### ISSUE TITLE
Bootstrap fails if the template comes up with an IP before customization

### ISSUE THREAD

**Issue by hufman** [chef-partners/knife-vsphere#130]
If you have a Linux VM that boots up and VMware sees that it has an IP before VMware changes the configuration to use a different IP, knife-vsphere may find this first IP and attempt to bootstrap with it.
Documentation should be added to mention the fact that templates should not have an automatic network enabled, or the code should keep checking with VMware to see what the VM's current IP is.

**Comment by swalberg** [comment]
Thanks. I'd like to have some kind of checklist for creating a good template, as a few issues have been related to this. If anyone has some thoughts there, this would be a good spot to put them.

**Comment by swalberg** [comment]
Created a Wiki document to start. https://github.com/chef-partners/knife-vsphere/wiki/Making-a-template-for-cloning
