### ISSUE TITLE
For discussion: Testing

### ISSUE THREAD

**Issue by swalberg** [chef-partners/knife-vsphere#151]
I'd love to have some testing in this so we can do more aggressive refactoring.

I was thinking either rspec or cucumber, but would love to hear other thoughts.

cc / @DennisBP

**Comment by DennisBP** [comment]
Some testing would be very nice, but I have no idea which is the best tool for this kind of tests.

**Comment by spudnic** [comment]
This kind of thing is kind of hard to unit test.  But Integration testing using kitchen-vsphere(https://rubygems.org/gems/kitchen-vsphere/versions/0.2.0)  may be a good route.

**Comment by swalberg** [comment]
Interesting, @spudnic, thanks! I will look into that.

**Comment by cmluciano** [comment]
Unit tests can def be invaluable for any ruby code though and I think this plugin could def use some unit tests.

**Comment by swalberg** [comment]
I've been playing with Cucumber and have been getting somewhere. Basically the idea is to mock out rbvmobi enough that we can call the plugin with various args and test whether or not it's making the right api calls.

https://github.com/swalberg/knife-vsphere/tree/cucumber

```
Feature: list vlans
  Background:
    Given a vsphere server at 1.1.1.1
    And a DC named test
  Scenario: vlans exist
    When I run 'knife vsphere vlan list --vspass=hello --vsdc=test'
    Then the output should have 2 lines
```

**Comment by swalberg** [comment]
Closing this, as we have started to use rspec.

**Comment by kenny-evitt** [comment]
@swalberg You never actually closed this :smile:

**Comment by swalberg** [comment]
![image](https://cloud.githubusercontent.com/assets/221368/14682908/f6bb2382-06f5-11e6-982e-cfc032897616.png)
