### ISSUE TITLE
VMDK add function returns unauthorized

### ISSUE THREAD

**Issue by dpmitchell** [chef-partners/knife-vsphere#190]
Hi,

Bumped into an issue where when adding a disk to a VM:

knife vsphere vm vmdk add vmd-test-app1 30 -f "Test" --vmdk-type "thin"
Datastore: NoBackup-* (2.71 TB(2981151899648) / 7.00 TB)
Choosing: NoBackup-*
Next vmdk name is => [NoBackup-*] vmd-test-app1/vmd-test-app1_1.vmdk
ERROR: RuntimeError: #<Net::HTTPUnauthorized 401 Unauthorized readbody=true>

This happens wether the VM is powered off or on.

Running with -VV I get the following stack trace:
/Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Datastore.rb:19:in `exists?': #<Net::HTTPUnauthorized 401 Unauthorized readbody=true> (RuntimeError)
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/gems/knife-vsphere-1.2.2/lib/chef/knife/vsphere_vm_vmdk_add.rb:89:in `run'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/gems/chef-12.4.1/lib/chef/knife.rb:425:in `block in run_with_pretty_exceptions'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/gems/chef-12.4.1/lib/chef/local_mode.rb:39:in `with_server_connectivity'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/gems/chef-12.4.1/lib/chef/knife.rb:424:in `run_with_pretty_exceptions'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/gems/chef-12.4.1/lib/chef/knife.rb:215:in `run'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/gems/chef-12.4.1/lib/chef/application/knife.rb:142:in `run'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/gems/chef-12.4.1/bin/knife:25:in `<top (required)>'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/bin/knife:23:in `load'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/bin/knife:23:in `<main>'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/daniel.mitchell/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'

I don't think this is a permission issue as I'm able to add disks via the GUI. Also it's the unauthorized message instead of a forbidden one. 

Cheers

**Comment by swalberg** [comment]
Thanks for reporting this and providing sample output. Any chance there's something logged on the Vsphere server? And which version of vsphere are you running?

**Comment by jjasghar** [comment]
If you are still having issues, please reopen this with some new errors so we can help debug.
