### ISSUE TITLE
knife vsphere vm clone with VDS

### ISSUE THREAD

**Issue by hbombonato** [chef-partners/knife-vsphere#200]
Hello Folks,

I do not know if missing parameters something, but the clone with a VDS is not working, the clone is completed anyway and no errors in vmware event, however they portgroup is not present in VM.

```knife vsphere vm clone habari-1 --template Template-Centos66 -f Templates -d DC --resource-pool QA --bootstrap true --distro chef-full --cdnsips 172.16.27.131 --cdnssuffix lab.local.io --cdomain lab.local.io --cvlan 1234 --cgw 172.16.170.1 --cips 172.16.170.21/23 --ssh-user root --ssh-password 'q1w2e3r4t5' -N nhabari-1.lab.local.io --dest-folder 'Tools' -E QA -r 'role[base-centos]' --ccpu 2 --cram 2 --config /opt/spec.chef/knife-qa.rb```

How do I fix this?

thx,

Hernani

**Comment by swalberg** [comment]
Hi Hernani,

Does your template have the network interface already created? In the clone phase, I don't believe we create any NICs; we just assign IPs to the ones from the template.

**Comment by hbombonato** [comment]
Hello,
Yep, the template have NIC in vss "VM Network" and when make the clone changed the portgroup to vds.

thank's for yout time :).

**Comment by swalberg** [comment]
Any chance you can include some screenshots? I guess I'm not clear on what's going on.

**Comment by hbombonato** [comment]
Okay, i try again. In my template we've one NIC and it has associated an stantard vswitch is my default. however when deployed new VM's with this template. 
<img width="188" alt="screen shot 2015-09-16 at 10 28 12 am" src="https://cloud.githubusercontent.com/assets/110977/9905919/12e34776-5c5e-11e5-981f-b4087e35d4ed.png">
<img width="652" alt="screen shot 2015-09-16 at 10 24 49 am" src="https://cloud.githubusercontent.com/assets/110977/9905920/12ec3ba6-5c5e-11e5-9dcc-3fb27028fb83.png">

**Comment by hbombonato** [comment]
Agian with network detail :).
<img width="656" alt="screen shot 2015-09-16 at 10 32 20 am" src="https://cloud.githubusercontent.com/assets/110977/9905961/53a6c0e4-5c5e-11e5-9d70-b9e94eccd900.png">

**Comment by hbombonato** [comment]
And when clone finished.
<img width="649" alt="screen shot 2015-09-16 at 10 38 27 am" src="https://cloud.githubusercontent.com/assets/110977/9906133/1eea3d44-5c5f-11e5-8290-33dbd237ac4f.png">

**Comment by hbombonato** [comment]
This is esxi log when deploy the template
hostd.log:2015-09-16T13:43:54.862Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] sleepState value is 0
hostd.log:2015-09-16T13:43:54.862Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] MKS ready for connections: true
hostd.log:2015-09-16T13:43:54.862Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Version status of tools changed to: 1
hostd.log:2015-09-16T13:43:54.863Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Tools version changed to: 9216
hostd.log:2015-09-16T13:43:54.941Z [46381B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:43:54.960Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 87 (msecs)
hostd.log:2015-09-16T13:43:55.103Z [46381B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:43:55.139Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 79 (msecs)
hostd.log:2015-09-16T13:43:55.260Z [46381B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:43:55.303Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 95 (msecs)
hostd.log:2015-09-16T13:43:55.359Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Imgcust event values read from vmdb tree are state = 1, errorCode = 0, errorMsgSize = 0
hostd.log:2015-09-16T13:43:55.361Z [46381B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Running status of tools changed to: 0
hostd.log:2015-09-16T13:43:55.477Z [467C0B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:43:55.494Z [467C0B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 42 (msecs)
hostd.log:2015-09-16T13:43:55.710Z [46444B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:43:55.726Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 49 (msecs)
hostd.log:2015-09-16T13:44:01.826Z [4A681B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Actual VM overhead: 40062976 bytes
hostd.log:2015-09-16T13:44:15.345Z [4A703B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:44:15.360Z [4A703B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 36 (msecs)
hostd.log:2015-09-16T13:44:45.343Z [499C1B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Tools guest daemon status changed to: 1
hostd.log:2015-09-16T13:44:45.344Z [499C1B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] guest operations are ready
hostd.log:2015-09-16T13:44:45.344Z [499C1B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] CheckHeartbeatMonitor: Reviving the heartbeat monitor in 30 seconds
hostd.log:2015-09-16T13:44:45.367Z [46403B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Imgcust event values read from vmdb tree are state = 2, errorCode = 0, errorMsgSize = 0
hostd.log:2015-09-16T13:44:45.370Z [50580B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Tools are auto-upgrade capable
hostd.log:2015-09-16T13:44:45.371Z [46340B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Tools are operations ready
hostd.log:2015-09-16T13:44:45.734Z [45F81B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Skipped tools ManifestInfo update.
hostd.log:2015-09-16T13:44:45.734Z [45F81B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Version status of tools changed to: 1
hostd.log:2015-09-16T13:44:45.774Z [45F81B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:44:45.791Z [45F81B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 45 (msecs)
hostd.log:2015-09-16T13:44:45.816Z [45F81B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Imgcust event values read from vmdb tree are state = 4, errorCode = 0, errorMsgSize = 38
hostd.log:2015-09-16T13:44:45.817Z [45F81B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Message: /var/log/vmware-imc/toolsDeployPkg.log
hostd.log:2015-09-16T13:44:45.817Z [45F81B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Failed to find activation record, event user unknown.

**Comment by hbombonato** [comment]
hostd.log:2015-09-16T13:45:02.802Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Message: /var/log/vmware-imc/toolsDeployPkg.log@4000
hostd.log:2015-09-16T13:45:02.802Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] 4000
hostd.log:2015-09-16T13:45:02.803Z [46444B90 info 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Enabling NICs following customization: (vim.vm.ConfigSpec) {
hostd.log:2015-09-16T13:45:02.810Z [46444B90 info 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] State Transition (VM_STATE_ON -> VM_STATE_RECONFIGURING)
hostd.log:2015-09-16T13:45:02.810Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Invoking interceptor:1-hbr
hostd.log:2015-09-16T13:45:02.810Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Done invoking interceptor:1-hbr
hostd.log:2015-09-16T13:45:02.961Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Current VM Tracking state: disabled
hostd.log:2015-09-16T13:45:02.993Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Setting VM's tracking state to disabled.
hostd.log:2015-09-16T13:45:05.858Z [46598B90 info 'vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx']  Disconnect check in progress.
hostd.log:2015-09-16T13:45:05.858Z [4677FB90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Retrieved current VM state from foundry 4, 8
hostd.log:2015-09-16T13:45:05.858Z [4677FB90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Received a duplicate transition from foundry: 8, 1
hostd.log:2015-09-16T13:45:05.868Z [46444B90 info 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] State Transition (VM_STATE_RECONFIGURING -> VM_STATE_ON)
hostd.log:2015-09-16T13:45:05.893Z [46444B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:45:05.919Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 48 (msecs)
hostd.log:2015-09-16T13:45:05.943Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Handling message _vmx4: Failed to connect virtual device Ethernet0.
hostd.log:2015-09-16T13:45:05.944Z [46444B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Failed to find activation record, event user unknown.
hostd.log:2015-09-16T13:45:05.945Z [46444B90 info 'Vimsvc.ha-eventmgr'] Event 56807 : Error message on habari-1 on dc1-z1-h10 in ha-datacenter: Failed to connect virtual device Ethernet0.
hostd.log:2015-09-16T13:45:05.952Z [46598B90 info 'vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx']  Disconnect check in progress.
hostd.log:2015-09-16T13:45:05.954Z [FFC99D20 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Retrieved current VM state from foundry 4, 8
hostd.log:2015-09-16T13:45:06.013Z [46444B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:45:06.033Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 64 (msecs)
hostd.log:2015-09-16T13:45:06.094Z [46444B90 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Unable to get network object for network 1227
hostd.log:2015-09-16T13:45:06.112Z [46444B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Time to gather config: 43 (msecs)
hostd.log:2015-09-16T13:45:06.128Z [53080B90 info 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Answered question _vmx4
hostd.log:2015-09-16T13:45:06.129Z [FFC99D20 warning 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Received a duplicate transition from foundry: 8, 1
hostd.log:2015-09-16T13:45:09.976Z [4A640B90 verbose 'Vmsvc.vm:/vmfs/volumes/1e9373ca-19e65007/habari-1/habari-1.vmx'] Imgcust event values read from vmdb tree are state = 4, errorCode = 103, errorMsgSize = 43

**Comment by swalberg** [comment]
Hmmm.  "Unable to get network object for network 1227" appears a bit. Wondering if we're looking for a distributed switch?

**Comment by hbombonato** [comment]
Yes, we've two type the switches in vmware, "virtual standard switch" vss (VM Network) and "virtual distributed switch" vds (1227).

**Comment by swalberg** [comment]
Can you try your template starting off as a distributed switch please?

**Comment by hbombonato** [comment]
knife vsphere vm clone -VV habari-2 --template Template-Centos66 -f Templates -d DC --resource-pool QA --bootstrap true --distro chef-full --cdnsips 172.16.27.131 --cdnssuffix lab.local.io --cdomain lab.local.io --cvlan 1227 --cgw 172.16.170.1 --cips 172.16.170.22/23 --ssh-user root --ssh-password 'q1w2e3r4t5' -N habari-2.lab.local.io --dest-folder 'Templates' -E QA -r 'role[base-centos]' --ccpu 2 --cram 2
DEBUG: value for config item bootstrap: true
DEBUG: value for config item distro: chef-full
DEBUG: value for config item vsphere_host: vc.loca.io
DEBUG: value for config item vshere_path:
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: habombo@loca.io
DEBUG: value for config item vsphere_pass: MAni113912
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: DC
DEBUG: value for config item folder: Templates
DEBUG: value for config item vsphere_dc: DC
DEBUG: value for config item linked_clone:
DEBUG: value for config item resource_pool: QA
DEBUG: value for config item resource_pool: QA
DEBUG: value for config item vsphere_dc: DC
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_memory: 2
DEBUG: value for config item customization_memory: 2
DEBUG: value for config item customization_vlan: 1227
DEBUG: value for config item customization_vlan: 1227
DEBUG: value for config item vsphere_dc: DC
/Library/Ruby/Gems/2.0.0/gems/knife-vsphere-0.9.9/lib/chef/knife/vsphere_vm_clone.rb:337:in `rescue in generate_clone_spec': undefined method `deviceName=' for #<RbVmomi::VIM::VirtualEthernetCardDistributedVirtualPortBackingInfo:0x007fc2c3e138a8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/knife-vsphere-0.9.9/lib/chef/knife/vsphere_vm_clone.rb:332:in `generate_clone_spec'
	from /Library/Ruby/Gems/2.0.0/gems/knife-vsphere-0.9.9/lib/chef/knife/vsphere_vm_clone.rb:231:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.14.6/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.14.6/lib/chef/knife.rb:174:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.14.6/lib/chef/application/knife.rb:139:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.14.6/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:23:in `load'
	from /usr/bin/knife:23:in `<main>'

**Comment by swalberg** [comment]
Oh, you seem to be running a really old version of this gem, can you update please? `gem install knife-vsphere`

**Comment by hbombonato** [comment]
Mr. swalberg
Oh! Past update for last version any clone is working! However VDS on template is required.
Thank's for your time, i appreciate so much your help.

knife vsphere vm clone -VV habari-2 --template Template-Centos66 -f Templates -d DC --resource-pool QA --bootstrap true --distro chef-full --cdnsips 172.16.27.131 --cdnssuffix lab.local.io --cdomain lab.local.io --cvlan 1227 --cgw 172.16.170.1 --cips 172.16.170.22/23 --ssh-user root --ssh-password 'q1w2e3r4t5' -N habari-2.lab.local.io --dest-folder 'Templates' -r 'role[base-centos]' --ccpu 2 --cram 2
DEBUG: value for config item chef_node_name: habari-2.lab.local.io
DEBUG: value for config item vsphere_host: vc.local.io
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: habombo@local.io
DEBUG: value for config item vsphere_pass: dfdfd12323@#
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: DC
DEBUG: value for config item folder: Templates
DEBUG: value for config item vsphere_dc: DC
DEBUG: value for config item linked_clone:
DEBUG: value for config item resource_pool: QA
DEBUG: value for config item resource_pool: QA
DEBUG: value for config item vsphere_dc: DC
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_memory: 2
DEBUG: value for config item customization_memory: 2
DEBUG: value for config item customization_vlan: 1227
DEBUG: value for config item customization_vlan: 1227
DEBUG: value for config item vsphere_dc: DC
DEBUG: value for config item customization_spec:
DEBUG: value for config item customization_dns_ips: 172.16.27.131
DEBUG: value for config item customization_dns_ips: 172.16.27.131
DEBUG: value for config item customization_dns_suffixes: lab.local.io
DEBUG: value for config item customization_dns_suffixes: lab.local.io
DEBUG: value for config item customization_gw: 172.16.170.1
DEBUG: value for config item customization_gw: 172.16.170.1
DEBUG: value for config item disable_customization:
DEBUG: value for config item customization_domain: lab.local.io
DEBUG: Identified os as linux.
DEBUG: value for config item customization_domain: lab.local.io
DEBUG: value for config item customization_domain: lab.local.io
DEBUG: value for config item customization_plugin:
DEBUG: value for config item vsphere_dc: DC
Cloning template Template-Centos66 to new VM habari-2
Finished creating virtual machine habari-2
DEBUG: value for config item customization_plugin:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item power:
DEBUG: value for config item bootstrap: true
Powered on virtual machine habari-2
DEBUG: value for config item bootstrap: true
DEBUG: Connect Host for Bootstrap: 172.16.170.22
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item bootstrap_protocol:

Hernani

**Comment by swalberg** [comment]
Thanks for the confirmation on the type of switch. Glad to hear you're up and running! Check back frequently at https://rubygems.org/gems/knife-vsphere, as we release updates as new stuff and bugfixes come in.
