### ISSUE TITLE
Can't find host and VMs if host moved to different datacenter.

### ISSUE THREAD

**Issue by LKHetzel** [chef-partners/knife-vsphere#204]
I am in the beginning phases of moving VMs from one host to another. I currently have 2 hosts, the "old" and the new, destination host. Initially, I was able to query the datacenter with ```knife vsphere vm list -D my_datacenter``` and see my VMs.

```
[lhetzel@chef-workstation chef]$ knife vsphere vm list --vsnossl --vsinsecure -D My\ Datacenter
[2015-10-12T16:19:21-07:00] WARN: Please install an English UTF-8 locale for Chef to use, falling back to C locale and disabling UTF-8 support.
Folder:
        VM Name: sa1
                IP:
                RAM: 2048
                State: off
        VM Name: di2
                IP:
                RAM: 4096
                State: off
```

 I did not originally have the hosts in the same datacenter, so I moved the one containing the VMs to the one where the new host lives.

As a test, to ensure I could see them, I ran the command again, using the new datacenter, and only the VMs on the destination host shows up. 

```
[lhetzel@chef-workstation chef]$ knife vsphere vm list --vsnossl --vsinsecure -D New\ Datacenter
[2015-10-12T18:26:01-07:00] WARN: Please install an English UTF-8 locale for Chef to use, falling back to C locale and disabling UTF-8 support.
Folder:
        VM Name: VMware vCenter Server Appliance
                IP: <valid IP here>
                RAM: 8192
                State: on
        VM Name: test-vm-2
                IP:
                RAM: 512
                State: on
```

When I run ```knife vsphere hosts list --vsnossl --vsinsecure```, I only see one pool, with my destination host. 

```
[lhetzel@chef-workstation chef]$ knife vsphere hosts list --vsnossl --vsinsecure
[2015-10-12T18:30:47-07:00] WARN: Please install an English UTF-8 locale for Chef to use, falling back to C locale and disabling UTF-8 support.
Pool: 10.1.69.10
  Host: 10.1.69.10
```

How can I get knife to see the missing host again? vSphere sees this and can interact with it, and for what it's worth, knife-esx can also interrogate this host.

**Comment by swalberg** [comment]
Does it change if you add `--recursive`?  Can you also add `--trace`? 

And just to confirm, you're on version 1.2.4 of this gem?

**Comment by LKHetzel** [comment]
Adding recursive fixed the problem. ```--trace``` appears to be unsupported. I am on 1.2.4. Guess I missed the fact that these are nested in folders.

Strangely enough, removing and re-adding the host to vCenter in the correct datacenter lists them without having to be recursive.

Thanks for the assist, although I'll probably have to open a different issue for a different problem...

**Comment by swalberg** [comment]
Doh, I should have said `-VV`. We should make folder structure clear so surprises like this don't happen. There seems to be a difference with what's shown in the vCenter display and the tree we get through the API.
