### ISSUE TITLE
Cannot Authenticate using Windows AD credentials

### ISSUE THREAD

**Issue by drahamim** [chef-partners/knife-vsphere#205]
I am getting the same error as in #3.  I have tested that the credentials work via the Vsphere application. Is there anything I need to enable on the Vcenter side?

I have tried using Base64: obvuscation, Plain text, With and without DOMAIN\

**Comment by swalberg** [comment]
Hi, I don't believe you need anything special. Are you seeing any logs on the vcenter side? Your user is a full administrator?

When you try it with `domain\`, try doubling the back slashes, e.g. `DOMAIN\\username`.

**Comment by drahamim** [comment]
I fixed it sort of. (just before I saw your reply) I tried the double back slash trick and that worked. 
But I am watching the logs in VCenter and when I try and query for "vm list" it looks like it tries to authenticate ignoring the two back slashes. 

Vsphere hosts list yields an attempt of just username (ignores domain and slashes)
running above using sudo knife vsphere hosts list returns correct response but I shouldn't need to run this with sudo to do so. 

vsphere vm list is the same as above (except in the sudo case it still doesn't seem to be able to list the VMs in the cluster)

**Comment by swalberg** [comment]
So `vlan list` works but `vm list` doesn't? Or is everything working?

**Comment by drahamim** [comment]
correct. Vlan list works but vm list doesn't.

**Comment by swalberg** [comment]
Have you checked your account permissions in vSphere? All the commands in this gem connect with the same method so I'd expect if one works, they all work.

**Comment by drahamim** [comment]
Permissions look ok. 
(now ' hosts list' works with out sudo) <- not sure why that was an issue
but 'vm list' still doesn't yield list of vms. 

Could structure be an issue? 
Vcenter
|-DataCenter
  |- Cluster
     |-VMs

Do I need to specify Cluster?

**Comment by swalberg** [comment]
Hi, I just noticed this is still an issue. Did you specify the `-r` option to indicate "recursive"? Sometimes it's needed depending on the structure.

**Comment by drahamim** [comment]
Sorry this took so long to reply. Yes it appears that the -r flag seems to be needed to see into sub folders as we sort our VMs.

**Comment by drahamim** [comment]
feel free to close this issue as the original issue is resolved. Unless you want to keep this open. I do have some other issues but I think I will open/find a different issue for that one.
