### ISSUE TITLE
Support for Storage Increase

### ISSUE THREAD

**Issue by warroyo** [chef-partners/knife-vsphere#206]
I am not sure if I am just missing it, but it would be awesome to be able to increase the storage on the vm when cloning. Is this something that is going to be added?

**Comment by swalberg** [comment]
Hi waroyo, we don't have that built in to the gem but you could write a plugin that would do it.

```
--cplugin CUST_PLUGIN_PATH - Path to plugin that implements KnifeVspherePlugin.customize_clone_spec and/or KnifeVspherePlugin.reconfig_vm
--cplugin-data CUST_PLUGIN_DATA - String of data to pass to the plugin.  Use any format you wish.
```

There's some small examples in the readme.

I haven't done it myself, but it looks like https://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.VirtualDiskManager.html is a good place to start.

I'm not sure if you're familiar with Ruby or not, so I'm sorry if this isn't helpful.

**Comment by warroyo** [comment]
I will give this a try, thank you!

**Comment by n8gard** [comment]
+1 for this. Not sure if I can actively help, but I'd be happy to try.

**Comment by gitfirenz** [comment]
Hello,
I've just added some function to knife vsphere : one to resize a disk (increase), one to list disk size. I'm a total noob to GIT,and i've just send the code to the author.

Here is my raw code to resize, to put in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/knife-vsphere-1.2.3/lib/chef/knife/vsphere_vm_vmdk_resize.rb : 

```
require 'chef/knife'
require 'chef/knife/base_vsphere_command'

class Chef::Knife::VsphereVmVmdkExtend < Chef::Knife::BaseVsphereCommand
  banner 'knife vsphere vm vmdk extend VMNAME DISK_NUM DISK_GB'

  common_options

  option :vmdk_type,
         long: '--vmdk-type TYPE',
         description: 'Type of VMDK',
  
         default: 'thin'

  option :target_lun,
         long: '--target-lun NAME',
         description: 'name of target LUN'

  def run
    $stdout.sync = true

    vmname = @name_args[0]
    if vmname.nil?
      show_usage
      ui.fatal('You must specify a virtual machine name')
      exit 1
    end

    disk_num = @name_args[1]
    if disk_num.nil?
      ui.fatal 'You need a disk number !'
      show_usage
      exit 1
    end

    size = @name_args[2]
    if size.nil?
      ui.fatal 'You need a VMDK size!'
      show_usage
      exit 1
    end

    vim = vim_connection
    vm = get_vm(vmname)
    if vm.nil?
      puts "Could not find #{vmname}"
      return
    end

    vmdk_size_kb = size.to_i * 1024 * 1024

    vm.config.hardware.device.each do |device|
      if device.class == RbVmomi::VIM::VirtualDisk
        if device.deviceInfo.label == "Hard disk #{disk_num}"
          puts "Disk #{disk_num} found !"
          puts device.capacityInKB
          puts device.unitNumber
          device.capacityInKB=vmdk_size_kb

          device_config_spec = RbVmomi::VIM::VirtualDeviceConfigSpec(
            device: device,
            operation: RbVmomi::VIM::VirtualDeviceConfigSpecOperation('edit')
          )

          vm_config_spec = RbVmomi::VIM::VirtualMachineConfigSpec(
            deviceChange: [device_config_spec]
          )

          vm.ReconfigVM_Task(spec: vm_config_spec).wait_for_completion
        end
      end
    end
  end
end
```

**Comment by gitfirenz** [comment]
And to list 

```
require 'chef/knife'
require 'chef/knife/base_vsphere_command'

# Add a new disk to a virtual machine
class Chef::Knife::VsphereVmVmdkList < Chef::Knife::BaseVsphereCommand
  banner 'knife vsphere vm vmdk list VMNAME'

  common_options

  def run
    $stdout.sync = true

    vmname = @name_args[0]
    if vmname.nil?
      show_usage
      ui.fatal('You must specify a virtual machine name')
      exit 1
    end

    vim = vim_connection
    vm = get_vm(vmname)
    if vm.nil?
      puts "Could not find #{vmname}"
      return
    end

    vm.config.hardware.device.each do |device|
      if device.class == RbVmomi::VIM::VirtualDisk
        if device.deviceInfo.label =~ /Hard disk/
          puts device.capacityInKB/1024/1024
        end
      end
    end
  end
end
```

**Comment by swalberg** [comment]
Hey thanks! If you can get onto #rbvmomi on Freenode IRC, I'll walk you through the git stuff. No reason you shouldn't get credit for this work on your GitHub profile. There's a web interface at https://webchat.freenode.net/ if you don't have an IRC client handy.

**Comment by mheidenr** [comment]
```if device.deviceInfo.label == "Hard disk #{disk_num}"``` will not work with other languages than English
![2015-11-11 09_28_19-managed object browser](https://cloud.githubusercontent.com/assets/3294195/11086984/b51215a8-8856-11e5-924f-ad8552285aa0.png)

I was working on the same functionality, see https://github.com/chef-partners/knife-vsphere/pull/209

**Comment by mheidenr** [comment]
I think this issue is done now via #209 & #211 aka the ```vsphere vm disk``` command

**Comment by swalberg** [comment]
If I'm reading it right, the original request was to support this while cloning rather than after the clone.

However I think the pull requests we put together are close enough to close this. Someone who is interested in doing this at clone time would want to copy some of the code from #209 or use the `vsphere vm disk extend` command to do it after the clone.
