### ISSUE TITLE
Issue with base64 password

### ISSUE THREAD

**Issue by wingZero21** [chef-partners/knife-vsphere#215]
Hi,

When using this it seems to work fine when adding the password in plain text, however when adding in the base64 equivilant it seems to bring up the below error.

Can you recommend the best command to get the right base64 output for this. I have tried with the below commands to generate base64.

Details:
Error
```
ERROR: RbVmomi::Fault: InvalidLogin: Cannot complete login due to an incorrect user name or password.
```

Base64 Commands
```
openssl enc -base64 <<< 'PASSHERE'

echo -n 'PASSHERE' | base64
```

**Comment by wingZero21** [comment]
Hi,

Re-read the page and it mentioned appending base64: to the password section.

Fixed.

**Comment by swalberg** [comment]
Good to hear you got it working!
