### ISSUE TITLE
Issue with clone guest operating system

### ISSUE THREAD

**Issue by wingZero21** [chef-partners/knife-vsphere#216]
Hi,

We are seeing the below error when attempting to clone a VM currently.

Can you advise what might be causing this to occur. Currently we are attempting to clone from a template which does not contain vmtools or a distro, however the distro has been set to red hat 6 in the options.

The clone does complete however were unable to start the server via the knife command line tools, however when doing this via the GUI it does switch on without issue.

Details:
```
gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion': UncustomizableGuest: Customization of the guest operating system 'rhel6_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations. (RbVmomi::Fault)
        from C:/Users//AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.6/lib/chef/knife/vsphere_vm_clone.rb:322:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/knife.rb:203:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/knife.rb:142:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:64:in `load'
        from C:/opscode/chefdk/bin/knife:64:in `<main>'```

**Comment by swalberg** [comment]
Hi, can you paste in the command line(s) you're running?

The `vsphere vm clone` command is geared towards cloning and customizing a guest, which does require an OS with the tools installed.

**Comment by wingZero21** [comment]
Hi,

The command we are running is below.

Details:
```
knife vsphere vm clone devtestapp001 --folder 'DIG Templates/Cobbler Bases' --template dev_base_no_os_hardware10_test --dest-folder 'DIG VMs' --datastore 'DATASTORE001'
```

**Comment by swalberg** [comment]
Hm, I'm not seeing why line 322 would be causing a problem.  On a hunch, can you try `--cspec` with a customization spec on the server, or `--disable-customization` ?

**Comment by davemeekin** [comment]
Hi,

I'm a colleague of wingZero21.....At the moment we pxe boot our VM's once created and use cobbler to install the OS. So we may be trying to use 'knife-vsphere' in an unintended way.

We deploy manually via vsphere at the moment from templates and select the 'Do not customize' option when it comes to Guest Customization. 

![capture](https://cloud.githubusercontent.com/assets/14975831/12038434/fab70266-ae4f-11e5-8a90-5b791771ed48.PNG)

Can a combination of 'knife-vsphere' options mimic this functionality?

I think what we may require is a method to call the vsphere API's 'CreateVM_Task' rather than 'CloneVM_Task'. Alternatively we move away from pxe boot installs and create pre-installed OS templates (probably the best solution)

Maybe we could work on 'CreateVM_Task' functionality unless you don't think this would be a good addition to the tool set.

**Comment by swalberg** [comment]
Yea, so cloning is a bit of a waste for you given your current tooling.

In general, I think anything exposed by the API is fair game for this gem.

I think what you want is a separate command `knife vsphere vm create` that does the `CreateVM_Task`, as you said. I'm usually on #rbvmomi on freenode if you need a hand.

**Comment by davemeekin** [comment]
Thanks for your comments we'll discuss how we approach this internally and get in touch if we venture down the vm create path. Feel free to close this non issue. Thanks

**Comment by swalberg** [comment]
You're welcome! Good luck in whichever direction you go.
