### ISSUE TITLE
Query on viewing network/mac address of created vm

### ISSUE THREAD

**Issue by wingZero21** [chef-partners/knife-vsphere#217]
Hi,

Do you know if its possible to grab the mac address from a newly created vm or if this can be queried at all?

**Comment by swalberg** [comment]
Sure is.. have a look at the `knife vsphere vm show` command, which doesn't seem to be documented in the README :(

```knife vsphere vm show seantest guest.net[0].macAddress
00:50:56:94:70:c2
```

**Comment by wingZero21** [comment]
Hey,

Thanks for the response. Just to confirm is the network adapter name or the network adapter tag that is in vSphere.

Cheers

**Comment by swalberg** [comment]
Sorry, I'm not understanding the question. `seantest` is the name of my vm. `guest.net[0].macAddress` shows the first (0 indexed) network adapter of the VM no matter what it's called. You can see all the stuff that you can query at http://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.VirtualMachine.html

**Comment by wingZero21** [comment]
Hi,

Does the machine need to be powered on for this to work?

I tried running the command with the guest.net[0].macAddress and got the below error.

Details:
```
FATAL: "guest.net[0].macAddress" not recognized.
```

**Comment by swalberg** [comment]
Nope, my VM was off. Does it have a network card and the tools installed? (I suspect anything under `guest` might come through the tools) Can you get `config.info` instead?

**Comment by jjasghar** [comment]
Please reopen this if you are still interested in continuing this.
