### ISSUE TITLE
knife vsphere does not take --format/-F option

### ISSUE THREAD

**Issue by kareiva** [chef-partners/knife-vsphere#220]
How to reproduce: 

In the ~/.chef/knife.rb:
`knife[:format]     = 'json'`

``` shell
$ knife vsphere vm list --vsdc Mgmt --format json
Folder:
        VM Name: vCenter_appliance
                IP: 10.10.10.10
                RAM: 32768
                State: on
...
```

**Comment by swalberg** [comment]
Hi, thanks for this report. This is going to be universal within the gem. Pretty much all the output is done with `puts` or some kind of call to one of the knife helpers that calls `puts` with some color.

Can you explain what you'd like to do with the json output?

Thanks,

Sean

**Comment by kareiva** [comment]
Well, I would like to make use the structured json (or yaml or etc.) output like one would want with any case of using the knife tool. A valid example might be to get a structured list of vsphere folders where you do not have to count the spaces to see which folder belongs to where.

**Comment by warroyo** [comment]
This would be a very useful feature. I have a few use cases where being able to parse the output easily into other applications/scripts would be very helpful.

I don't mind working on getting some initial functionality implemented.

**Comment by swalberg** [comment]
Hi Will, I recently noticed that the base knife classes have a presenter system [def output](https://github.com/chef/chef/blob/811cbff2baaf0c5f8ad78cbaf6e62db969842827/lib/chef/knife/core/ui.rb#L127-L132)

If you wanted to spend a few minutes investigating this to see if it will do the job, I think that would be a great start.

**Comment by warroyo** [comment]
@swalberg it looks that will work for  outputting the data in the specified format with --format. 

here is an example using the `template list` command

I made the modification below to https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_template_list.rb#L26-L28:

```ruby
    vm_list =[]
    vms.each do |vm|
        vm_info = {"Template Name" => vm.name}
        vm_list << vm_info
    end

   ui.output(vm_list)
````

the output then returns as follows without `--format specifed`

![image](https://cloud.githubusercontent.com/assets/616621/21155626/12b3a75e-c130-11e6-901a-054c88ab2b30.png)


and with `--format json`

```json
[
  {
    "Template Name": "DEVOPS-CENTOS7.2-MIN-NONPROD-DMZ-V1"
  },
  {
    "Template Name": "DEVOPS-CENTOS7.2-MIN-DEV-INT-V1"
  },
]
```


I also tried `--format yml` which properly displayed the results in yml.


what do you think about this approach?

**Comment by swalberg** [comment]
That's perfect! I'm glad it worked. It should make testing much easier, too, which is something that's been holding me back.

Just as a point of style we can shorten that up with a `#map`.

```
vm_list =vms.map do |vm|
                 {"Template Name" => vm.name}
              end
ui.output(vm_list)
```

Can you put a pull request in for that file?

I think from here we just look for PRs on a command-by-command basis. I'm happy to pitch in, too.

**Comment by swalberg** [comment]
Sorry, didn't mean to imply you should do all the work for this. Whatever you feel like contributing will be appreciated, and this project will just pick the remaining ones off as time permits, or as other people send contributions.

**Comment by warroyo** [comment]
PR submitted https://github.com/chef-partners/knife-vsphere/pull/327

**Comment by warroyo** [comment]
@swalberg I have been looking into a few other commands and it looks like the structure of the output will need to change in order for the multi formatted output to make sense. 

for example `datastore_list`

current output is :

`Datastore: mydatsatore (134.55 GB / 2.00 TB)`


this wouldn't work very well as formatted json. I was thinking something like the example below would work well.

```json
[
  {
    "Datastore": "mydatastore",
    "Free": "134.55 GB",
    "Capacity": "2.0 TB"
  }
]
````


Is changing the output format something that would be a problem? This would essentially break backwards compatibility for anyone that is parsing the output currently?

**Comment by swalberg** [comment]
Yea, that's totally cool. Anyone who was trying to parse the text can now have some good JSON to work with.

**Comment by swalberg** [comment]
Closing this as many of the big commands have been moved over. Happy to take PRs or issues dealing with specific commands though if there is a need.
