### ISSUE TITLE
 ERROR: RbVmomi::Fault: NicSettingMismatch: fault.NicSettingMismatch.summary

### ISSUE THREAD

**Issue by mlckha** [chef-partners/knife-vsphere#222]
Hi,
I Can't add any arguments to my knife command but the vm creation works all time. Anyone have idea about this error ?
Thank's for help,
Regards,
![test](https://cloud.githubusercontent.com/assets/4509437/12396439/d080a778-be07-11e5-9726-d1f97601c059.png)

**Comment by swalberg** [comment]
Hi, I'm sorry you're running into problems here. I think it may have to do with the configuration of your template. Does it have any NICs on it? You may have to configure the NICs by adding `--cips 192.168.0.99/24` (or whatever IP suits you).

**Comment by mlckha** [comment]
Hi, thank's for your fast help.
I have this error now 
![2](https://cloud.githubusercontent.com/assets/4509437/12412704/121ced5a-be89-11e5-8c64-8b9a745d14d6.png)

**Comment by mlckha** [comment]
I don't understand why i have this error !
![22](https://cloud.githubusercontent.com/assets/4509437/12413860/178ee708-be92-11e5-8320-6f4f97f61c14.png)

**Comment by mlckha** [comment]
WB, thx for your fast response. I have a new challenge for u.
Although I put in parameter I still have this new error:
![3](https://cloud.githubusercontent.com/assets/4509437/12413882/3c9f646e-be92-11e5-8a3c-41bf8eef9bdb.png)

Thank's for help,
Regards,

**Comment by swalberg** [comment]
Ah, this is cloning a Windows machine. We're probably running into #177. The current workaround is to specify the customizations such as DNS in a customization specification on the vsphere server and reference it with `--cspec`.

**Comment by mlckha** [comment]
Swalberg,
Thank you for your reply
I did not understand where to put these customization specifications in vSphere? (like DNS)
I need to reference it in a dedicated configuration file ? (with --cspec)

Thank's for help,
Regards,

**Comment by swalberg** [comment]
Hi, in the vSphere client, from the home page, you should see a menu item called "customization specification manager" where you can pre-fill in some configuration options for your VM. See the [detailed instructions](https://pubs.vmware.com/vsphere-51/index.jsp#com.vmware.vsphere.vm_admin.doc/GUID-7523239A-9BB8-4FAD-88F6-C8701933CA64.html) for the whole procedure.

During that procedure you'll give the customization specification a name, such as `my_windows`. When you clone the VM, pass `--cspec my_windows`.

Hope that helps.

**Comment by mlckha** [comment]
Thank you for help. That works.
Have a nice day :+1:
