### ISSUE TITLE
Knife Vsphere Clone VM - Windows

### ISSUE THREAD

**Issue by Robsi1** [chef-partners/knife-vsphere#229]
Hey All, 

Recently our VM Clone for windows VM's has been failing with Hostname Not Specified. 

We run the VM Clone command using a customisation script in VMWare for Doing the domain etc. And we pass the Hostname over with --chostname. This is trying to build from a Windows 2012 R2 Template. 

It doesn't look like the hostname param is being passed through - no customization_hostname value. 

```
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_memory: 4
DEBUG: value for config item customization_memory: 4
DEBUG: value for config item customization_vlan: Vlan_1
DEBUG: value for config item customization_vlan: Vlan_1
DEBUG: value for config item vsphere_dc: Duss
DEBUG: value for config item customization_spec: Chef
DEBUG: value for config item customization_spec: Chef
DEBUG: value for config item customization_dns_ips: x.x.x.x,x.x.x.x
DEBUG: value for config item customization_dns_ips: x.x.x.x,x.x.x.x
DEBUG: value for config item customization_dns_suffixes: Domain.com
DEBUG: value for config item customization_dns_suffixes: Domain.com
DEBUG: value for config item customization_gw: x.x.x.x
DEBUG: value for config item customization_gw: x.x.x.x
DEBUG: value for config item disable_customization: true
DEBUG: value for config item vsphere_dc: Duss
```

This did work and as far as i'm aware there have been no changes in our chef/vmware environment. 

this is my first post on GitHub, and first issue with Chef - If you need any more information please let me know .. and be nice :) 

Thanks 

Rob

**Comment by swalberg** [comment]
Hey Rob, sorry to hear you're having problems. Did you recently upgrade the gem or install it new?

Thanks for the debug output. Could you also please paste the exact command you're running (redact what you need to)? Some of our options, for better or worse, are contradictory. 

Also, paste in the output of `gem list knife-vsphere`, please.

Thanks,

Sean

**Comment by swalberg** [comment]
Oh, and welcome to Github and the Chef community!

**Comment by Robsi1** [comment]
Hey, 

Thanks.. 

```gem list knife-vsphere
*** LOCAL GEMS ***
knife-vsphere (1.2.7)```

Here is the command I am running: 

```knife vsphere vm clone "Test.Domain.com" -N Test --cdnsips x.x.x.x,x.x.x.x --cdnssuffix Domain.com --cips x.x.x.x/x —fqdn Test.Domain.com --cdomain Domain.com --cgw x.x.x.x --chostname Test --cvlan Vlan_1 --cspec Chef --cram 4 --ccpu 2 --datastore vsanDatastore --template Windows2012R2Template --dest-folder / --folder Templates --verbose --resource-pool vSAN/Rob -VV```

Some of these options may not apply to the vm clone command, but we will be wrapping the command in another script that bootstraps the node as we do with Linux at present. But this did build windows nodes fine a few weeks ago. 

Thanks

Rob

**Comment by swalberg** [comment]
So that line `DEBUG: value for config item disable_customization: true` means we're skipping over a lot of the customization to do with Windows, and the spec never gets the hostname. But normally you need to pass `--disable-customization` to do that. Do you maybe have it in a `knife.rb` or is the script you're using adding it in?

**Comment by Robsi1** [comment]
Ah, 

My apologies, I was following some debug steps online and added ```--disable-customization``` to the last test I did. I do get the issue if I don't have that in the command as well. Here is the debug output without ```--disable-customization```  in the command 

```DEBUG: value for config item chef_node_name: Test
DEBUG: value for config item vsphere_host: x.x.x.x
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: xxxx
DEBUG: value for config item vsphere_pass: xxxxx
DEBUG: value for config item vsphere_pass: xxxxxx
DEBUG: value for config item vsphere_pass: xxxxxx
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: Duss
DEBUG: value for config item folder: Templates
DEBUG: value for config item vsphere_dc: Duss
DEBUG: value for config item linked_clone:
DEBUG: value for config item resource_pool: vSAN/Rob
DEBUG: value for config item resource_pool: vSAN/Rob
DEBUG: value for config item vsphere_dc: Duss
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore: vsanDatastore
DEBUG: value for config item datastorecluster:
DEBUG: value for config item datastore: vsanDatastore
DEBUG: value for config item datastore: vsanDatastore
DEBUG: value for config item vsphere_dc: Duss
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_memory: 4
DEBUG: value for config item customization_memory: 4
DEBUG: value for config item customization_vlan: Vlan_1
DEBUG: value for config item customization_vlan: Vlan_1
DEBUG: value for config item vsphere_dc: Duss
DEBUG: value for config item customization_spec: Chef
DEBUG: value for config item customization_spec: Chef
DEBUG: value for config item customization_dns_ips: x.x.x.x,x.x.x.x
DEBUG: value for config item customization_dns_ips: x.x.x.x,x.x.x.x
DEBUG: value for config item customization_dns_suffixes: Domain.com
DEBUG: value for config item customization_dns_suffixes: Domain.com
DEBUG: value for config item customization_gw: x.x.x.x
DEBUG: value for config item customization_gw: x.x.x.x
DEBUG: value for config item disable_customization:
DEBUG: Identified os as windows.
DEBUG: value for config item customization_plugin:
DEBUG: value for config item vsphere_dc: Duss
Cloning template Windows2012R2Template to new VM Test.domain.com
ERROR: RbVmomi::Fault: InvalidArgument: A specified parameter was not correct: hostname```

Sorry for confusion there..

**Comment by swalberg** [comment]
Hey no problem.

I'm not seeing where "hostname" is needed in a clone spec (https://www.vmware.com/support/developer/converter-sdk/conv55_apireference/vim.vm.customization.IdentitySettings.html). Any chance that got added to the customization spec on the vsphere server?

Have you always used periods in the hostname `knife vsphere vm clone test.domain.com`?

**Comment by Robsi1** [comment]
The customization spec in VMWare has always had the "Enter a name in the Deploy Wizard" checked. this hasn't changed (as far as I know). But we have also named the machine using the knife vm clone command. 

And yes - We have multiple Domains here so fully qualifying the VM name with the domain is very useful. 

Thanks

**Comment by Robsi1** [comment]
Any ideas on this ? 

I want to define the hostname of the machine with the knife vsphere vm clone command... This used to work.. But I can't seem to get it applying at all now.

**Comment by swalberg** [comment]
Sorry nothing immediately comes to mind. It's possible we have a regression -- maybe try installing an older version of the gem or drop some of the hostname arguments to see if there's a conflict.

Other thing you can do is modify the code right before the clone task to print the specs, like [here](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L316).  `pp vmname; pp clone_spec` should tell you what's being sent to vSphere which might give us an idea of what the improper field is.

I've been a bit tied up at work lately. My intention is to play more with the Windows cloning as I know we have a few bugs here. Sorry I'm not more responsive :(

**Comment by paulherbosch** [comment]
hi,

I'm a colleage of Rob and believe I have fixed the issue.
I don't know how 'clean' this fix is, but it's good enough for our implementation.

In file `knife-vsphere-1.2.4/lib/chef/knife/vsphere_vm_clone.rb` around line number 559 I made this change:

```
          windows_hostname = RbVmomi::VIM.CustomizationFixedName(
            :name => hostname
          )

          user_data = RbVmomi::VIM.CustomizationUserData(
            fullName: cust_spec.identity.userData.fullName,
            orgName: cust_spec.identity.userData.orgName,
            productId: cust_spec.identity.userData.productId,
            # computerName: cust_spec.identity.userData.computerName
            computerName: windows_hostname
          )
```

**Comment by swalberg** [comment]
Hey Paul, thanks for that. I'll double check the API docs and make the changes in the gem, unless you wanted to submit a PR yourself. Otherwise I'll give credit in the changelog.

**Comment by paulherbosch** [comment]
Hey Sean,

feel free to make the changes yourself.
thx for the quick response.

gr, paul
