### ISSUE TITLE
Knife clone vm - Using random-vmname

### ISSUE THREAD

**Issue by barracksbuilder** [chef-partners/knife-vsphere#232]
I'm trying to use the knife clone vm with the --random-vmname flag and it always throws the:
FATAL: You must specify a virtual machine name OR use --random-vmname

I have tried several variations of my command:
knife vsphere vm clone test59 --random-vmname true --template UbuntuChris --cspec AutoSpec --cips X.X.X.X/24 --cgw X.X.X.X --datastore Pure-Test6 --bootstrap true --fqdn X.X.X.X --run-list "role[allservers], role[cmegateway]" --ssh-user haadmin --ssh-password "password"

knife vsphere vm clone --random-vmname true --template UbuntuChris --cspec AutoSpec --cips X.X.X.X/24 --cgw X.X.X.X --datastore Pure-Test6 --bootstrap true --fqdn X.X.X.X --run-list "role[allservers], role[cmegateway]" --ssh-user haadmin --ssh-password "password"

knife vsphere vm clone test59 --random-vmname --template UbuntuChris --cspec AutoSpec --cips X.X.X.X/24 --cgw X.X.X.X --datastore Pure-Test6 --bootstrap true --fqdn X.X.X.X --run-list "role[allservers], role[cmegateway]" --ssh-user haadmin --ssh-password "password"

knife vsphere vm clone --random-vmname --template UbuntuChris --cspec AutoSpec --cips X.X.X.X/24 --cgw X.X.X.X --datastore Pure-Test6 --bootstrap true --fqdn X.X.X.X --run-list "role[allservers], role[cmegateway]" --ssh-user haadmin --ssh-password "password"

If i run it without the --random-vmname flag and hard code a name it works fine:
knife vsphere vm clone test59 true --template UbuntuChris --cspec AutoSpec --cips X.X.X.X/24 --cgw X.X.X.X --datastore Pure-Test6 --bootstrap true --fqdn X.X.X.X --run-list "role[allservers], role[cmegateway]" --ssh-user haadmin --ssh-password "password"

A gem list knife-vsphere shows:
*** LOCAL GEMS ***

knife-vsphere (1.2.7)

**Comment by swalberg** [comment]
Hi, sorry you're getting this confusing error message. I'm pretty sure this is Chef's arg parsing haunting you -- both `--random-vmname` and `--bootstrap` are binary parameters and don't expect a `true` after them. So try:

```
knife vsphere vm clone --random-vmname true --template UbuntuChris --cspec AutoSpec --cips X.X.X.X/24 --cgw X.X.X.X --datastore Pure-Test6 --bootstrap --fqdn X.X.X.X --run-list "role[allservers], role[cmegateway]" --ssh-user haadmin --ssh-password "password"
```

I think what's happening is that the hostname is being picked as `true` and we only allow random OR static hostnames, not both.

**Comment by barracksbuilder** [comment]
Well that set me on the right path. Above didn't work and then I modified it one step further:
knife vsphere vm clone --random-vmname --template UbuntuChris --cspec AutoSpec --cips X.X.X.X/24 --cgw X.X.X.X --datastore Pure-Test6 --bootstrap --fqdn X.X.X.X --run-list "role[allservers], role[cmegateway]" --ssh-user haadmin --ssh-password "password"

And finally success! Moral of the story --random-vmname and --bootstrap does not take any parameters to work.

**Comment by swalberg** [comment]
Whoops I realized I gave you a bad command... Glad you figured it out!
