### ISSUE TITLE
knife vsphere clone doesn't exit 

### ISSUE THREAD

**Issue by brainstead** [chef-partners/knife-vsphere#234]
I am running the following command 
```
knife vsphere vm clone test --template "test-1" --cips foo --chostname bar --cdomain foo --cspec  bar -VVVV --datastore "foo" 
```

The vm is created successfully on vspehre, however the command hangs here and doesn't exit 
"Cloning template test to new VM test-1"
ruby version 2.1.0p0
knife-vsphere version - 1.2.7
chef-version - 12.7.2

**Comment by swalberg** [comment]
Hi, sorry to hear you're having this problem. What version of vSphere are you running? Is this a Windows or Linux VM?

**Comment by brainstead** [comment]
Thanks for responding. 
Linux VM - RHEL 6.6 
VSphere - 5.1

**Comment by brainstead** [comment]
My bad... the vsphere version is 5.5 and not 5.1 . Sorry for the error : (

**Comment by swalberg** [comment]
No problem. I'm at a loss to explain what's going on here. Maybe try it without `--cspec bar`?

Does the clone finish in the vSphere interface? Can you boot it? And just to be clear, you never see "Finished creating virtual machine"?

**Comment by brainstead** [comment]
Without the --cspec it errors out  wtih nicsettingsmismatch. The clone finishes on vsphere with all the customization. I am able to boot it also using vsphere show PowerOnVM_task . I just don't see the finished creating virtual machine. 
It hangs on "wait for task completion "

**Comment by brainstead** [comment]
My VM takes 90 minutes to clone BTW. I do not know if that is a factor for emitting an exit code .

**Comment by swalberg** [comment]
That seems like a lot. . I don't know if it is the cause of your problems though. Do you have a way of trying it with a faster clone?

**Comment by brainstead** [comment]
With faster clones, it exists cleanly.

**Comment by CEI-Rwitt** [comment]
Have you tried this?
--sysprep_timeout TIMEOUT - Wait TIMEOUT seconds for sysprep event before continuing with bootstrap

**Comment by brainstead** [comment]
Is there any resolution or mitigation steps or should this be marked as "can't be reproduced " ?

**Comment by swalberg** [comment]
Hi, sorry, I've been distracted.

Any chance there's a firewall in the middle that's dropping a tcp session? I'm not sure if keepalives are enabled on the connection. Can you run the command from a VM that's adjacent to the vsphere server?

**Comment by brainstead** [comment]
Here is the keepalive value on my system 
cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
My vm and vsphere are on the same subnet

**Comment by swalberg** [comment]
Are you running the `knife` command from a VM or from a local computer?

Firewall tables are typically under an hour. But I don't know for sure if keepalives are enabled for the connection. My Mac doesn't support `netstat -o`.

**Comment by brainstead** [comment]
Running it from   rhel 6.6 vm . netstat -e would give you timers .

**Comment by brainstead** [comment]
Is there a way to get  the progress bar for a vm creation ?

**Comment by brainstead** [comment]
I am marking this can't be reproduced or resolved.

**Comment by swalberg** [comment]
Hey, sorry I didn't get back to you. I don't know of a way to get the progress offhand. We mostly use the `wait_for_completion` command that blocks until the operation is complete.
