### ISSUE TITLE
Knife-vsphere fails to add second vmdk

### ISSUE THREAD

**Issue by TyMac** [chef-partners/knife-vsphere#235]
**When the following command to add a vmdk is run it fails:**

COMMAND=/usr/local/rvm/gems/ruby-2.0.0-p643/bin/knife vsphere vm vmdk add usa01dev-mesos-inf.amd01.net 200G --config conf/knife_vm_conf_usa01dev.rb

**Here is the command's error output:**

Datastore: USA007V292046_58 (498.93 GB(535718428672) / 1.95 TB)
Datastore: USA007V292046_77 (961.39 GB(1032289685504) / 1.95 TB)
Choosing: USA007V292046_58
Next vmdk name is => [USA007V292046_58] usa01dev-mesos-inf.amd01.net/usa01dev-mesos-inf.amd01.net_1.vmdk
Creating VMDK
Capacity: 200G GB
Disk: [USA007V292046_58] usa01dev-mesos-inf.amd01.net/usa01dev-mesos-inf.amd01.net_1.vmdk
ERROR: RbVmomi::Fault: FileNotFound: File [USA007V292046_58] usa01dev-mesos-inf.amd01.net/usa01dev-mesos-inf.amd01.net_1.vmdk was not found

This does not always happen however... this seems to happen randomly with CentOS 7 VMs coming from the same template.

**Comment by TyMac** [comment]
Here is version information:

/usr/local/rvm/gems/ruby-2.0.0-p643/bin/knife --version
Chef: 12.4.3

gem list | grep -i vsphere
knife-vsphere (1.2.4)

**Comment by jjasghar** [comment]
If this is still an issue, please reopen and post the error again. We have updated the gems significantly since Feb, so maybe it's fixed?
