### ISSUE TITLE
Any way of adding a VMDK when cloning a VM?

### ISSUE THREAD

**Issue by joldham1023** [chef-partners/knife-vsphere#237]
Looking to see if there is a way to add a vmdk when cloning a VM. Right now we have a nasty PowerCLI build script that we are trying to fully convert away from into using the knife vsphere commands. But the only thing preventing us is the ability to add additional vmdk's

**Comment by swalberg** [comment]
Hi, we have `knife vsphere vm vmdk add VMNAME DISK_GB` that'll let you add a new disk after the clone. If you need it done during the cloning then you can use the same code within a plugin (`--cplugin CUST_PLUGIN_PATH`, see the README for some examples)

**Comment by joldham1023** [comment]
I will take a look today. The only reason we are wanting it to be apart of the cloning action, is because we have a cspec that will online the disk/format it upon first boot. Thank you!

**Comment by swalberg** [comment]
Cool, let me know how it goes, please. I feel like the custom plugins are a powerful feature that's underdocumented.

**Comment by chef09210** [comment]
Hi what is the syntax for this when placed in the .rb file for a cplugin?

**Comment by swalberg** [comment]
Hi @chef09210, it has to be Ruby code, so you'd be modifying the spec that's passed to `customize_clone_spec`. I realize our documentation is pretty poor. The README has a stub you can start with:

```
class KnifeVspherePlugin
  def data=(cplugin_data)
    # Parse your cplugin_data from the format of your choosing.
  end

  # optional
  def customize_clone_spec(src_config, clone_spec)
    # Customize the clone spec as you see fit.
    return customized_clone_spec
  end

  # optional
  def reconfig_vm(target_vm)
    # Do anything you want in here with the cloned VM.
  end
end```
