### ISSUE TITLE
vsphere_datastore_maxfree regex option misleading

### ISSUE THREAD

**Issue by zachsmorgan** [chef-partners/knife-vsphere#239]
Due to circumstances beyond my control, I require the ability to search for datastores based on a true regular expression. Presently, the regex option is passed through Regexp.escape meaning that the regex option, instead of taking a regular expression, actually takes a string.

May I submit a pull request to that end, or was that on purpose?

**Comment by swalberg** [comment]
Hi Zach,

The current implementation doesn't make sense to me, I don't know the history, and I don't think that using a proper regex would cause people who rely on the current behaviour any problems, so by all means, please fix it for us :)

Thanks!
