### ISSUE TITLE
conditional check after get_vm should look for False instead of nil

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef-partners/knife-vsphere#242]
The get_vm method in [this code](https://github.com/chef-partners/knife-vsphere/blob/v1.2.8/lib/chef/knife/vsphere_vm_vmdk_add.rb#L43-L47) returns "False" instead of "nil" if no vms are found so the conditional check should be changed to the following code which matches what is done [here](https://github.com/chef-partners/knife-vsphere/blob/v1.2.8/lib/chef/knife/vsphere_vm_disk_list.rb#L19-L20).

```
    vm = get_vm(vmname)
    fatal_exit "Could not find #{vmname}" unless vm
```

**Comment by swalberg** [comment]
Thanks for letting us know. Did you want to make a pull request so you get credit for the fix?

**Comment by jeremiahsnapp** [comment]
No thanks. That's more responsibility than I have time for right now. I just wanted to pass on the info. Thanks for taking care of it though. :)
