### ISSUE TITLE
knife vsphere vm clone fails to execute

### ISSUE THREAD

**Issue by notouchie92** [chef-partners/knife-vsphere#243]
The following was done on a centos 6.7 machine. Out of the few commands i tried this one gave me an error.

Running "knife vspshere vm clone" Causes the following error:

/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- readline (LoadError)
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.3.0/gems/knife-windows-1.4.0/lib/chef/knife/winrm_base.rb:37:in `block (2 levels) in included'
        from /usr/local/lib/ruby/gems/2.3.0/gems/chef-12.8.1/lib/chef/knife.rb:232:in `block in load_deps'
        from /usr/local/lib/ruby/gems/2.3.0/gems/chef-12.8.1/lib/chef/knife.rb:231:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/chef-12.8.1/lib/chef/knife.rb:231:in `load_deps'
        from /usr/local/lib/ruby/gems/2.3.0/gems/chef-12.8.1/lib/chef/knife.rb:216:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/chef-12.8.1/lib/chef/application/knife.rb:148:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/chef-12.8.1/bin/knife:25:in `<top (required)>'
        from /usr/local/bin/knife:23:in `load'
        from /usr/local/bin/knife:23:in `<main>'

Here is my the info provided by "gem env"
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.3
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.3.0
     - /root/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /root/bin

**Comment by swalberg** [comment]
Hi, and thanks for the detailed bug report. I'm going to guess that 

```
ruby -rreadline -e 'puts 42'
```
fails for you, too?

I'm not sure why we require `readline` as I don't immediately see it being used in the source. But it's usually a part of the Ruby installation -- the `readline` module is part of the standard library.

Did you have the `readline-devel` package installed when you compiled Ruby? If not, install that and recompile Ruby.

Alternatively, try `gem install readline-rb` and see if that helps.

**Comment by notouchie92** [comment]
runnung `gem install rb-readline` fixed the issue! 

Thanks for the help!
