### ISSUE TITLE
Running commands against an unmanaged ESXi server (no vcenter)

### ISSUE THREAD

**Issue by mrjcleaver** [chef-partners/knife-vsphere#244]
Hi, 

Assuming https://github.com/chef-partners/knife-vsphere/issues/26 is true, to what - for ESXi - do I need to set: 
`
knife[:vsphere_dc] = "datacenter"
`

In https://discourse.chef.io/t/anyone-using-the-knife-vsphere-knife-plugin/2731/2 they use this literal.

Like https://www.reddit.com/r/chef_opscode/comments/2or5rj/knifevsphere_datacenter/ I've tried empty string etc to no avail.

I can't use the ESXi plugin as I don't have SSH access to the ESXi host.

Thanks,
   Martin.

**Comment by swalberg** [comment]
Hi, this plugin uses the vSphere APIs to manage a vSphere cluster, so I don't think it works with an unmanaged (by a vcenter server) ESXi server.

It's confusing because the hypervisor is ESXi but we actually talk to the management layer of vSphere. #26 seems to conflate the two.

**Comment by mrjcleaver** [comment]
ESXi standalone does have some sort of API that's used by ESXi Embedded Host Client. The UI is https://labs.vmware.com/flings/esxi-embedded-host-client

**Comment by swalberg** [comment]
Let me have a look at this tomorrow to see if they're the same API.

**Comment by mrjcleaver** [comment]
I'm told https://labs.vmware.com/flings/esxi-embedded-host-client#comment-562600 that Host Client is written against the public vSphere API. http://pubs.vmware.com/vsphere-60/topic/com.vmware.wssdk.apiref.doc/right-pane.html

Thanks :)

**Comment by swalberg** [comment]
OK, I see where you're going. I can't test this from here -- while I can connect to the API port the authentication is set up by my vcenter server.

So a few thoughts. First run the command with `-VV` and paste in the command and output (redact what you need to) so we can see where this thing chokes.

Next, install the `rvc` gem (`gem install rvc`), and then have a look at the object tree you get:

```
sean.walberg~/work/knife-vsphere (master)$ rvc
Host to connect to (user@host): myuser@myvcenterserver
password:
VMRC is not installed. You will be unable to view virtual machine consoles. Use the vmrc.install command to install it.
0 /
1 myvcenterserver/
> cd myvcenterserver/
/myvcenterserver> ls
0 MYDC (datacenter)
/myvcenterserver> cd MYDC/
ls/myvcenterserver/MYDC> ls
0 storage/
1 computers [host]/
2 networks [network]/
3 datastores [datastore]/
4 vms [vm]/
/myvcenterserver/MYDC>
```

So in my example, all my objects like vms and storage are under `MYDC`, which is why all the code makes reference to the datacenter. The objects you manage are like a big directory tree.

So see if you can determine what the "datacenter" is, that is, how do you find the `vms` folder?

I suspect it either won't have this abstraction, or it'll be some variant of the hostname.

**Comment by mrjcleaver** [comment]
Ah-ha:
`
password: 
password: 
Welcome to RVC. Try the 'help' command.
VMRC is not installed. You will be unable to view virtual machine consoles. Use the vmrc.install command to install it.
0 /
1 10.6.42.101/
> cd myvcenterserver
no matches for "myvcenterserver"
> ls
0 /
1 10.6.42.101/
> cd 10.6.42.101/
/10.6.42.101> ls
0 ha-datacenter (datacenter)
/10.6.42.101> cd ha-datacenter/
/10.6.42.101/ha-datacenter> ls
0 storage/
1 datastores [datastore]/
2 computers [host]/
3 networks [network]/
4 vms [vm]/
`

Looks like ha-datacenter is the answer!
I'll try it.

**Comment by mrjcleaver** [comment]
This also lines up with:

https://github.com/vmware/rvc/blob/acac697bd732fc8b9266aca9018ff844ecf62238/bin/rvc#L116

**Comment by swalberg** [comment]
Hm, I wouldn't have guessed a static value. If you get it to work, can you share a command or two here for future Google searches please?

**Comment by mrjcleaver** [comment]
I can confirm that after setting:
$ export VSPHERE_DC=ha-datacenter
...

And in ./.chef/knife.rb
`
if ENV['VSPHERE_HOST'] then
  knife[:vsphere_host] = ENV['VSPHERE_HOST'] 
  knife[:vsphere_user] = ENV['VSPHERE_USER']
  knife[:vsphere_pass] = ENV['VSPHERE_PASS']
  knife[:vsphere_dc] = ENV['VSPHERE_DC']    
  knife[:vsphere_insecure] = ENV['VSPHERE_INSECURE'] 
else
  puts "VSPHERE ENV vars not set in "+__FILE__+" ?"
end
`

Result:
`
$ knife vsphere vm list
 
Folder:
 
    VM Name: T3
 
        IP:
 
        RAM: 2048
 
        State: off
 
    VM Name: T4
 
        IP:
 
        RAM: 2048
 
        State: on
 
$ knife vsphere datastore list
 
Datastore: vmstorage (223.84 GB / 279.25 GB)
`

Sadly, the utility is limited to read-only operations due to license limitations:
`
$ knife vsphere vm clone T6 --template T3
 
Cloning template T3 to new VM T6
 
ERROR: RbVmomi::Fault: NotSupported: The operation is not supported on the object.
`

Nevertheless, thanks @swalberg for your insight and assistance!

**Comment by bby-bishopclark** [comment]
> Sadly, the utility is limited to read-only operations due to license limitations:
```
$ knife vsphere vm clone T6 --template T3

Cloning template T3 to new VM T6

ERROR: RbVmomi::Fault: NotSupported: The operation is not supported on the object.
```

That's not 100% true.  *cloning* isn't possible with a free-license setup, and probably also no good as unmanaged (no vSphere) ESXi as well.  Other operations may or may not be possible; but cloning is definitely specifically denied. 

Try other things, early and often.  I've never tried the knife-vSphere with my Freebie ESXi host; just with the managed ones;  If I could configure my standard vSwitches etc on that without having to enhance the josenk knife-esxi add-on, why, I'd save *days* of really bad coding and 30 lines of passable submission to turn in.
