### ISSUE TITLE
Unable to activate em-winrm-0.7.0, because winrm-1.7.3 conflicts with winrm

### ISSUE THREAD

**Issue by gitdave225** [chef-partners/knife-vsphere#247]
Getting this error trying to bootstrap a windows VM. I tried doing this with chefdk 0.10.0 and also 0.12.0. Looking at em-winrm in gems and see that this has been deprecated and is part of knife-windows. Has anyone seen this before?

Here is the error:
C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate em-winrm-0.7.0, because winrm-1.7.3 conflicts with winrm (~> 1.3.0) (Gem::ConflictError)

I am using:
- chefdk 0.12.0
- knife-windows (1.4.0, 1.1.1, 1.0.0, 1.0.0.rc.2, 0.8.6)
- knife-vsphere (1.2.8)
- em-winrm (0.7.0)
- winrm (1.7.3, 1.7.2)
- winrm-fs (0.3.2)
- winrm-s (0.3.1)
- winrm-transport (1.0.3)

**Comment by swalberg** [comment]
Do you get a longer backtrace, showing where the gem was required? We manually require it in `lib//chef/knife/vsphere_vm_clone.rb:811`, did you want to try commenting it out to see if you get past this?

The dependency in the gemspec is `s.add_dependency('knife-windows', ['>= 0.6.0'])`, so we'll take the gem before and after `em-winrm` was merged in.

**Comment by gitdave225** [comment]
Commented it out and I get further along. If that gem is already deprecated and replaced by knife-windows, maybe it should be removed as a dependency?

**Comment by swalberg** [comment]
Yup I'll look at bumping knife-windows to something recent and removing any references to this gem. 

Sean

**Comment by gitdave225** [comment]
Thanks! I'll close this issue then.

**Comment by swalberg** [comment]
See #251

**Comment by swalberg** [comment]
Fixed in v1.2.9! Thanks for reporting the problem.
