### ISSUE TITLE
Modify VM settings?

### ISSUE THREAD

**Issue by kenny-evitt** [chef-partners/knife-vsphere#249]
This seems like a generalization of #218.

Specifically, I want to change the network that a VM network adapter uses. Based on the existing README, there doesn't seem to be any way to do this.

However, there are several sub-commands that seem pertinent:
1. `vm config VNAME PROPERTY VALUE`
2. `vm query VNAME QUERY`
3. `vm show VNAME QUERY`

The description of the first command tho states:

> See "http://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.ConfigSpec.html" for allowed ATTRIBUTE values (any property of type xs:string is supported).

The above seems to indicate that _only_ the properties of type `xs:string` are supported – is that right?

I am very much interested in this and I'd be happy to work on adding support myself.

For the second and third commands above both descriptions state:

> See "http://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.VirtualMachine.html" for allowed QUERY values.

I can't however figure out what on that linked page relates to "allowed QUERY values" – if I pass an empty string I get the following error:

> `knife : FATAL: You must specify a QUERY value (e.g. guest.ipAddress or network[0].name)`

**Comment by kenny-evitt** [comment]
After playing with `vm show ...` and `vm query ...` (which seems deprecated in favor of the former), I think I've figured out that the `QUERY` values should be a (single) name of one of the properties listed on the linked page.

For example, if I run `knife vsphere vm show MYVMNAME "config"`, I get a result like this:

`#<RbVmomi::VIM::VirtualMachineConfigInfo:0x6a01c88>`

**Comment by kenny-evitt** [comment]
Perhaps naively, I'd think we could add general support for working with the underlying RbVmomi objects by converting from and to text via a syntax like Ruby hashes (or JSON objects).

If run `knife vsphere vm show MYVMNAME "network"` I get something like this:

`Network("network-401")`

but `knife vsphere vm show MYVMNAME "network.name"` (i.e. trying to output the `name` property of the network object) just fails:

`knife : FATAL: "network.name" not recognized.`

But now, finally, the message I got when I passed an empty `QUERY` value makes sense:

> `knife : FATAL: You must specify a QUERY value (e.g. guest.ipAddress or network[0].name)`

So, running `knife vsphere vm show MYVMNAME "network[0].name"` results in:

`My network's name`

as I hoped and expected.

**Comment by swalberg** [comment]
Hi, yes, you've found some of the gory internals. The `show` command is pretty tightly coupled with the vSphere objects.

Networks are a bit tricky if I remember correctly because you have to look up certain IDs and use those to modify the VM instead of just a name. But it's been a while since I've tried. I have some half written code that predates me finding this project but it starts with a warning not to use it because it doesn't work :)

Would be very happy to see improvements to this.

**Comment by kenny-evitt** [comment]
@swalberg Thanks! Any advice on where I should start? I'm not familiar with RbVmomi – should I start looking at it first?

**Comment by swalberg** [comment]
Are you trying to address the `knife vsphere vm show MYVMNAME "network"` shows `Network("network-401")` problem? Or using other data types in the `knife vsphere vm config`? The naming is probably part of RbVmomi, what we send to the API is in this gem.

**Comment by kenny-evitt** [comment]
@swalberg Sorry for not being clear.

I'm fine with the existing behavior with respect to `knife vsphere vm show MYVMNAME "network"` – I just need to pass e.g. `"network[0].name"` or `"network.count"` to query specific info. I don't think coupling the `QUERY` values to the vSphere API is particularly problematic.

I'd like to address using the non-string data types in the `knife vsphere vm config` sub-command. Looking at the code for that sub-command seems like a logical place to start.

**Comment by swalberg** [comment]
Ah, got it. So the [existing code](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_config.rb#L44-L45) is taking a bit of a shortcut by sending a key-value pair. To handle anything more complicated you'd need to pass a more complicated data structure, probably by using RbVmobi.

Looking at the API for [VirtualMachineConfigSpec](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.ConfigSpec.html), if you wanted to change boot options, you'd be passing a `VirtualMachineBootOptions` structure, for example 

```Ruby
properties = VirtualMachineBootOptions.new(bootDelay: 5000)
vm.ReconfigVM_Task(spec: RbVmomi::VIM.VirtualMachineConfigSpec(properties)).wait_for_completion
```

**Comment by kenny-evitt** [comment]
@swalberg Thanks; that looks like enough to get started.

**Comment by kenny-evitt** [comment]
@swalberg After working with the `vm show` sub-command some more, I think it'd be a good idea to pick a standard or default format for displaying the results of a query (i.e. serialize the query result object). Ideally, that format could also be used to pass an argument or arguments (either directly as text or in the form of a path to a text file containing the formatted object info) to the `vm config` sub-command.

As an example, querying all of the devices of a VM is tedious given that there's currently no support for multiple queries in a single command. And, even if there were, it'd be nice to just output the entire array of device objects with a single query (particularly given that it can be fairly slow to run a single query – or at least it is for me).

The two main candidates I found, based on a cursory Google search, are YAML and JSON (given that we'd want to be able to manually edit it).

Preferences? Thoughts?

**Comment by kenny-evitt** [comment]
@swalberg Welp – good news is that formatting a query result is already supported, given the magic of Ruby. I just ran `knife vsphere vm show "MY-VM-NAME" "config.hardware.device.to_yaml"` and got a big ol' heap of YAML with all of the device info!

**Comment by swalberg** [comment]
So there's already a `format` option to knife that we largely ignore. What about using that to print out the output?

```
if format_is_json
  puts result.to_json
 elsif format_is_yaml
  puts result.to_yaml
else
   puts result
 end
```

**Comment by kenny-evitt** [comment]
@swalberg That would work too.

**Comment by swalberg** [comment]
BTW I just tried out that `config.hardware.device.to_yaml` thing, that's so cool! I could see using this with `json` and `jq` in some scripts! Thanks for pointing it out!

**Comment by kenny-evitt** [comment]
@swalberg Glad you like it as much as I do :smile:
