### ISSUE TITLE
`vm snapshot ... --create ...` fails with "missing required parameter memory" error

### ISSUE THREAD

**Issue by kenny-evitt** [chef-partners/knife-vsphere#252]
I ran:

`knife vsphere vm snapshot "MY-VM-NAME" --create "Snapshot 0"`

The result:

`knife : ERROR: RuntimeError: missing required parameter memory`

In my case, I *don't* want to include the memory state in the snapshot, but there's no 'no-memory' option listed in the sub-sub-command help.

[The relevant code](https://github.com/chef-partners/knife-vsphere/blob/72d69f68dd01f7c45646944ef1c58cf0d0966f25/lib/chef/knife/vsphere_vm_snapshot.rb#L94-L97) looks good. But [I can't find CreateSnapshot_Task in the RbVmomi code](https://github.com/rlane/rbvmomi/search?utf8=%E2%9C%93&q=CreateSnapshot_Task&type=Code) so I'm guessing that comes from the vSphere API directly.

I'm running vCenter Server 5.5 – maybe the API changed since 5.0?

**Comment by kenny-evitt** [comment]
If I include `--dump-memory`, I get a new complaint:

`knife : ERROR: RuntimeError: missing required parameter quiesce`

Aha – those options expect (and require) a boolean value; this worked:

`knife vsphere vm snapshot "MY-VM-NAME" --create --dump-memory false --quiesce false "Snapshot 0"`

Could we change the help text for those options to something like:

```
        --dump-memory BOOL           Dump the memory in the snapshot
...
        --quiesce BOOL               Quiesce the VM prior to snapshotting
```

**Comment by swalberg** [comment]
Hey thanks for pointing this out. I thought the `default: false` at the top of the file should have taken care of that. I'd rather have a sensible default than force people to add long opts. Let me have a look!

**Comment by swalberg** [comment]
Oh, Ruby, what a wonderful language you are. This code is fine, it's the `get_config` in the base class that has a problem because a falsey value is being counted as a missing value.

PR coming.

**Comment by swalberg** [comment]
See #253

**Comment by kenny-evitt** [comment]
@swalberg Thanks. I had actually started looking at the *slop* options library, trying to figure out what was going on, but I didn't spot the falsey thing.

Interestingly, my command that 'worked', i.e. passing `--dump-memory false --quiesce false`, was probably *not* working as expected. I'm guessing the command was receiving string arguments (`"false"`) for both options, i.e. both options were truthy.

**Comment by kenny-evitt** [comment]
@swalberg Should the changes in #253 be included in version 1.2.9 of the gem? I installed that version (and removed the previous version too), but I'm still getting the same error.

**Comment by swalberg** [comment]
Sorry, no, 1.2.9 was released before this was merged. I just cut v1.2.10, you should see it soon.

**Comment by kenny-evitt** [comment]
@swalberg Ahh; thanks.

**Comment by kenny-evitt** [comment]
@swalberg I ran it with `bundle exec knife vsphere ...` and it worked.
