### ISSUE TITLE
Power on VMs without cloning

### ISSUE THREAD

**Issue by aroonseena** [chef-partners/knife-vsphere#255]
I apologize if I have raised the below scenario as an issue. I can't find another way to contact the authors

A full disclaimer here of me still  being a newbie to the Ruby/Chef world

We have a pre built pool of VDI(Linked Clones)/VMs which have been already bootstrapped and powered off to conserve resources. 

Apart from the clone/snapshot subcommand is there another command by providing an IP or hostname that can just power on the machines. I couldn't find any subcommand to only power on the VMs/VDIs.

Thanks in advance!

**Comment by swalberg** [comment]
Hi, issues are the perfect way to get help. Others might have the same question later and this'll show up when they search.

Are you perhaps looking for the confusingly named [knife vsphere vm state](https://github.com/chef-partners/knife-vsphere#knife-vsphere-vm-state--s-state-state-state--w-port-wait-port-port--g-shutdown--r-recursive)?

`knife vsphere vm state -s on -r myserver` should turn on `myserver`.

**Comment by swalberg** [comment]
p.s. Welcome to the Ruby/Chef world!

**Comment by aroonseena** [comment]
Absolutely, that command worked to power on a VDI. Sorry I overlooked that command since state was involved.

Thanks again for the help. I will post here if I run into more issues.

**Comment by swalberg** [comment]
Glad this was a quick one to solve. Discovery is definitely a problem here. 0c0471a adds some more wording to make this one possibly easier to find.
