### ISSUE TITLE
Implementing the --msi-file option

### ISSUE THREAD

**Issue by gitdave225** [chef-partners/knife-vsphere#257]
Not much an issue but one of the things that I liked about knife-windows was the implementation of the --msi-file option. This will allow you to specify where to download the chef client. Any chance this can be added to knife-vsphere?

**Comment by swalberg** [comment]
Hi, yes, I'm sure it could be added. At some point in the code we just hand over control to knife-windows.

Are you downloading it to subsequently run it for bootstrapping? Or do you need to download it for other purposes? I'm not positive, but I thought there are already features to bootstrap a Windows node in the existing code. (I don't run any Windows machines so I don't know first hand)

**Comment by gitdave225** [comment]
Yeah my company isolates our windows and linux servers from the network so the best way for bootstrapping them is to specify where the installer file is located locally. Yes the code is there to bootstrap a windows server but it relies on being able to pull the installer from the net.

**Comment by swalberg** [comment]
So just for clarity, you'd be passing it a UNC path? Or a local path with the installer being part of the template?

**Comment by gitdave225** [comment]
I was passing the URL ie http://server/chef-client-latest.msi. The UNC path was not working the last time I tried it.

**Comment by swalberg** [comment]
Aha, got it, thanks.

**Comment by joldham1023** [comment]
Have you thought about putting the chef-client msi into the vmware template? The way the company I work for achieved this was, bootstrapping the template into our chef org / removed the client.pem file and the reference to the hostname in the client.rb file. For Windows: We then put a powershell script that basically adds the hostname to the client.rb then runs chef-client, then runs knife node runs_list add/set nodename "recipe[]" and we do something similar for our linux VMs.

**Comment by gitdave225** [comment]
Yeah that's another way to do it but I was hoping to stream line this with knife-vsphere. Pulling the file from a local web server is possible with knife-windows and since knife-vsphere just passes along the boot strap options, I don't see why this could not be implemented here.

**Comment by gitdave225** [comment]
The --msi-url functionality being implemented in the next release. Thanks again for all the help folks.

**Comment by swalberg** [comment]
I just released 1.2.15 (and then shortly after, 1.2.16) that implements this.
