### ISSUE TITLE
Kerberos_service

### ISSUE THREAD

**Issue by kev111** [chef-partners/knife-vsphere#261]
What is this value? The kdc? Is there a working example of kerberos with active directory?

**Comment by swalberg** [comment]
Hi @kev111, I'm not sure where we use `kerberos_service`. Can you give me a link to what you're seeing, please? If it's something that goes in the Windows customization spec, you can configure that in vsphere and then use `--cspec xxx` when cloning.

**Comment by kev111** [comment]
This is embarrassing, it's in knife-windows. Sorry, it gets confusing.
