### ISSUE TITLE
Is it still possible to specify the MAC address that a new VM must have on the primary interface?

### ISSUE THREAD

**Issue by kozmikyak** [chef-partners/knife-vsphere#265]
In an older version of knife-vsphere, one could provide the --cmac CUST_MAC_ADDR option to set the MAC address on the primary interface.

My organization is stuck at that older version because, while I can convert most command line options to the latest version's options, our infrastructure currently relies on DHCP based on hardware address to set the IP.  Since my department is not in charge of the DHCP servers, we have to work with what we're provided.

I'm a bit out of date on my knowledge of current best practice for doing this kind of thing--is there an architectural reason this option was removed?  What is the current best practice in situations where an organization wants to control IP addresses with DHCP for IPv4 addresses?

**Comment by kozmikyak** [comment]
Looks like the proper place to allow setting of a MAC address per network card would be somewhere between lines 527 and 545.  I could try my hand at a pull request but want to understand first what the reasoning was. 

I can see that once one allows multiple cards/vlans that it's unwieldy to specify them especially if you can set the IPs directly per card, and that may have figured into the reasoning.

**Comment by swalberg** [comment]
Hi, which version of the gem had that? I'm not able to find where we've supported it in the past.

I don't know why the feature would have been removed which is why I'm hoping to find the commit message to get some context. Barring any solid reasoning from that, I'd be happy seeing it supported.

What you're describing is certainly a bit unorthodox, but given your circumstances, seems logical. I wouldn't want this gem to enforce any kind of workflow on people, so setting the MAC is OK in my books.

**Comment by kozmikyak** [comment]
It's in 1.0.17, which is not in this repo.  Perhaps a previous maintainer before it was forked/taken over?  The code layout/structure and key comments/lines look very similar so I'm sure there is some kind of family relation between the code in this repo and the code I'm looking at.

Maybe that's a local addition someone did, too, I'm not quite sure, which is why I'm poking around.

The gemspec looks similar as well, though obviously yours is updated from what I have.

If we need to communicate out-of-band regarding access to the code that I have, I'd be willing, though of course I'm willing to do a pull request and the actual lifting on the coding.  I see that it should be relatively easy to add a command line option with a comma-separated list of MAC addresses, which would be applied to the adapters in order along with the proper virtual switch/VLAN stuff.

The current version of the code is MUCH better formatted/laid out than what I have, though the general thrust is the same.  It's a joy to read, actually, so good work to the contributors.

**Comment by swalberg** [comment]
If you want to write the code, please be my guest and let me know how I can help. Your approach about a comma separated list is ideal -- maybe consider a keyword like `auto` in case someone wants to only configure 1 nic out of multiple?

**Comment by kozmikyak** [comment]
The "auto" option sounds good to me.  I'll get working in a forked repo and will send a pull request when I'm closer to finished.

**Comment by kozmikyak** [comment]
I have some code ready to pull-request here.  This would be my first public GitHub pull request, is it okay to do these requests against "master" branch or is there some other way I should provide it for comment first?  I have a fork of this repo in my personal GitHub space, under the branch 'local-dev', if anyone wants to inspect it first.

Code working in our env but I have limited ability to test it on differing Vsphere environments, to ensure that it doesn't break existing things.  I designed it to not break existing usage but one never knows . . .

**Comment by swalberg** [comment]
Yea, the best way for you to do this is to develop in a branch and submit a pull request against this repo's master. We'll chat about the code within the PR, make any needed changes as extra commits in your branch, then it gets merged and I take care of bumping the version, adding release notes, and releasing.

One thing that will happen once you create the PR is that a bot (Hound) will run through the code and make comments about style. This helps new people come on board by giving consistent style and practices throughout the code. If it makes comments, just fix them within your branch and the PR will be updated automagically when you push the commit up.

Thanks, and looking forward to seeing the code!

**Comment by kozmikyak** [comment]
I've done pull requests against the University of Minnesota's GitHub instance, so the process itself is familiar, just wanted to be sure about the branching.  I'll do the pull request this morning.

**Comment by kozmikyak** [comment]
Pull request made.

**Comment by swalberg** [comment]
Oh! You made it the other day and I missed it. Will dig in, thanks!

**Comment by swalberg** [comment]
This is all done and in the latest versions... Closing, with my thanks for your work on it!
