### ISSUE TITLE
RbVmomi::Fault: machine[testevm] (vsphere::provision line 56) had an error: RbVmomi::Fault:  InvalidArgument: A specified parameter was not correct. 

### ISSUE THREAD

**Issue by cmesquita** [chef-partners/knife-vsphere#266]
Hi All,

Does anyone know What can kind of problem could be the following ? It´been happing intermittently , It always happen at the second time I tried to provision a new VM  template based.

   RbVmomi::Fault
   --------------
   InvalidArgument: A specified parameter was not correct.
   LicenseFilePrintData

The recipe being used:

ENV['http_proxy'] = 'http://172.22.8.18:3128'

with_chef_server "https://palencia/organizations/ACME",
  :client_name => Chef::Config[:node_name],
  :signing_key_filename => Chef::Config[:client_key],
  :machine => 'testevm' 

    chef_gem 'chef-provisioning-vsphere' do
      action :install
      compile_time true
    end

    require 'chef/provisioning/vsphere_driver'

    with_vsphere_driver host: '172.22.10.112',
      insecure: true,
      user:     'ilegra_fribeiro@ACME',
      password: '@ACME123'

    machine_options = {
	:bootstrap_options => {
	:start_timeout => 60,
	:create_timeout => 60,
	:name => 	'testevm',
        :num_cpus =>        '2',
        :memory_mb =>       '4096',
	:datacenter =>		'ALPHAVILLE',
	:resource_pool =>	'CORP-DEVOPS',
        :datastore =>          'VNX-DT-07',
        :template_name =>      'Template_sql2003_devops',
        :customization_spec => {
          :ipsettings => {
            :ip => '172.22.14.12',
            :subnetMask => '255.255.255.0',
            :gateway => ['172.22.14.1'],
            :dnsServerList => ['8.8.8.8','8.8.4.4'] 
          },
          :domain => 'local',
          :domainAdmin => 'Administrator',
          :domainAdminPassword => '@ACME123',
          :org_name => 'ACME',
          :product_id => 'MT3V3-HVKB8-GKYJJ-YVVJJ-922M6',
          :win_time_zone => 4
        },
        :ssh => {
          :user => 'Administrator',
          :password => '@ACME123',
          :paranoid => false
        },
        :convergence_options => {
	     :ssl_verify_mode => :verify_none
	    }
      }
    }

	machine 'testevm' do
		machine_options machine_options
		action :ready
		retries 0
  		retry_delay 6
	end

thanks in advance 

Cesar

**Comment by swalberg** [comment]
Hi Cesar,

I think you're looking for [this gem](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere). This gem, `knife-vsphere`, is similarly named but only works for ad-hoc commands.

**Comment by cmesquita** [comment]
Hi swalberg,

Thanks for your reply. I just raised an issue in the following link

https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/issues/80
