### ISSUE TITLE
Kitchen Driver?

### ISSUE THREAD

**Issue by kbrowns** [chef-partners/knife-vsphere#267]
We're currently using knife-vsphere and doing so quiet happily.  There has been some interest in [Chef Provisioning](https://github.com/chef/chef-provisioning) and it's [VSphere implementation](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere).  Provisioning machines from chef-client feels very odd to me - knife seems like a much more suitable approach to me.  I believe the primary reason for a potential switching is because of [Chef Provisioning VSphere's Kitchen Driver](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/blob/master/lib/kitchen/driver/vsphere.rb).  This is indeed compelling as running kitchen tests in our CI pipeline is our next goal.  We would like to run these in vsphere for two reasons 1) we want to practice (test) like we play (production); and 2) our CI pipeline runs on entirely virtualized machines where no local hypervisor is available.

Has there been any thought to creating a kitchen driver as part of this project?  Would this be a desirable contribution?  I've been struggling to find much doc on how to actually implement a kitchen driver, but could probably dissect how this works by looking at the existing drivers.

**Comment by swalberg** [comment]
Hi Kelly,

I'm currently on vacation with limited internet access but did want to reply so you know this issue was received. 

I thought there was already a kitchen vsphere adapter as a separate project but will do some digging when I get back next week to understand what's going on here.

Sean

**Comment by jjasghar** [comment]
I've flirted with the idea to pull: https://github.com/CenturyLinkCloud/chef-provisioning-vsphere#kitchen-driver into it's own project.

But i think this answers your question, please reopen if you have any more thoughts.
