### ISSUE TITLE
Password with quotes causes config file syntax error

### ISSUE THREAD

**Issue by bhaliti** [chef-partners/knife-vsphere#268]
Hi,

I am very new to chef and was wondering if someone can help me out

i ran gem install knife-vsphere on my workstation
configured the knife.rb file to point to my vsphere host, user, pass, dc but i am getting an error

PS 
```
C:\opscode\learn-chef> knife vsphere vm list
ERROR: CONFIGURATION ERROR:You have invalid ruby syntax in your config file C:/opscode/learn-chef/.chef/knife.rb

SyntaxError: C:/opscode/learn-chef/.chef/knife.rb:13: syntax error, unexpected $undefined, expecting end-of-input
knife[:vsphere_pass] ="my password"
```

here is what my knife.rb file looks like

```
# See https://docs.getchef.com/config_rb_knife.html for more information on knife configuration options

current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "admin"
client_key               "#{current_dir}/admin.pem"
chef_server_url          "https://chef_server/organizations/short_name"
cookbook_path            ["#{current_dir}/../cookbooks"]
# knife-vsphere plugin
knife[:vsphere_host] = "vcenter_host"
knife[:vsphere_user] = "administrator"
knife[:vsphere_pass] = "my_password"
knife[:vsphere_dc] = "my_datacenter"
```

**Comment by swalberg** [comment]
Hi, I'm not near a computer until Sunday so can't check my file to see what I have. But double check that you are using double quotes and not some kind of smart quotes from a copy-paste. Also check line 12 for an unterminated or mismatched quote. 

Sean

**Comment by bhaliti** [comment]
I figured out that my password had quotes and double quotes, ruby does not like that. so I had to use %Q(password_here) 

now I can't login to vcenter with an admin account. incorrect username or pass - on to the next issue


thanks

**Comment by swalberg** [comment]
Updated description and formatting -- closing.
