### ISSUE TITLE
RbVmomi::Fault: InvalidLogin: Cannot complete login due to an incorrect user name or password

### ISSUE THREAD

**Issue by bhaliti** [chef-partners/knife-vsphere#269]
I have an admin account that I am trying to use to login to vcenter. I can telnet, 443, 80, resolve FQDN
 I guess I need to look into ports???
my chefdk (workstation), my chef server, and vcenter are on the same subnet there are no firewall rules on the workstation or the chef server, OS firewall on vcenter is disabled, it sits behind ASA 

I am not sure what is going on right now. 

I would appreciate some assistance

thanks

**Comment by swalberg** [comment]
Hi if you're getting that error then you are connecting to vcenter. Are there any special characters in your password? Run the command with -VV and make sure the password looks ok.

Sean

**Comment by bhaliti** [comment]
I have removed special characters from password and tried -VV and here is what I am seeing:

[root@DP-CHEFDK01 .chef]# knife vsphere vm list -VV
INFO: Using configuration from /root/chef-repo/.chef/knife.rb
DEBUG: value for config item vsphere_host: my_vcenter
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: chefservice
DEBUG: value for config item vsphere_pass: my_password
DEBUG: value for config item vsphere_pass: my_password
DEBUG: value for config item vsphere_pass: my_password
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connecti                                                                                                                                                             on.rb:61:in `parse_response': InvalidLogin: Cannot complete login due to an inco                                                                                                                                                             rrect user name or password. (RbVmomi::Fault)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbv                                                                                                                                                             momi/connection.rb:90:in `call'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbv                                                                                                                                                             momi/basic_types.rb:205:in `_call'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbv                                                                                                                                                             momi/basic_types.rb:74:in `block (2 levels) in init'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbv                                                                                                                                                             momi/vim.rb:38:in `block in connect'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbv                                                                                                                                                             momi/vim.rb:36:in `tap'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbv                                                                                                                                                             momi/vim.rb:36:in `connect'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.11/lib/chef/kni                                                                                                                                                             fe/base_vsphere_command.rb:113:in `vim_connection'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.11/lib/chef/kni                                                                                                                                                             fe/vsphere_vm_list.rb:64:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/che                                                                                                                                                             f/knife.rb:421:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/che                                                                                                                                                             f/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/che                                                                                                                                                             f/knife.rb:420:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/che                                                                                                                                                             f/knife.rb:219:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/che                                                                                                                                                             f/application/knife.rb:148:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/bin/kni                                                                                                                                                             fe:25:in `<top (required)>'
        from /opt/chefdk/bin/knife:52:in `load'
        from /opt/chefdk/bin/knife:52:in `<main>'

**Comment by bhaliti** [comment]
username@domainname.com did the trick. 
it's funny because it says no vms??? I have plenty of vms. does chef log this anywhere, where is a good place to see what these knife commands are doing from a log perspective?

thanks

**Comment by swalberg** [comment]
Try the -r option for a recursive search... It only looks in the top level by default

**Comment by bhaliti** [comment]
yup. figured it out. thanks. I'll close the ticket.
