### ISSUE TITLE
ERROR: RbVmomi::Fault: NicSettingMismatch: fault.NicSettingMismatch.summary

### ISSUE THREAD

**Issue by bhaliti** [chef-partners/knife-vsphere#271]
Hi,

I am having issues with this now.  knife vsphere vlan list shows me all the vlans, its a cluster env. and they are setup the same, however we are not using distributed switch, 

would appreciate some help.

thanks

**Comment by swalberg** [comment]
Is this during a clone operation? Pretty sure we assume a distributed switch in most places. Can you paste the command you're trying to run, please?

**Comment by bhaliti** [comment]
knife vsphere vm clone PS-CHEFTEST01 –-template Chef-Windows-Template \ --disable-customization \ --cspec DS-APP \ --datastore DS-VM-VOL4 \ --resource-pool DALLAS_CLOUD \ --cvlan SB-APP01, \ --cips 10.117.202.150/24, \ --cgw 10.117.202.1, \ --start true --bootstrap true \ --fqdn PS-CHEFTEST01.sandbox.olstest.com \ --ssh-user Adminstrator \ --ssh-password mypassword \ --node-name PS-CHEFTEST01 -VV

**Comment by jjasghar** [comment]
Please reopen if you are still having issues so we can continue debugging :)
