### ISSUE TITLE
Bootstraping vmware windows2012r2 template

### ISSUE THREAD

**Issue by bhaliti** [chef-partners/knife-vsphere#272]
Hi,

I need some help in figuring out a way to bootstrap nodes. None of the servers in our environment will have outbound access, no proxy. How do I install chef-client on the nodes via workstation for example. 

Can I install the client on the template and change some file ??? to realize that client is on there and point to it instead of ussuing that wget:* because it will miserably fail due to no egress. 

Please note that I am very knew and might not get low level terms, please be specific. 

What I am trying to do is, use my windows template to build servers:
change vlan
change name
join to domain
and eventually install java or as needed 

thanks 

here is an error I received even after I manually installed client 
 C:\Users\Administrator>goto install
10.117.100.245 Checking for existing downloaded package at "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
10.117.100.245 No existing downloaded packages to delete.
10.117.100.245 Attempting to download client package using PowerShell if available...
10.117.100.245 powershell.exe -ExecutionPolicy Unrestricted -NoProfile -NonInteractive -File  C:\chef\wget.ps1 "https://www.chef.io/chef/download?p=windows&pv=2012&m=x86_64&DownloadContext=PowerShell&v=12" "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
10.117.100.245 Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to
10.117.100.245 the remote server"
10.117.100.245 At C:\chef\wget.ps1:14 char:1
10.117.100.245 + $webClient.DownloadFile($remoteUrl, $localPath);
10.117.100.245 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10.117.100.245     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
10.117.100.245     + FullyQualifiedErrorId : WebException
10.117.100.245
10.117.100.245 Warning: Failed to download "https://www.chef.io/chef/download?p=windows&pv=2012&m=x86_64&DownloadContext=PowerShell&v=12" to "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
10.117.100.245 Failed download: download completed, but downloaded file not found
10.117.100.245 Warning: Retrying download with cscript ...
10.117.100.245 C:\chef\wget.vbs(47, 1) msxml3.dll: A connection with the server could not be established
10.117.100.245
10.117.100.245
10.117.100.245 Failed download: download completed, but downloaded file not found
10.117.100.245 Exiting without bootstrapping due to download failure.
ERROR: Failed to execute command on 10.117.100.245 return code 1

**Comment by gitdave225** [comment]
If you are using VMware, you can specify customizations for changing the name and adding to the domain. You can use powercli to modify the network your VM is using.
If you are limited to just using the knife-vsphere gem, you can specify the new hostname using --chostname and --cdomain for the name. As for the chef client, I am in the same boat as you. None of my servers can get to the internet. I was hoping that the --msi_url option using the knife-windows gem would get added to this gem. Not sure how I can do that. Anyway, I ended ensuring the chef client is already installed on the template and using VMware customizations to build my servers. Currently, I am specifying a default cookbook for each server that gets created. Total build time is about 25 minutes.

**Comment by bhaliti** [comment]
thank you for your reply.

"Anyway, I ended ensuring the chef client is already installed on the template"

where did you place the client??
I see the template under nodes in chef manage but it says never checked in

**Comment by swalberg** [comment]
Thanks for the comment @gitdave225. The `--distro` option might help here, allowing you to specify a template that uses a locally stored agent rather than omnitruck.

**Comment by gitdave225** [comment]
You can grab the client from chef.io downloads. Then install the client on your template. You will have to kick off the chef-client after deployment.

**Comment by bhaliti** [comment]
lol. please be more specific.  use the --distro when knife vsphere  correct?

I have installed the chef-client package but I don't see it under services or under task manager as running. I even went into opscode> chef> bin and ran chef-client and complained about there not being a client.rb file. does that mean I have to create that on each new node to point to chef server???

**Comment by swalberg** [comment]
It's probably a runnable binary of sorts. Is there a `chef-client` anywhere?

Normally at this point you either go to a workstation and run `[knife bootstrap](https://learn.chef.io/manage-a-node/windows/bootstrap-your-node/)`, which should detect that chef is already installed, or you [bootstrap it from the server](http://www.kickflop.net/blog/2013/03/13/bootstrapping-new-chef-nodes-without-knife-bootstrap/).

**Comment by bhaliti** [comment]
I tried running with that --distro and because I am not using a distributed switch i am getting /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Task.rb:11:in `wait_f                                        or_completion': NicSettingMismatch: fault.NicSettingMismatch.summary (RbVmomi::Fault)

is this also an issue with chef-provisioning-vsphere do you know?

**Comment by swalberg** [comment]
@gitdave225 the `--bootstrap-msi-url` will be available in the next release, which is this week.
