### ISSUE TITLE
`mac_list` undefined unless `--cmacs` is set

### ISSUE THREAD

**Issue by raghav8888** [chef-partners/knife-vsphere#277]
Hi. I'm getting the error in subject when I run the command below.

```
knife vsphere vm clone testvm -f templates --template templatename --vsuser username --vspass password --resource-pool rpname --datastorecluster datstoreclusname --dest-folder foldername --vshost hostip --vsdc datacenter --cspec cspecname --cips ipaddress -VV

DEBUG: value for config item chef_node_name:
DEBUG: value for config item vsphere_host: xxxx
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: xxxx
DEBUG: value for config item vsphere_pass: xxxx
DEBUG: value for config item vsphere_pass: xxxx
DEBUG: value for config item vsphere_pass: xxxxx
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: xxxx
DEBUG: value for config item folder: templates
DEBUG: value for config item vsphere_dc: xxxx
DEBUG: value for config item linked_clone:
DEBUG: value for config item resource_pool: xxxx
DEBUG: value for config item resource_pool: xxxx
DEBUG: value for config item vsphere_dc: xxxx
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster: xxxx
DEBUG: value for config item datastorecluster: xxxx
DEBUG: value for config item vsphere_dc: xxxx
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount:
DEBUG: value for config item customization_memory:
DEBUG: value for config item customization_macs:
DEBUG: value for config item customization_sw_uuid:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item customization_spec: xxxx
DEBUG: value for config item customization_spec: xxxx
DEBUG: value for config item customization_dns_ips:
DEBUG: value for config item customization_dns_suffixes:
DEBUG: value for config item customization_gw:
/root/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.13/lib/chef/knife/vsphere_vm_clone.rb:608:in `block in generate_clone_spec': undefined method `[]' for nil:NilClass (NoMethodError)
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.13/lib/chef/knife/vsphere_vm_clone.rb:607:in `map'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.13/lib/chef/knife/vsphere_vm_clone.rb:607:in `with_index'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.13/lib/chef/knife/vsphere_vm_clone.rb:607:in `generate_clone_spec'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.13/lib/chef/knife/vsphere_vm_clone.rb:330:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:219:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/knife.rb:156:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:53:in `load'
        from /usr/bin/knife:53:in `<main>'
```
Could you please guide?

**Comment by swalberg** [comment]
Hi, are you running the latest version of the gem? Try `gem install knife-vsphere`. I thought we fixed this one up.

Failing that, does adding `--cmacs auto` to your command line help?

**Comment by raghav8888** [comment]
Yeah its the latest version. I did try to update and validated that previous fixed which were merged are there. But it is still coming up. This is for a Linux VM.

2 things I observed:
1. The fix that went in was for line 581.
2. The function def generate_adapter_map(ip = nil, gw = nil, mac = nil) sets the mac address as 

adapter_map.macAddress = mac if !mac.nil? && (mac != 'auto')

What should be the value set if it is not passed in the parameters? Also, is it necessary to pass MAC in the parameters?

This is different than https://github.com/chef-partners/knife-vsphere/issues/275

**Comment by raghav8888** [comment]
Let me try with cmacs auto. I missed that part of your response. Apologies.

**Comment by swalberg** [comment]
Normally we'd set it to `nil` and let vsphere figure it out.

**Comment by raghav8888** [comment]
It seems to be working fine with --cmacs auto. Could there be a default value (auto may be) that does not make this a mandatory parameter?

**Comment by swalberg** [comment]
It's a bug rather than a missing default. `mac_list` doesn't get defined unless certain options are set. I'll clean it up so you don't need the parameter. Looking at my scripts I had it in there, probably from testing, which is why I missed it :)

**Comment by raghav8888** [comment]
Thanks mate! Irony is I'm a tester by profession and just stepped into DevOps :P

**Comment by swalberg** [comment]
Ah, then welcome to the field. Lots of fun to go around.

**Comment by raghav8888** [comment]
I was wondering if you could guide me on a basic thing since I'm new around here. I want to do these deployments where parameters are read through a CSV file. What should be the approach? And I'm guessing the CSV should be on the node, right?

**Comment by swalberg** [comment]
These parameters are for creating new nodes with `knife vsphere vm clone`?

If you have a file like:

```
server1,1.1.1.1
server2,2.2.2.2
```

Then you could create 2 nodes with a script like
```
cat servers.txt | while read LINE; do
  server=`echo $LINE | awk -F, '{ print $1 }'`
  ip=`echo $LINE | awk -F, '{ print $2 }'`
  knife vsphere vm clone $server --cips ${ip}/24 --and --more --opts
done
```

That's all on the workstation. If some of the parameters are for the chef run then look into `--json-attributes` and you'll be passing stuff to the node, which'll get picked up by chef.

That close to what you were after?

**Comment by swalberg** [comment]
Any chance you could pull down master and try it out yourself through `bundle exec` to verify this problem disappeared? I fixed it in c3a5e77 and will cut a release shortly if someone is able to double check my work.

**Comment by kozmikyak** [comment]
--cmacs definitely should not be required, anytime that --cips is set it should have automatically populated --cmacs to as many "auto"s as there are IPs, or something similar.  I'm sorry to have thrown things into chaos with my ill-advised changes; should have tested more thoroughly, though I did at least do some cursory testing.

**Comment by kozmikyak** [comment]
Point being that the design was not that --cmac should be required, rather I wanted it to behave just as it used to if --cmac is not specified.

I'm available to answer questions about it today once I get into work in about an hour.

**Comment by swalberg** [comment]
No worries @kozmikyak, these kinds of things get difficult in a project with virtually no automated tests. I reordered a couple of things and we are closer to your original intent.

**Comment by raghav8888** [comment]
@swalberg I have a query. The command ran fine. I was able to set the gateway, IPs, hostname and even fetch the customization profile. The gateway is not getting set. Rest everything works just fine. Also, the VM does not power on. I would expect the VM to turn on and be ready with the configuration provided once knife-vsphere reports job completed. Thoughts?

**Comment by swalberg** [comment]
Did you pass `--start` to the command? By default we don't start the VM. Not sure about the gateway without knowing more specifics. Your template should have the latest vm tools running and all the network configuration nuked. Is something from the specs overriding the gateway, or making it try and set an invalid gateway?  (I should have asked, is this Windows or Linux? )

**Comment by raghav8888** [comment]
1. Passing the --start powers on the VM. Thanks for that.
2. The VM is updated with the latest version of VMware tools. It is a linux template. What's suspicious is that the IP, subnet and hostmane are getting set, just not the gateway.

Here is the command.

knife vsphere vm clone testvm1234 -f templates --template "xxxx" --vsuser xxxx --vspass xxxx --resource-pool xxxx --datastorecluster xxxx --dest-folder xxxx  --vsinsecure --vshost "x.x.x.x" --vsdc "xxxx" --cspec xxxx --cips y.y.y.y/16 --cgw z.z.z.z --cmacs auto --chostname test1234urb --start -VV

**Comment by swalberg** [comment]
I don't have a solid answer for that right now. FWIW when I clone Linux VMs I don't use `--cgw` or a `--cspec`. I suspect one of those is the culprit. Is there something in the cspec that you can't pass on the command line.

**Comment by raghav8888** [comment]
I'm trying without a --gw and will let you know. The option for Linux asks for a default gateway in the customization template. Trying that.

**Comment by raghav8888** [comment]
No luck. :( One workaround I can follow for now is knife vsphere vm execute. But could you take a look at your end if this is an issue?

**Comment by swalberg** [comment]
Did you try without both the `--cspec` and `--cgw`? Your command is almost identical to what I do.

**Comment by raghav8888** [comment]
Yeah I did. Only the default gateway is what is not getting configured.

**Comment by swalberg** [comment]
RedHat? Ubuntu? Something else? I haven't run into this before.

**Comment by raghav8888** [comment]
Centos 6. Something interesting that I noted. This is what is getting added at the end of the ifcfg-eth0 when the VM boots up.

check_link_down() {
 return 1;
}

Manually this VM clones perfect. 
![image](https://cloud.githubusercontent.com/assets/21267302/18060889/6ce9d83c-6dee-11e6-987b-ef5a14ee30a7.png)

**Comment by swalberg** [comment]
Yup, I get the same. The default route should be in a different file:
```
[root@la3stgpushapi02 ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE=eth0
ONBOOT=yes
USERCTL=no
BOOTPROTO=static
NETMASK=255.255.255.0
IPADDR=10.198.108.6
PEERDNS=no

check_link_down() {
 return 1;
}
[root@la3stgpushapi02 ~]# cat /etc/sysconfig/network-scripts/route-eth0
default via 10.198.108.1
```

**Comment by raghav8888** [comment]
Yeah but in my case this does not establish the network connectivity. Probably need to add DEFROUTE=yes in ifcfg-eth0.

**Comment by swalberg** [comment]
Hi, did you ever figure out what the problem was?

**Comment by raghav8888** [comment]
Hey Sean. Sorry the late reply. Yeah I got it resolved by modifying the network file using sed. Thanks for the help man.
