### ISSUE TITLE
Bootstrap does not wait for the VM to be assigned an IP from spec file

### ISSUE THREAD

**Issue by andrewmercerCA** [chef-partners/knife-vsphere#281]
I am cloning a VM from a template with a spec file and trying to bootstrap it. Here is how I am creating it:

knife vsphere vm clone vm_name --folder 'folder_name' --template 'template_name' \
--ccpu 2 --cram 4 --cips vm_ip --cgw <vm_gw> --cdnsips vm_dns1,vm_dns2 \
--cdnssuffix dns_suffix1,dns_suffix2 --cspec 'spec_name' --datastore 'datastore_name' \
--distro chef-full --bootstrap --winrm-user 'Administrator' --node-name 'node_name' \
--run-list 'recipe[docker::default]' --server-url 'https://chef_url/organizations/org_name' --start -y -VV

The VM gets created and picks up the customization, but bootstrapping fails because it gets an IP before customization has completed:

Cloning template template_name to new VM vm_name
Finished creating virtual machine vm_name
DEBUG: value for config item customization_plugin:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item power: true
Powered on virtual machine vm_name
DEBUG: value for config item bootstrap: true
DEBUG: Connect Host for Bootstrap: 169.254.36.234
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item bootstrap_protocol:
DEBUG: Identified os as windows.
Waiting for customization to complete...
DEBUG: value for config item sysprep_timeout: 600
Waiting for sysprep........
Customization of VM vm_name succeeded. Customization log located at C:/Windows/TEMP/vmware-imc/guestcust.log in the guest OS.
Customization Complete

DEBUG: value for config item fqdn: 169.254.36.234
DEBUG: value for config item winrm_transport: plaintext
DEBUG: value for config item winrm_port: 5985

Waiting for winrm access to become available on 169.254.36.234:5985

**Comment by swalberg** [comment]
Hi, does this box register in DNS? Passing `--fqdn hostname` might help here. Or maybe the NIC on the template should have a static address (or nothing) rather than DHCP?

**Comment by andrewmercerCA** [comment]
Hi @swalberg , shortly after posting this I did in fact use the --fqdn option to resolve this. Thank you for your response.
