### ISSUE TITLE
`knife vsphere template list` does not show templates in folders

### ISSUE THREAD

**Issue by jjasghar** [chef-partners/knife-vsphere#282]
### What are you trying to do and what's not working?

I'm trying to list/find templates that i have created in a "Linux" folder.
![image](https://cloud.githubusercontent.com/assets/810824/18401747/aa31e598-76a1-11e6-8a7b-afadbc514ed2.png)

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
15:22:47 JJs-MacBook-Pro ~ > ce knife vsphere template list
### I moved the template from "Linux" to the Root
15:23:05 JJs-MacBook-Pro ~ > ce knife vsphere template list
Template Name: ubuntu16-template
15:23:43 JJs-MacBook-Pro ~ >
```

**Comment by swalberg** [comment]
Hm, we don't seem to descend into folders. Can you try adding `-f Linux` to the command line?

**Comment by jjasghar** [comment]
Interesting!

```
15:44:51 JJs-MacBook-Pro ~ > ce knife vsphere template list
Template Name: ubuntu16-template
15:45:20 JJs-MacBook-Pro ~ > ce knife vsphere template list -f Linux
Template Name: centos7-template
```

We should either add a note to the docs and/or add it to the help.

**Comment by jjasghar** [comment]
But listing is only 1/2 the battle, when you do a `knife vsphere vm clone ubuntu-3 --template ubuntu16-template` you'll need a way to add `Linux/ubuntu16-template`.
