### ISSUE TITLE
Clone VM: A CustomizationSpec should not be used when --disable-customization is specified

### ISSUE THREAD

**Issue by martinmosegaard** [chef-partners/knife-vsphere#287]
### What are you trying to do and what's not working?
Trying to clone a Windows VM not prepared for customization, no sysprep. I get an error due to the `CustomizationSpec`. But this is an optional field in the `VirtualMachineCloneSpec` and if I set it to `nil` I am able to clone the machine.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
knife vsphere -VV vm clone <name> --template win-2012-template --folder <folder> --linked-clone --resource-pool <rp> --cips dhcp --disable-customization
...
Cloning template win-2012-template to new VM <name>
VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec( deviceChange: [] ),
  customization: CustomizationSpec(
    globalIPSettings: CustomizationGlobalIPSettings(  ),
    identity: CustomizationIdentitySettings(  ),
    nicSettingMap: [CustomizationAdapterMapping(
       adapter: CustomizationIPSettings( ip: CustomizationDhcpIpGenerator(  ) )
     )]
  ),
  location: VirtualMachineRelocateSpec(
    diskMoveType: :moveChildMostDiskBacking,
    pool: ResourcePool("resgroup-2003")
  ),
  powerOn: false,
  template: false
)
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion': InvalidArgument: A specified parameter was not correct: spec.identity (RbVmomi::Fault)
```

### Other details, such as gem version and if you're working with a Linux or Windows VM
Gem version 1.2.14.
In the `generate_clone_spec` method of `vsphere_vm_clone.rb`, I think we should simply not set the `CustomizationSpec` in this block:
```
if get_config(:disable_customization)
      clone_spec.customization = cust_spec
```

**Comment by martinmosegaard** [comment]
Here is a proposed fix, I will submit a PR later:

```
diff --git a/lib/chef/knife/vsphere_vm_clone.rb b/lib/chef/knife/vsphere_vm_clone.rb
index ad46808..e4de2d2 100644
--- a/lib/chef/knife/vsphere_vm_clone.rb
+++ b/lib/chef/knife/vsphere_vm_clone.rb
@@ -612,9 +612,7 @@ class Chef::Knife::VsphereVmClone < Chef::Knife::BaseVsphereCommand
       }
     end

-    if get_config(:disable_customization)
-      clone_spec.customization = cust_spec
-    else
+    unless get_config(:disable_customization)
       use_ident = !config[:customization_hostname].nil? || !get_config(:customization_domain).nil? || cust_spec.identity.nil?

       if use_ident
```

**Comment by swalberg** [comment]
Thanks for bringing this up, Martin. I'd run into this when doing work on #278 and wasn't sure what the proper behaviour was. Have you tried removing that line to see if it works?

I think people normally use this option in conjunction with a server side `--cspec` so that might be why it hasn't come up before. In this case that line is necessary as the customization applied with `--cspec` only gets assigned on that line. Our docs say:

```The customization specification defaults can be disabled using the --disable-customization switch and the --cspec specified as-is.

NOTE: if you are specifying a --cspec and the cloning process appears to not be properly applying the spec as defined on vSphere, consider using the --disable-customization as the conventions described above could be erroneously interfering with the spec as defined on vSphere.
```

I don't know if that's right because it predates me on the project, so before I make any changes here I'd like to try and figure out both what's right and what won't break backward compatibility.

I think that assigning ` clone_spec.customization ` to the cspec earlier on and then removing the line you mention is possibly the correct way.

**Comment by swalberg** [comment]
Hi Martin, WRT your proposed change, I think that'll break things for people that also use `--cspec`. Right or wrong, it's what our docs say to do.

The good news is that #278 [heavily unit tests those options](https://github.com/chef-partners/knife-vsphere/pull/278/files#diff-adb1f0fa6d9c39796d788388b02e6da9R143) so at least what we do here should stick around and we should be confident we're not breaking more.

**Comment by martinmosegaard** [comment]
Thanks for your reply. I was just looking for a way to not do guest customization at all. I currently don't have the knowledge to do a proper fix for other use cases.

**Comment by swalberg** [comment]
Do you know if it works if you pass nothing in the customization, as opposed to an empty customization structure? I can test later today, too.

**Comment by swalberg** [comment]
(or rather, does your proposed fix work for you?)

**Comment by martinmosegaard** [comment]
Yes, that works for me :) So you can have a `VirtualMachineCloneSpec` where `customization` is `nil`. That works, because it is an optional field in the VMODL. Corresponding to http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.CloneSpec.html
