### ISSUE TITLE
Allow custom MSI URL when bootstrapping a Windows VM

### ISSUE THREAD

**Issue by martinmosegaard** [chef-partners/knife-vsphere#289]
### What are you trying to do and what's not working?
I want to clone a Windows VM and then bootstrap it with a Chef server. The node does not have Internet access, and so when using `knife windows` on a command line, I use the `--msi-url` option to specify a custom `chef-client` install URL. 
However, I cannot do this from `knife vsphere` today. It would be great if we could add an option like `--bootstrap-msi-url` that is passed on to `BootstrapWindowsWinrm`.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
knife vsphere vm clone <name> --template win-2012-template --folder <folder> --bootstrap --linked-clone --bootstrap-protocol winrm --cips dhcp --resource-pool <rp>
```
A knife-windows command to bootstrap using a custom MSI URL:
```
knife bootstrap windows winrm <ip address of node> -x <user> -N <name> --msi-url <a url inside my org that my node can reach>
```

### Other details, such as gem version and if you're working with a Linux or Windows VM
Gem version 1.2.14.

**Comment by martinmosegaard** [comment]
This is also mentioned in issue #272 but that issue has a broader discussion.

**Comment by swalberg** [comment]
So my problem is that I don't do much Windows work so testing these things is kind of troublesome.

JJ and I worked through #284 and it does look like getting options over to the Bootstrap code is as simple as that. See the `bootstrap_for_windows_node` method.

If I put a branch together are you able to try it out?

**Comment by martinmosegaard** [comment]
I am able to try it out against Windows VMs. I currently work on a fork of `knife-vsphere` where I cannot submit PRs upstream, but I am happy to report back here :)

**Comment by swalberg** [comment]
Can you try it out against my branch above? https://github.com/swalberg/knife-vsphere/tree/msi-url (or just copy paste into your local copy, it's only a few lines)

Thanks.

**Comment by martinmosegaard** [comment]
Thanks, yes it almost works. I just had to add a `URL` value to the new parameter, like this:

```
diff --git a/lib/chef/knife/vsphere_vm_clone.rb b/lib/chef/knife/vsphere_vm_clone.rb
index e4de2d2..3cbf0e7 100644
--- a/lib/chef/knife/vsphere_vm_clone.rb
+++ b/lib/chef/knife/vsphere_vm_clone.rb
@@ -147,6 +147,10 @@ class Chef::Knife::VsphereVmClone < Chef::Knife::BaseVsphereCommand
          long: '--fqdn SERVER_FQDN',
          description: 'Fully qualified hostname for bootstrapping'

+  option :bootstrap_msi_url,
+         long: '--bootstrap-msi-url URL',
+         description: 'Location of the Chef Client MSI. The default templates will prefer to download from this location.'
+
   option :bootstrap_protocol,
          long: '--bootstrap-protocol protocol',
          description: 'Protocol to bootstrap windows servers. options: winrm/ssh',
@@ -778,6 +782,7 @@ class Chef::Knife::VsphereVmClone < Chef::Knife::BaseVsphereCommand
       bootstrap.config[:winrm_password] = get_config(:winrm_password)
       bootstrap.config[:winrm_transport] = get_config(:winrm_transport)
       bootstrap.config[:winrm_port] = get_config(:winrm_port)
+      bootstrap.config[:msi_url] = get_config(:bootstrap_msi_url)
     elsif get_config(:bootstrap_protocol) == 'ssh'
       bootstrap = Chef::Knife::BootstrapWindowsSsh.new
       bootstrap.config[:ssh_user] = get_config(:ssh_user)
```

**Comment by swalberg** [comment]
I had put that in `bootstrap_common_params`, did it not work there? Or does it not make sense for an SSH bootstrapped node (I guess I could have equally put it after the `if` statement.

**Comment by martinmosegaard** [comment]
Sorry, I missed that. I will try that.

**Comment by martinmosegaard** [comment]
It works in `bootstrap_common_params` too. So I only changed this line to have the `URL` value:

` long: '--bootstrap-msi-url URL',`
