### ISSUE TITLE
join domain specific OU

### ISSUE THREAD

**Issue by bathenme** [chef-partners/knife-vsphere#292]
hi,
i'm trying to clone a new virtual machine and to join in to domain whit specific OU ....
can i do that whit knife vsphere vm clone?

**Comment by swalberg** [comment]
Hi there, I'm sure it's possible, just not sure about the specifics offhand.

Are you able to join it to a domain in general? Can you paste the command you're trying to run and the output, please?

Thanks!

**Comment by bathenme** [comment]
hi,
yes im able to add to domain 
my command is:

knife vsphere vm clone BHTest --vshost vcname --vsdc "DataCenter" --vsuser vcuser --vspass password --template Template --cspec test_bh --cips 2.2.2.2/24 --cgw 2.2.2.1 --cdnsips 2.2.2.5 --vsinsecure --datastore DataStore --dest-folder "VMs" --start --bootstrap --bootstrap-ipv4 --node-name bhtest --winrm-user vcuser  --winrm-password password  -VV

and he adds the computer to domain just fine but i wanted to chose the OU but i dont see this option in the help....

**Comment by swalberg** [comment]
Hello, did this ever work for you? I'm going to close this ticket; please re-open/comment if something new has come up. Thanks.
