### ISSUE TITLE
bootstrap-msi-url not working in version 1.2.16

### ISSUE THREAD

**Issue by cwlong0** [chef-partners/knife-vsphere#295]
### What are you trying to do and what's not working?
try to bootstrap chef while provisioning the VM. the CHEF client installation location is set up in a local environment. knife vsphere doest nt recognize the option --bootstrap-msi-url

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
[root@pr2vmx40 default]# knife vsphere vm clone st2vmx101 --template OEL_6.5_Template_20160909 --dest-folder OSM --resource-pool Singapore_Staging_Level-1_1 --ccpu 2 --cram 8 --cips 10.14.144.71/24,10.14.148.71/24 --chostname st2vmx101 --cdomain sin.dc.gemalto.com --cvlan "TEST SIN DC TSM LEVEL 1 DATA","TEST SIN DC TSM LEVEL 1 MGT" --bootstrap  --node-name st2vmx101 --environment staging --run-list base --bootstrap-msi-url https://xxx.xxx.com/pub/GTO-DCI-SW/CHEF/install.sh
Error: invalid option: --bootstrap-msi-url
USAGE: knife vsphere vm clone VMNAME (options)

```

**Comment by swalberg** [comment]
Hi, we added this option in 1.2.16 which was released a few days ago. You'll want to upgrade the gem (`chef gem install knife-vsphere` if you use ChefDK, or `gem install knife-vsphere` otherwise)

**Comment by cwlong0** [comment]
jsut upgraded the knife vsphere to 1.2.16. but the msi-url is not taking effect. bootstrap is still referring to the default chef.io. please refer to below.

[root@pr2vmx40 chef-repo]# knife vsphere vm clone st2vmx101 --template OEL_6.5_Template_20160909 --bootstrap  --node-name st2vmx101 --environment staging --run-list base -**_-bootstrap-msi-url https://10.14.36.52/pub//GTO-DCI-SW/CHEF/install.sh_** --dest-folder OSM --resource-pool Singapore_Staging_Level-1_1 --ccpu 2 --cram 8 --cips 10.14.144.71/24,10.14.148.71/24 --chostname st2vmx101 --cdomain sin.dc.gemalto.com --cvlan "TEST SIN DC TSM LEVEL 1 DATA","TEST SIN DC TSM LEVEL 1 MGT"

Cloning template OEL_6.5_Template_20160909 to new VM st2vmx101
Finished creating virtual machine st2vmx101
Powered on virtual machine st2vmx101
Waiting for network interfaces to become available...

Waiting for sshd access to become available on 10.14.144.71:22done
Doing old-style registration with the validation key at /root/chef-repo/.chef/sindci-validator.pem...
Delete your validation key in order to use your user credentials instead

Connecting to 10.14.144.71
10.14.144.71 -----> Installing Chef Omnibus (-v 12)
10.14.144.71 downloading **_https://omnitruck-direct.chef.io/chef/install.sh_**

**Comment by cwlong0** [comment]
adding in -VV logging info.

Finished creating virtual machine st2vmx101
DEBUG: value for config item customization_plugin:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item power:
DEBUG: value for config item bootstrap: true
Powered on virtual machine st2vmx101
DEBUG: value for config item bootstrap: true
Waiting for network interfaces to become available...
Found address 10.14.144.71
DEBUG: value for config item bootstrap_nic: 0
DEBUG: Connect Host for Bootstrap: 10.14.144.71
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item bootstrap_protocol:

Waiting for sshd access to become available on 10.14.144.71:22DEBUG: sshd accepting connections on 10.14.144.71, banner is SSH-2.0-OpenSSH_5.3

done
DEBUG: value for config item ssh_user: root
DEBUG: value for config item winrm_user: Administrator
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item winrm_port: 5985
DEBUG: value for config item ssh_password:
DEBUG: value for config item winrm_password:
DEBUG: value for config item identity_file:
DEBUG: value for config item kerberos_keytab_file:
DEBUG: value for config item secret_file:
DEBUG: value for config item ssh_user: root
DEBUG: value for config item ssh_password:
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item identity_file:
DEBUG: value for config item ssh_user: root
DEBUG: value for config item ssh_user: root
DEBUG: value for config item log_level:
DEBUG: value for config item bootstrap_version:
DEBUG: value for config item distro: chef-full
DEBUG: value for config item template_file:
DEBUG: value for config item environment: staging
DEBUG: value for config item prerelease:
DEBUG: value for config item first_boot_attributes: {}
DEBUG: value for config item hint:
DEBUG: value for config item chef_node_name: st2vmx101
DEBUG: value for config item bootstrap_vault_file:
DEBUG: value for config item bootstrap_vault_json:
DEBUG: value for config item bootstrap_vault_item:
DEBUG: value for config item no_host_key_verify:
Doing old-style registration with the validation key at /root/chef-repo/.chef/sindci-validator.pem...
Delete your validation key in order to use your user credentials instead

Connecting to 10.14.144.71
DEBUG: Looking for bootstrap template in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife/bootstrap/templates
DEBUG: Found bootstrap template in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife/bootstrap/templates
DEBUG: Adding 10.14.144.71
DEBUG: establishing connection to 10.14.144.71:22
DEBUG: connection established
INFO: negotiating protocol version
DEBUG: local is `SSH-2.0-Ruby/Net::SSH_3.1.1 x86_64-linux'
DEBUG: remote is `SSH-2.0-OpenSSH_5.3'
DEBUG: read 840 bytes
DEBUG: received packet nr 0 type 20 len 836
INFO: got KEXINIT from server
INFO: sending KEXINIT
DEBUG: queueing packet nr 0 type 20 len 1684
DEBUG: sent 1688 bytes
INFO: negotiating algorithms
DEBUG: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client:
* language_server:
DEBUG: exchanging keys
DEBUG: queueing packet nr 1 type 34 len 20
DEBUG: sent 24 bytes
DEBUG: read 152 bytes
DEBUG: received packet nr 1 type 31 len 148
DEBUG: queueing packet nr 2 type 32 len 140
DEBUG: sent 144 bytes
DEBUG: read 720 bytes
DEBUG: received packet nr 2 type 33 len 700
DEBUG: queueing packet nr 3 type 21 len 20
DEBUG: sent 24 bytes
DEBUG: received packet nr 3 type 21 len 12
DEBUG: beginning authentication of `root'
DEBUG: queueing packet nr 4 type 5 len 28
DEBUG: sent 52 bytes
DEBUG: read 52 bytes
DEBUG: received packet nr 4 type 6 len 28
DEBUG: trying none
DEBUG: queueing packet nr 5 type 50 len 44
DEBUG: sent 68 bytes
DEBUG: read 216 bytes
DEBUG: received packet nr 5 type 53 len 76
INFO: Oracle Linux Server release 6.5
Kernel \r on an \m


DEBUG: received packet nr 6 type 51 len 92
DEBUG: allowed methods: publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive
DEBUG: none failed
DEBUG: trying publickey
DEBUG: connecting to ssh-agent
ERROR: could not connect to ssh-agent
DEBUG: trying publickey (55:6c:9a:ea:af:de:f1:50:1b:00:ae:7a:62:f7:e9:ac)
DEBUG: queueing packet nr 6 type 50 len 348
DEBUG: sent 372 bytes
DEBUG: read 324 bytes
DEBUG: received packet nr 7 type 60 len 300
DEBUG: queueing packet nr 7 type 50 len 620
DEBUG: sent 644 bytes
DEBUG: read 36 bytes
DEBUG: received packet nr 8 type 52 len 12
DEBUG: publickey succeeded (55:6c:9a:ea:af:de:f1:50:1b:00:ae:7a:62:f7:e9:ac)
DEBUG: queueing packet nr 8 type 90 len 44
DEBUG: sent 68 bytes
DEBUG: read 52 bytes
DEBUG: received packet nr 9 type 91 len 28
INFO: channel_open_confirmation: 0 0 0 32768
INFO: sending channel request "env"
DEBUG: queueing packet nr 9 type 98 len 44
INFO: sending channel request "pty-req"
DEBUG: queueing packet nr 10 type 98 len 60
INFO: sending channel request "exec"
DEBUG: queueing packet nr 11 type 98 len 7468
DEBUG: sent 7644 bytes
DEBUG: read 88 bytes
DEBUG: received packet nr 10 type 93 len 28
INFO: channel_window_adjust: 0 +2097152
DEBUG: received packet nr 11 type 99 len 12
INFO: channel_success: 0
DEBUG: read 212 bytes
DEBUG: received packet nr 12 type 94 len 188
INFO: channel_data: 0 161b
10.14.144.71 -----> Installing Chef Omnibus (-v 12)
10.14.144.71 downloading https://omnitruck-direct.chef.io/chef/install.sh
10.14.144.71   to file /tmp/install.sh.2738/install.sh
10.14.144.71 trying wget...
DEBUG: read 68 bytes
DEBUG: received packet nr 13 type 94 len 44
INFO: channel_data: 0 16b
10.14.144.71 trying curl...
DEBUG: read 68 bytes
DEBUG: received packet nr 14 type 94 len 44
INFO: channel_data: 0 16b
10.14.144.71 trying perl...
DEBUG: read 68 bytes
DEBUG: received packet nr 15 type 94 len 44
INFO: channel_data: 0 18b
10.14.144.71 trying python...
DEBUG: read 1460 bytes
DEBUG: received packet nr 16 type 94 len 1436
INFO: channel_data: 0 1412b
10.14.144.71 >>>>>> wget, curl, fetch, perl, or python not found on this instance.
10.14.144.71 \nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2016-09-15 14:46:03--  https://omnitruck-direct.chef.io/chef/install.sh
10.14.144.71 Resolving omnitruck-direct.chef.io... failed: Name or service not known.
10.14.144.71 wget: unable to resolve host address âomnitruck-direct.chef.ioâ
10.14.144.71 BEGIN failed--compilation aborted at -e line 1.\n\nSTDERR from python:\n\nTraceback (most recent call last):
10.14.144.71   File "<string>", line 1, in <module>
10.14.144.71   File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
10.14.144.71     return _opener.open(url, data, timeout)
10.14.144.71   File "/usr/lib64/python2.6/urllib2.py", line 391, in open
10.14.144.71     response = self._open(req, data)
10.14.144.71   File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
10.14.144.71     '_open', req)
10.14.144.71   File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
10.14.144.71     result = func(*args)
10.14.144.71   File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
10.14.144.71     return self.do_open(httplib.HTTPSConnection, req)
10.14.144.71   File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
10.14.144.71     raise URLError(err)
10.14.144.71 urllib2.URLError: <urlopen error [Errno -2] Name or service not known>\n
DEBUG: read 272 bytes
DEBUG: received packet nr 17 type 98 len 44
INFO: channel_request: 0 exit-status false
DEBUG: received packet nr 18 type 94 len 108
INFO: channel_data: 0 85b
10.14.144.71 Starting the first Chef Client run...
10.14.144.71 sh: line 257: chef-client: command not found
DEBUG: received packet nr 19 type 96 len 12
INFO: channel_eof: 0
DEBUG: received packet nr 20 type 97 len 12
INFO: channel_close: 0
DEBUG: queueing packet nr 12 type 97 len 28
INFO: 10.14.144.71 delete channel 0 which closed locally and remotely
INFO: closing remaining channels (0 open)

**Comment by swalberg** [comment]
Oh! Is this a Linux box? That option only works on Windows bootstrapping... I'd need to dig around to see if there's an option for the Linux bootstrap phase (this gem doesn't implement the bootstrap code; we just hand it off to Chef with a bunch of options)

**Comment by cwlong0** [comment]
i c. thanks. so after VM provisioned, i just use the chef bootstrap to add the node into the chef server. previously we were using Xen plugin, it supports the bootstrap when provision the VM.
but vSphere plugin is supporting more features than Xen plugin.

Again thanks for reply.

**Comment by cwlong0** [comment]
just add in 1 more issue.
after provision the VM, it seems the network interface name changed. in the template it's eth0 and eth1, the VM provisioned is having eth2 and eth3.

do you have any hints on this issue?
Thanks.

regards,
long

**Comment by swalberg** [comment]
For the NIC thing, the template probably has a configuration for eth0 so the VMWare agent is starting at eth1. I make sure that I've removed /etc/udev/rules.d/70-persistent-net.rules and /etc/sysconfig/network-scripts/ifcfg-eth0 from my template.

**Comment by cwlong0** [comment]
Great. thanks for the advice. solved it.
for the VM cloning, is it possible to add the static route rule to the new VM in addition to the default gateway? As you know, in most env, data network is used for serving service which going through the default gateway, for management, like CHEF, normally it's connecting via management network by a specific static route.

does this make sense?

Thanks.

regards,
long

**Comment by swalberg** [comment]
Glad to hear it worked. VMWare customization is fairly sensitive to the configuration on the template.

The plugin doesn't natively support what you're trying to do, namely to add a static route during customization. I took a look through [the API we use](http://pubs.vmware.com/vsphere-50/index.jsp#com.vmware.wssdk.apiref.doc_50/vim.vm.customization.IPSettings.html#field_detail) and I don't see anywhere you can tell VMWare to add a static route.

One option would be to include the static route as part of your template, though with multiple VLANs this may not be practical.

There is, however, a [hook called #reconfig_vm](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L360-L363) you could use in a plugin that would run a command on the box after it's been provisioned but before we run Chef. The README has some info on how a plugin is written and you would copy code from the [vsphere vm execute command](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_execute.rb#L51-L60) to do the heavy lifting.

If a plugin isn't your thing, or you just want to try out the procedure, you could clone the VM with `--start` and forget about bootstrapping. Then run `knife vsphere vm execute` to add the static route, and bootstrap with `knife bootstrap` (so basically doing all that the plugin would do at the command line).

My experience is that host routes on servers rarely end up working well because they're hard to manage (even with Chef helping out). I'm not sure if it's possible, but having your default gateway route your management traffic (and optionally applying a security policy at the same time) may save you this headache, and more in the future.

**Comment by jjasghar** [comment]
It looks like this issue was resolved. :metal: If you have any more questions please open another issues @cwlong0

**Comment by cwlong0** [comment]
sure, sorry for that. the issue is resolved.
regarding the static route topic, we ended up to provision the VM with management network as default gateway, then bootstrap the CHEF, adding in static route for management network, and change back the default gateway to service network.

but still, guys, thanks for the great advices here.

regards,
long
