### ISSUE TITLE
`snapshot --revert <snap> --start` help is ambiguous

### ISSUE THREAD

**Issue by dhildebrandt** [chef-partners/knife-vsphere#300]
### The documentation (as seen in README.md and snapshot help) states:
`--start           - Indicates whether to start the VM after a successful revert`
The **behavior** is unambiguous: if you specify `--start` the VM will start after a successful revert, and if you don't, it won't.

Therefore a clearer wording is:
`--start           - causes the VM to start after a successful revert`

"whether" would be language used if there were an additional parameter required. I spent some time testing --start to discover that it is a presence => true, absence => false type flag.  

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
nothing as this is a doc issue
```

### Other details, such as gem version and if you're working with a Linux or Windows VM
knife is running on Ubuntu 14.04.5 LTS 
knife-vsphere is 1.2.17

**Comment by swalberg** [comment]
Thanks, let me double check the code against this description and make the fix. I would likely use the active voice of `starts the VM after a successful revert` if you think that still conveys the same meaning.

**Comment by dhildebrandt** [comment]
+1 for active voice!!
