### ISSUE TITLE
no such folder <> while looking for <> - option containing space is not parsed properly

### ISSUE THREAD

**Issue by nkichukov** [chef-partners/knife-vsphere#302]
### What are you trying to do and what's not working?

I am building a new VM using 'knife vsphere vm clone' command where the destination folder contains a space in it.
### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information

DESTFOLDER="YYY/_XXX zzz/test" - I have attempted multiple variations here, different quotes, different escapes for ' ', nothing works.

$knife vsphere vm clone vmane -f $FOLDER --template $TEMPLATE --dest-folder ${DESTFOLDER} --datastorecluster $DSCLUSTER --cspec $SPEC --cvlan $VLAN --cips IP/24 --cram 4 --ccpu 2 --resource-pool $RESPOOL --thin-provision --ssh-user $SSHUSER --ssh-password $SSHPASS --bootstrap --server-url $CHEFURL -r "role[XXX]," -VV
DEBUG: value for config item datastore:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item chef_node_name:
DEBUG: value for config item vsphere_host: XXX
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: XXX
DEBUG: value for config item vsphere_pass: XXX
DEBUG: value for config item vsphere_pass: XXX
DEBUG: value for config item vsphere_pass: XXX
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: XXX
DEBUG: value for config item folder: XXX
DEBUG: value for config item vsphere_dc: XXX
DEBUG: value for config item linked_clone:
DEBUG: value for config item resource_pool: XXX
DEBUG: value for config item resource_pool: XXX
DEBUG: value for config item vsphere_dc: XXX
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster: XXX
DEBUG: value for config item datastorecluster: XXX
DEBUG: value for config item vsphere_dc: XXX
DEBUG: value for config item thin_provision: true
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_cpucount: 2
DEBUG: value for config item customization_memory: 4
DEBUG: value for config item customization_memory: 4
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item customization_ips: XXX/24
DEBUG: value for config item customization_sw_uuid:
DEBUG: value for config item customization_vlan: XXX
DEBUG: value for config item customization_vlan: XXX
DEBUG: value for config item vsphere_dc: XXX
DEBUG: value for config item customization_sw_uuid:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item customization_spec: XXX
DEBUG: value for config item customization_spec: XXX
DEBUG: value for config item disable_customization: false
DEBUG: value for config item customization_dns_ips:
DEBUG: value for config item customization_dns_suffixes:
DEBUG: value for config item customization_gw:
DEBUG: value for config item customization_domain:
DEBUG: value for config item customization_plugin:
DEBUG: value for config item vsphere_dc: XXX
no such folder YYY/_XXX while looking for _XXX
no such folder YYY/_XXX while looking for _XXX
### Other details, such as gem version and if you're working with a Linux or Windows VM

This was not working with knife-vsphere version 1.2.8, I have upgraded to 1.2.16, it still does not work.

Seems like config[:dest_folder] gets incorrectly populated. If there is a space, it would truncate and appear to be set to YYY/_XXX ignoring everything after it. In that way the code below from vsphere_vm_clone.rb:

```
cust_folder = config[:dest_folder] || get_config(:folder)

dest_folder = cust_folder.nil? ? src_vm.vmFolder : find_folder(cust_folder)
```

makes a call to find_folder('YYY/_XXX') which is wrong. Why is the config array not initialized properly? This has to do with parsing the options from bash on the command line.

What initializes the symbol :dest_folder ?
Thank you!

**Comment by swalberg** [comment]
Hi, thanks for the detailed bug report. This might be related to #301 which was just reported. That `config` hash comes from Chef itself. See https://github.com/chef-partners/knife-vsphere/blob/245fb067d5fe4e76694d18d5dba91de604b7e37a/lib/chef/knife/vsphere_vm_clone.rb#L35-L37 for where we define the option in the clone.

I'm traveling this week, will look next week unless someone gets to it first. Would be curious to know if we can reproduce with a spec.

**Comment by nkichukov** [comment]
Hi swalberg,
I opened this case here, because I found very similar issue already reported with chef mainline here:
https://github.com/chef/chef/issues/3885, they forward to knife-vsphere.

If the config[] hash comes from chef, this needs to go to them. Let me know once you can confirm and I can reopen with them.
Thank you,
-Nik

**Comment by swalberg** [comment]
Hi Nik, I'll pull out the debugger when I get back. In that issue's case, it does look like the space is being picked up.

When you did this, did you try passing the pool name direct on the command line rather than using variable expansion, e.g. `--dest-folder "my pool"` rather than `--dest-folder ${DESTFOLDER}`? I know I've ran into this with VLANs with spaces in it, but always ascribed my problem to shell quoting rules.

Either way I'll have a look and see if I can figure out where the problem lies.

**Comment by swalberg** [comment]
I can reproduce this, but it looks like shell quoting problems as opposed to something with Knife:

```
sean~/work/knife-vsphere (master *)$ DC=LV bundle exec knife vsphere vm clone sean1 --dest-folder "seanroot/sean test" --template CentOS_6.7_Template_16GB_v1.6 --cips dhcp
Cloning template CentOS_6.7_Template_16GB_v1.6 to new VM sean1
Finished creating virtual machine sean1
sean~/work/knife-vsphere (master *)$ DEST="seanroot/sean test"
sean~/work/knife-vsphere (master *)$ export DEST
sean~/work/knife-vsphere (master *)$ DC=LV bundle exec knife vsphere vm clone sean1 --dest-folder $DEST --template CentOS_6.7_Template_16GB_v1.6 --cips dhcp
no such folder seanroot/sean while looking for sean
sean~/work/knife-vsphere (master *)$ DC=LV bundle exec knife vsphere vm clone sean1 --dest-folder "$DEST" --template CentOS_6.7_Template_16GB_v1.6 --cips dhcp
Cloning template CentOS_6.7_Template_16GB_v1.6 to new VM sean1
Finished creating virtual machine sean1
```

Can you try the quoting please?

**Comment by nkichukov** [comment]
Thanks, I will run some more tests and provide updates with my findings.
Cheers,
-Nik

**Comment by nkichukov** [comment]
Hi Sean,
Just managed to test and you are right. The issue seems to be with the shell and not with chef or chef-vsphere.

We can close this now. Thank you for your help!
-Nikolay
