### ISSUE TITLE
find_network doesn't limit itself to specified VLAN

### ISSUE THREAD

**Issue by dhgwilliam** [chef-partners/knife-vsphere#307]
### What are you trying to do and what's not working?

When the vm clone command calls `find_network()` it simply looks for a VLAN by name but does not exclude VLANs with the same name as the target _but on different DV switches_.
### Other details, such as gem version and if you're working with a Linux or Windows VM

vSphere 6, gem built locally from `master`

**Comment by swalberg** [comment]
Interesting, I'll have a look into it. Thanks!

**Comment by dhgwilliam** [comment]
I may be able to offer a patch/PR later this week, if it ends up fitting in
to my story :)
