### ISSUE TITLE
knife vsphere vm vmdk add

### ISSUE THREAD

**Issue by bathenme** [chef-partners/knife-vsphere#309]
Hi,
i am trying to run this command:
`knife vsphere vm vmdk add $MachineName 25 --vshost $VCenter --vsdc $Datacenter --vsuser $vcUser --vspass $VCPassword --vsinsecure`

and its works fine and add disk to the virtual machine .
but if i run the command from powershell i get this error :

> ```
> knife : Creating VMDK
> At C:\Source\Repos\chef-repo\Scripts\newVm.ps1:131 char:5
> +     knife vsphere vm vmdk add $MachineName 25 --vshost $VCenter --vsd ...
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (Creating VMDK:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> Capacity: 25 GB
> Disk: [DataStore] bhchef3/bhchef3_2.vmdk
> Attaching VMDK to bhchef3
> ```

the command works fine but still puts out the error.(just from powershell command line)

any ideas?

**Comment by swalberg** [comment]
I don't suppose it gives you a stack trace or the output of the command? Can you try running with `-VV` for more output, please? Maybe also give the output of the first command you sent so I can see what it's sending?

My guess is that `knife` is writing something to the error stream which is not really an error, but powershell is interpreting as a problem. If I were a betting man it would be https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_vmdk_add.rb#L63

**Comment by swalberg** [comment]
Sorry, I should also add if you Google for `NativeCommandError` you can see some strategies for dealing with subshells that send error messages, like redirecting streams to null. I'm afraid I'm not a powershell user so not sure which ones I looked at were good solutions though, so I won't point you to anything specific.

**Comment by swalberg** [comment]
Hi, did you find out any more information about this?

**Comment by bathenme** [comment]
yes,
the command is
knife vsphere vm vmdk add $MachineName 50 --vshost $VCenter --vsdc "$Datacenter" --vsuser $vcUser --vspass $VCPassword --vsinsecure  2>&1 | % { $_.ToString() } 
it helps to not display the error but if i have real errors i can see them also ..
