### ISSUE TITLE
Bug: vsphere vm cdrom

### ISSUE THREAD

**Issue by coda4096** [chef-partners/knife-vsphere#321]
### What are you trying to do and what's not working?

Try to mount an ISO to a VM with no CD/DVD drive

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```

DEBUG: value for config item datastore: ESX-Datastore
DEBUG: value for config item iso: ISOs/CentOS-6.8-x86_64-LiveDVD.iso
/home/scott/Documents/chef/knife-vsphere/lib/chef/knife/vsphere_vm_cdrom.rb:77:in `run': undefined method `key' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/chef-12.15.19/lib/chef/knife.rb:429:in `block in run_with_pretty_exceptions'
	from /var/lib/gems/2.3.0/gems/chef-12.15.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /var/lib/gems/2.3.0/gems/chef-12.15.19/lib/chef/knife.rb:428:in `run_with_pretty_exceptions'
	from /var/lib/gems/2.3.0/gems/chef-12.15.19/lib/chef/knife.rb:219:in `run'
	from /var/lib/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/knife.rb:156:in `run'
	from /var/lib/gems/2.3.0/gems/chef-12.15.19/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:23:in `load'
	from /usr/local/bin/knife:23:in `<main>'

```

### Other details, such as gem version and if you're working with a Linux or Windows VM

Works fine when a CD/DVD drive is present, but should this add a drive or at least check for one before mounting an ISO?

**Comment by swalberg** [comment]
Hi, thanks for reporting this. I think the proper behaviour would be to fail with a helpful error rather than what we have now.

**Comment by coda4096** [comment]
I can have a look at fixing this, I am working on a knife for adding the CD/DVD drive to a VM too.

**Comment by swalberg** [comment]
I had started writing tests for this class over the weekend so I could do some cleanup. Were you going to put your new command in a separate class or make it part of this one?

**Comment by coda4096** [comment]
Probably a separate one

**Comment by swalberg** [comment]
Cool, thanks. I just pushed up #322 that cleans up the class and fixes the bug you reported. Give it a shot and let me know if it works for you!
