### ISSUE TITLE
Add new disk functionality

### ISSUE THREAD

**Issue by warroyo** [chef-partners/knife-vsphere#324]
Would it be possible to add functionality for adding another disk to a vm? This could either be done during clone , as a new command `vm disk add`, or both.

If there is a way to do this currently that I am missing, then there would be no need for this.

**Comment by swalberg** [comment]
Hi,

You can use `knife vsphere vm vmdk` to add a vmdk to an existing VM. If you want to do it at clone time it's possible through a custom plugin. There's an example in the bottom of the README about modifying the clone spec for other purposes.

If you do go down the route of creating a plugin let me know if you need help or would be willing to share the results.

**Comment by warroyo** [comment]
awesome, thanks for the quick response!

**Comment by warroyo** [comment]
@swalberg i am working on a plugin as you suggested, however i cant seem to be able to access the VMNAME from the plugin is this possible? the clone_spec does not have it either.

**Comment by swalberg** [comment]
Hi, the hostname is somewhere in the identity, but it depends on if you're doing Linux or Windows.

What do you need the vmname for though?

**Comment by warroyo** [comment]
I am able to see the hostname(this is for linux). I am adding the ability to add an additional disk during the clone as well, and I need to use the vmname for the folder structure and vmdk file.

if there is a better way to get that info that you know of I can try that.

**Comment by swalberg** [comment]
Ah, seems reasonable. You could pass it in as `data` as another approach.

If you can share what you eventually come up with, I'll see if it would make more sense to have this gem pass the name to the plugin.

**Comment by warroyo** [comment]
that was the last piece I needed to get the plugin working. here is the plugin.

https://gist.github.com/warroyo/4887300cbb3bec2034650202a65fb906

**Comment by swalberg** [comment]
Awesome! Mind if I link this up from the project?

**Comment by warroyo** [comment]
don't mind at all, hopefully others find it useful.

**Comment by swalberg** [comment]
Added to the docs this morning. Thanks for putting this together!
