### ISSUE TITLE
Is it possible to deploy a VM to a specific host?

### ISSUE THREAD

**Issue by ZedCode** [chef-partners/knife-vsphere#326]
### What are you trying to do and what's not working?
I have multiple hosts in each resource pool, I'd like to control where a VM gets deployed within that resource pool, but I don't seem to be able to specify it. Is there a way to do this that I'm overlooking?

**Comment by swalberg** [comment]
Hi, no I don't think you're missing anything. We do the [relocation spec](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.RelocateSpec.html) to the [pool](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L512-L517).

It's technically possible to specify a host instead; it's just never come up before. I guess people rely on DRS to move stuff around?

**Comment by jjasghar** [comment]
I'm interested in this feature too, `--vhost` won't work; this needs to be written as a new feature it seems.

**Comment by digitalmichael** [comment]
+1

Sometimes you need a little more control of vm placement. Rather than writing scripts to adjust after the fact it would be nice to deploy as desired.

**Comment by zerosevens** [comment]
+1 
I would love to have the ability to add VMs to a specific host

**Comment by swalberg** [comment]
Hey folks, @jjasghar and I were just working on this functionality. Would love to see if it works for you. Check out the [branch](https://github.com/chef-partners/knife-vsphere/tree/clone_to_host) locally and use the `--host` option.

Please let me know in this thread how it works for you. Would also be interested to know if you are using clusters or not, as we saw some variance between a top level cluster and not having a top level cluster.

**Comment by ZedCode** [comment]
This seems awesome! I should have time to provide feedback on how it worked tomorrow. For what it's worth, we are using clusters.

**Comment by digitalmichael** [comment]
Just did a quick test, and that worked. I deployed to 2 different hosts in the same cluster. 

Very cool, thank you!

**Comment by ZedCode** [comment]
So far this is working for us. Thanks!

**Comment by ZedCode** [comment]
Looks like this got merged in, I'm happy closing this now. Thanks for this very useful addition!
