### ISSUE TITLE
datastore_list and hosts_list do not have proper exit codes

### ISSUE THREAD

**Issue by warroyo** [chef-partners/knife-vsphere#337]
I noticed that the hosts and datastore list commands will not exit with a proper code of `1` when it can not find the pool. Other list commands have this implemented already(https://github.com/chef-partners/knife-vsphere/blob/11aa06cf023afc4589f8025099b079c38f4d57cf/lib/chef/knife/vsphere_vm_disk_list.rb#L15)

**Comment by warroyo** [comment]
I have created a pull request for this issue https://github.com/chef-partners/knife-vsphere/pull/338

**Comment by swalberg** [comment]
Thanks Will! I'll have a look this weekend. 

Sean

**Comment by warroyo** [comment]
closing this since the change was merged in.
