### ISSUE TITLE
Ability to choose datastore by space available and regex during clone

### ISSUE THREAD

**Issue by warroyo** [chef-partners/knife-vsphere#339]
It would be great to be able to choose a datastore with the  most space available during a clone. Also being able to select a datastore or group of datastores by regex would be nice. 

For example my use case is that I have many datastores in a cluster, however even though I have access to some datastores and they have available space I may not want them to be selected because they are specific purposes.

It looks like the base functions for this to work are already implemented and it would just be a matter of changing out some methods in the `clone` command. 

regex:
https://github.com/chef-partners/knife-vsphere/blob/6135e5a05b93f3463c642bfd3300399e552fa465/lib/chef/knife/base_vsphere_command.rb#L263

choose by size:

https://github.com/chef-partners/knife-vsphere/blob/6135e5a05b93f3463c642bfd3300399e552fa465/lib/chef/knife/base_vsphere_command.rb#L236

would it make sense to just allow the `--datastore` option to accept regex as well? this would still allow for current functionality, since specifying a full datastore name `/my-datastore1/`  in regex would match that datastore only. The results could then be sent into the `choose_datastore` function to pick the right LUN based on size.

**Comment by swalberg** [comment]
We do have the `maxfree` command at both the data store and data store cluster levels, which I believe do accept regex of explicitly called so the precedent is there (or could be used to chain a command). I think we'd have to be careful about that to avoid stuff like `myds` matching both `myds` and `myds2`, and what happens if multiple matches are returned. How do you think we should approach that?

**Comment by warroyo** [comment]
yea, myds and myds2 scenarios would be tricky. I guess another option would be to add a new parameter `--datastore-regex` that could be used in place of `--datastore` or `--datastorecluster`

As for handling multiple matches, I was thinking the `choose_datastore` function takes in an array of datastores and returns one back. So the results from the regex search could be passed into that function and the selected datastore could be used. 

I will take look at the `maxfree` commands. I think those will may meet my needs, they will just need to have the json formatting output added to them.  The main problem I am running into is that the LDAP login into VCenter seems to take up to 30 seconds so making multiple calls slows down the scripts significantly. So having the ability to select the datastore by regex in the `clone` would speed up the scripts.

**Comment by warroyo** [comment]
Looks like `maxfree` will work just fine. I have created a PR https://github.com/chef-partners/knife-vsphere/pull/341 to add the formatting option to the output as well as the ability to filter on cluster/pool.

**Comment by warroyo** [comment]
closing this issue since the `maxfree` command solves this problem
