### ISSUE TITLE
winrm user and winrm password switches are missing from Readme

### ISSUE THREAD

**Issue by vinyar** [chef-partners/knife-vsphere#344]
### What are you trying to do and what's not working?

attempting to clone a windows box without having to manually type the password.

Under bootstrap switches in the readme, I suggest adding -x & -P switches so users can create servers w/o any manual interaction.

**Comment by swalberg** [comment]
Hi, thanks for the bug report. Let me look into this!

Just so I'm clear, you're using winrm transport and not ssh? At first glance those switches are for SSH transport, but there's a few hacks in the code so it could very well be the same and I'm not seeing it.

**Comment by vinyar** [comment]
Hi, the switches are actually the same between `knife bootstrap` and `knife bootstrap windows winrm`

**Comment by swalberg** [comment]
Ah I was trying to find where they were set that way. The documents use the long form of this: `--ssh-user` and `--ssh-password`. I will update to include the short options.
