### ISSUE TITLE
Have a different VM name in the OS and in vCenter

### ISSUE THREAD

**Issue by joldham1023** [chef-partners/knife-vsphere#354]
### What are you trying to do and what's not working? 

Trying to change the name that appears in the OS. The challenge we have is with our non-windows machines (rhel and CentOS), we use the FQDN in the OS but only want to short name to appear in vcenter. I noticed the --fqdn switch, but also notice it is for bootstrapping. Is there a want to specify a different name within the OS similar to the way you can with the GUI? 

We do use cspec in our environment if that makes a difference.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information

knife vsphere vm clone SOMENAME -f some_folder --template some_template --ccpu 2 --cram 8 --cspec some_cspec --cips XX.XX.XX.XX/24 --cgw XX.XX.XX.XX --cdnsips XX.XX.XX.XX,XX.XX.XX.XX --datastore some_datastore --dest-folder some_folder --vsdc some_datacenter --start

```

### Other details, such as gem version and if you're working with a Linux or Windows VM

**Comment by swalberg** [comment]
Heya, I use `--chostname` to set the hostname, and you may also like `--cdomain` to set the domain part.

**Comment by joldham1023** [comment]
let me test this tomorrow to see if this will meet the needs for my team. Ill get back to you after I test it out.

**Comment by joldham1023** [comment]
@swalberg the --chostname and --cdomain worked for me, thanks you. I do have 1 more question about the --ctz (timezone) command; do you need to give an ssh username and password for it to set the value on rhel 6/7 or centos 6/7?

**Comment by swalberg** [comment]
Anything that starts with `c` goes into the customization spec, so it's done by the agent by vmware. The ssh username and password are for bootstrapping. So I'd expect you wouldn't need a password for the timezone.

**Comment by joldham1023** [comment]
@swalberg Have you tried using the --ctz option? I am able to get the other `c` options to work besides the time zone flag. Here is the snippet of code `--ctz 'US/Eastern'`.

**Comment by swalberg** [comment]
Hi, I don't use it. Just glanced at the code and it would appear it's never passed to vSphere! No wonder it doesn't work :(

**Comment by joldham1023** [comment]
well that explains it :)...We will just create a cookbook/recipe to control/set timezone. Thanks @swalberg
