### ISSUE TITLE
vm vncset wont find vm in folder

### ISSUE THREAD

**Issue by coda4096** [chef-partners/knife-vsphere#355]
### What are you trying to do and what's not working?
trying to enable vnc for a vm thats inside a folder

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
knife vsphere vm list -r

...
Folder: Replicas
	VM Name: SVR-AUBUN-VC01_replica
		IP: 
		RAM: 16384
		State: off
...

knife vsphere vm vncset SVR-AUBUN-VC01_replica --vnc-port <port> --vnc-password <password>

**VM SVR-AUBUN-VC01_replica not found**

```

### Other details, such as gem version and if you're working with a Linux or Windows VM

any vms in a folder

**Comment by coda4096** [comment]
Hi Sean

Do you think I should do a recursive vncset on vmname

`vms = get_vms(vmname)`

or use an optional  --folder option to specify the folder name?

```
base_folder = find_folder(get_config(:folder))

      vm = find_in_folder(base_folder, RbVmomi::VIM::VirtualMachine, vmname) || abort("VM #{vmname} not found")
```

**Comment by coda4096** [comment]
actually, using the --folder option works already

I did not know this.

**Comment by swalberg** [comment]
Hi Scott, glad you figured it out. `--folder` comes from the base class if memory serves, so many of the "find resource" functions support it. Not that clear from the code though, been something that's bothered me for a while.
