### ISSUE TITLE
Setting memory reservation

### ISSUE THREAD

**Issue by petericebear** [chef-partners/knife-vsphere#358]
### What are you trying to do and what's not working?
Im trying to set the memory reservation. You can set the ram with the option
--cram 4

I would like to set the memory reservation aswell. Maybe something like:
--cram_reservation 2

Can this be done?

**Comment by swalberg** [comment]
I think so... Look for `memoryAllocation` at the [Config Spec](https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.ConfigSpec.html) documentation. There are a [few things](https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.ResourceAllocationInfo.html) we can set in that structure. What would be helpful?

**Comment by petericebear** [comment]
Seems like the reservation can indeed be set with:
https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.ResourceAllocationInfo.html

Can it already be done with a featue of knife-vpshere (like something knife vsphere vm config set ... )?

**Comment by swalberg** [comment]
Not as-is, as `config` doesn't support nested attributes.

**Comment by petericebear** [comment]
This is now merged, can be closed?

**Comment by swalberg** [comment]
Yes, thanks for the reminder!
