### ISSUE TITLE
find_network method needs to be able to filter on cluster

### ISSUE THREAD

**Issue by warroyo** [chef-partners/knife-vsphere#360]
I have run into an issue where the `find_network` method returns an incorrect network if their are multiple port groups with the same name in different clusters.

I have multiple clusters with different Virtual Switches and the port groups inside of the switches have the same name. This issue arises when trying to run a clone when specifying a `host` and `cvlan`.  when the code reaches this step https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L503 , the`find_network` method will return the first item in the list if there are multiple matches, this is then compared against the host's available networks and it does not match causing the clone to fail. 

I think it would be a good option to have an option to pass `find_network` a cluster to limit its search to.

**Comment by swalberg** [comment]
We do have `--customization_sw_uuid` which lets you specify the switch it comes from, does that help?

**Comment by warroyo** [comment]
@swalberg ahh I missed that one, I think this will do the trick! I will give it a shot and close this issue if it solves the problem. thanks!

**Comment by swalberg** [comment]
Hi, did that help?

**Comment by warroyo** [comment]
Sorry about the delay. it ended up being a mistake in vcenter and was fixed there. so this issue can be closed

**Comment by swalberg** [comment]
Thank you!
