### ISSUE TITLE
vm vncset (BROKEN) for a VM that has multiple datastore folders 

### ISSUE THREAD

**Issue by coda4096** [chef-partners/knife-vsphere#362]
### What are you trying to do and what's not working?
vm vncset for a VM that has multiple datastore folders containing configs (.vmx)

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information
```
knife vsphere vm vncset
```
The command sort of works, the RemoteDisplay.vnc* settings are added to the .vmx file BUT in the wrong folder for a VM

### Other details, such as gem version and if you're working with a Linux or Windows VM

A VM replica (created by Veeam software) seems to create a new folder on the datastore whenever the vm config (or something?) changes.

ie. the datastore might contain multiple configs in multiple folders like this:

VM_Name
VM_Name_1
VM_Name_2
VM_Name_3
VM_Name_4

The VM seems to be using the .vmx etc in the largest numbered (newest) folder BUT the chef command updates the vmx in the (oldest) non-numbered folder.

**Comment by coda4096** [comment]
these lines seem to select and update the incorrect config

`  extra_config, = vm.collect('config.extraConfig')

    vm.ReconfigVM_Task(
      spec: {
        extraConfig: [
          { key: 'RemoteDisplay.vnc.enabled', value: 'true' },
          { key: 'RemoteDisplay.vnc.port', value: config[:vnc_port].to_s },
          { key: 'RemoteDisplay.vnc.password', value: config[:vnc_password].to_s }
        ]
      }
    ).wait_for_completion

    puts extra_config.detect { |x| 'RemoteDisplay.vnc.enabled'.casecmp(x.key) && 'true'.casecmp(x.value.downcase) }
`

**Comment by swalberg** [comment]
Those lines first save the existing extra config, then takes the chosen VM and asks VMWare to make those changes. I don't see in the docs or our code where we're able to set where the config file is -- we're basically telling VMWare to update the config file on its own.

Can you try `--folder VM_Name_4` which might force us to pick the right folder? Maybe also attach some screenshots showing the structure you're talking about? I may have to run this by someone at VMWare...
