### ISSUE TITLE
Windows VM Clone timeout waiting for sysprep

### ISSUE THREAD

**Issue by gazataeon** [chef-partners/knife-vsphere#369]
### Versions:

* Version of knife-vsphere: knife-vsphere-1.2.26
* Version of chef: azure automate 0.7.239

### Platform Details

* Version of vSphere: 5.5
* Version of ESXi: 5.5

### Scenario:
Clone and bootstrap a windows VM

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:
knife vsphere vm clone xxxxxxxxxxxxxxxxxxxxxxxx --template Win2012R2-Chef -f Templates \ --bootstrap --dest-folder UAT/Chef-Deploy --cspec webhost-af --run-list role[webserver_es_dev] --sysprep_timeout 1000 -VV
INFO: Using configuration from xxxxxxxxxxxxxxxxxxxxxxxx/chef-repo/.chef/knife.rb
DEBUG: value for config item datastore:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item chef_node_name:
DEBUG: value for config item vsphere_host: xxxxxxxxxxxxxxxxxxxxxxxx
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: xxxxxxxxxxxxxxxxxxxxxxxx
DEBUG: value for config item vsphere_pass: xxxxxxxxxxxxxxxxxxxxxxxx
DEBUG: value for config item vsphere_pass: xxxxxxxxxxxxxxxxxxxxxxxx
DEBUG: value for config item vsphere_pass: xxxxxxxxxxxxxxxxxxxxxxxx
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: xxxxxxxxxxxxxxxxxxxxxxxx
DEBUG: value for config item folder: Templates
DEBUG: value for config item vsphere_dc: xxxxxxxxxxxxxxxxxxxxxxxx
DEBUG: value for config item linked_clone:
DEBUG: value for config item host:
DEBUG: value for config item resource_pool:
DEBUG: value for config item vsphere_dc: xxxxxxxxxxxxxxxxxxxxxxxx
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount:
DEBUG: value for config item customization_corespersocket:
DEBUG: value for config item customization_memory:
DEBUG: value for config item customization_memory_reservation:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item customization_ips:
DEBUG: value for config item customization_sw_uuid:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item customization_spec: webhost-af
DEBUG: value for config item customization_spec: webhost-af
DEBUG: value for config item disable_customization: false
DEBUG: value for config item customization_dns_ips:
DEBUG: value for config item customization_dns_suffixes:
DEBUG: value for config item customization_domain:
DEBUG: value for config item customization_plugin:
DEBUG: value for config item vsphere_dc: xxxxxxxxxxxxxxxxxxxxxxxx
Cloning template Win2012R2-Chef to new VM xxxxxxxxxxxxxxxxxxxxxxxx
VirtualMachineCloneSpec(OMITTED FOR FORMAT SAKE!)
Finished creating virtual machine xxxxxxxxxxxxxxx
DEBUG: value for config item customization_plugin:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item power:
DEBUG: value for config item bootstrap: true
Powered on virtual machine xxxxxxxxxxxxxxxxxx
DEBUG: value for config item bootstrap: true
Waiting for network interfaces to become available...
Found address 192.168.50.253
DEBUG: value for config item bootstrap_nic: 0
DEBUG: Connect Host for Bootstrap: 192.168.50.253
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item bootstrap_protocol:
DEBUG: Identified os as windows.
Waiting for customization to complete...
DEBUG: value for config item sysprep_timeout: 1000
Waiting for sysprep...................................................
Customization of VM xxxxxxxxxxxxxxxxxx not succeeded within 1000 seconds.

### Expected Result:
I guess a cloned and bootstrapped VM showing up in the Nodes list

### Actual Result:
Time out when waiting for the sysprep to finish.  Not sure what specifically it's waiting for but visually it seems to be done and sat at the desktop following the automated install.

**Comment by swalberg** [comment]
Hi, thanks for the output of `-VV`. Seems like we're not detecting that sysprep is done.

[The code](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/customization_helper.rb#L45-L50) looks through the events on the VM to see if it recognizes that it's done. Are you able to look at the events on the VM to see if something different has fired?

**Comment by gazataeon** [comment]
Hmm,
It does seem that it boots once using the static IP assigned and we get the .253 address, but then after the 2nd reboot it reverts to DHCP. 

```
Powered on virtual machine hostname
DEBUG: value for config item bootstrap: true
Waiting for network interfaces to become available...
Found address 192.168.50.253
DEBUG: value for config item bootstrap_nic: 0
DEBUG: Connect Host for Bootstrap: 192.168.50.253
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item bootstrap_protocol:
DEBUG: Identified os as windows.
Waiting for customization to complete...
DEBUG: value for config item sysprep_timeout: 1000
Waiting for sysprep........................................................
Customization of VM hostname not succeeded within 1000 seconds.
```

I'm going to try using  --cips 192.168.50.253/24 --cgw 192.168.50.1, the unattended.xml file does set to static IP, but perhaps it needs it here too?


(also thank you for the quick reply!)

**Comment by gazataeon** [comment]
Okay still not luck. I wonder am I missing something that I should be doing to have a Windows VM be picked up by this? Should I be passing log on credentials for knife-vsphere to be using to bootstrap/check logs?

**Comment by gazataeon** [comment]
Have a work around for this now. 
I gave the template the static ip, then let it bootstrap fully and then later change to DHCP.
