### ISSUE TITLE
vm clone picks up IP before Windows sysprep

### ISSUE THREAD

**Issue by talcloudshare** [chef-partners/knife-vsphere#372]
### Versions:

* Version of knife-vsphere: 1.2.26
* Version of chef: 12.17.44

### Platform Details

* Version of vSphere: 6.5.0 Build 4602587
* Version of ESXi:

### Scenario:
When running vm clone with bootstrap, for a Windows VM, IP for bootstrapping is determined before running sysprep (lib/chef/knife/vsphere_vm_clone.rb:395)

I would expect the command to first wait for sysprep to complete before determining the IP for bootstrap (in my case, IP is altered during sysprep)

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:

```
knife vsphere vm clone ****** --vsdc ****** --vshost ****** --vsinsecure true --vsuser **** --vspass **** --datastore ****** --resource-pool ****** --dest-folder ****** --folder ****** --template ****** --cspec knife-vsphere-plugin --ccpu 1 --cram 1 --cdomain ****** --cgw ****** --cdnsips ****** --cdnssuffix ****** --chostname CloudIIS-K --cvlan ****** --cips x.x.x.82/16 --cmacs auto --sw-uuid auto --bootstrap --environment ****** --bootstrap-version 12.14.89 --run-list ****** --node-name ****** --bootstrap-protocol winrm --winrm-user **** --winrm-password **** --bootstrap-ipv4 --sysprep_timeout 1200 -VV
```

### Expected Result:

VM cloned, Chef bootstrap running properly

### Actual Result:

```
Finished creating virtual machine ******
DEBUG: value for config item customization_plugin: 
DEBUG: value for config item mark_as_template: 
DEBUG: value for config item power: 
DEBUG: value for config item bootstrap: true
Powered on virtual machine ******
DEBUG: value for config item bootstrap: true
Waiting for network interfaces to become available...
Found address x.x.x.78
Waiting for a valid IPv4 address...
DEBUG: value for config item bootstrap_nic: 0
DEBUG: value for config item bootstrap_nic: 0
DEBUG: Connect Host for Bootstrap: x.x.x.78
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item bootstrap_protocol: winrm
DEBUG: Identified os as windows.
Waiting for customization to complete...
DEBUG: value for config item sysprep_timeout: 1200
Waiting for sysprep............................
Customization of VM ****** succeeded. Customization log located at C:/Windows/TEMP/vmware-imc/guestcust.log in the guest OS.
Customization Complete
DEBUG: value for config item winrm_transport: plaintext
DEBUG: value for config item winrm_port: 5985
```

Then run is stuck (as IP was altered to x.x.x.82 as mentioned in knife command)

**Comment by swalberg** [comment]
Ah, interesting. I see https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L395 saves the host before the sysprep is done. Definitely a problem.

**Comment by swalberg** [comment]
Tal, any chance you could pull down my branch in #374 and see if it fixes this problem?

**Comment by talcloudshare** [comment]
Fixed the issue, thanks!

**Comment by swalberg** [comment]
Thanks! I'll cut a release tomorrow with this in it.
