### ISSUE TITLE
Issue Bootstraping with --bootstap. 

### ISSUE THREAD

**Issue by DMEvanCT** [chef-partners/knife-vsphere#379]
### Versions:

* Version of knife-vsphere: Newest
* Version of chef: 12.21.2

### Platform Details

* Version of vSphere: 5.5
* Version of ESXi: HP-ESXi-5.1.0

### Scenario:
Trying to clone and bootstrap a machine to my chef server. 
knife vsphere vm clone Devops-01 --template CentOS-Updated-Temp \ --cips 10.1.0.44/24 \ --chostname Devops-01 --cdomain Devops-01 --ssh-user (hidden) -P (Hidden) --bootstrap --chostname Devops-01 --cdomain cssi.clarityssi.com

### Expected Result:
The machine should have bootstraped. 

### Actual Result:
 [sudo] password for (Hidden): -----> Installing Chef Omnibus (-v 12)
 downloading https://omnitruck-direct.chef.io/chef/install.sh
   to file /tmp/install.sh.2206/install.sh
 trying wget...
 trying curl...
 trying perl...
 trying python...
 >>>>>> wget, curl, fetch, perl, or python not found on this instance.
 \nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2017-07-22 12:16:35--  https://omnitruck-direct.chef.io/chef/install.sh
 Resolving omnitruck-direct.chef.io (omnitruck-direct.chef.io)... failed: Name or service not known.
 wget: unable to resolve host address ‘omnitruck-direct.chef.io’\n\nSTDERR from curl:\n\n\n\nSTDERR from perl:\n\nCan't locate LWP/Simple.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 1.
 BEGIN failed--compilation aborted at -e line 1.\n\nSTDERR from python:\n\nTraceback (most recent call last):
   File "<string>", line 1, in <module>
   File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
     return opener.open(url, data, timeout)
   File "/usr/lib64/python2.7/urllib2.py", line 431, in open
     response = self._open(req, data)
   File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
     '_open', req)
   File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
     result = func(*args)
   File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
     context=self._context, check_hostname=self._check_hostname)
   File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
     raise URLError(err)
 urllib2.URLError: <urlopen error [Errno -2] Name or service not known>\n
 Starting the first Chef Client run...

**Comment by swalberg** [comment]
Hi, I'm out of pocket for a few days but I think you either need to set a DNS server or make sure your template has wget, curl, or one of the other listed tools. --cdns I think for DNS. Your vm isn't able to download the chef client. 

Sean

**Comment by DMEvanCT** [comment]
so would it be --cdns 8.8.8.8 as an example?

**Comment by swalberg** [comment]
Yea though I was wrong, it's --cdnsips. 

Sean

**Comment by DMEvanCT** [comment]
Perfect! It picked it up right away when specifying the DNS. Another question when doing the --run-list how do I specify role over recipe?

**Comment by swalberg** [comment]
Excellent! It's 'role[foo]' as opposed to 'recipe[foo]' and it can be comma separated just like when you do it from knife.

**Comment by DMEvanCT** [comment]
Quick question for you. If I have 2 nics one for SAN one for network eth0, eth1 how do I specify which IP address for what

**Comment by swalberg** [comment]
`--cips ip1,ip2` where an ip can be `x.x.x.x/y` or `dhcp`.

**Comment by swalberg** [comment]
Oh, and if one is non routable and it happens to be the first `--bootstrap-nic` lets you pick the nic we bootstrap against.
