### ISSUE TITLE
knife vsphere execute example

### ISSUE THREAD

**Issue by amitseth7** [chef-partners/knife-vsphere#382]
### Versions:

* Version of knife-vsphere: latest
* Version of chef: 12.19.36

### Platform Details

* Version of vSphere: 6.0
* Version of ESXi: 6.0

### Scenario:

amitseth@~/chef-repo/rti-app-cookbooks: knife vsphere vm execute hostname-name "/bin/cat /etc/hosts" -f "Development/Miscellaneous" --exec-user root --exec-passwd "xxx&yyyyy" -VV

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:

INFO: Using configuration from /zzzz/knife.rb
DEBUG: value for config item vsphere_host: 
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl: 
DEBUG: value for config item vsphere_user: 
DEBUG: value for config item vsphere_pass: 
Enter your password: 
DEBUG: value for config item vsphere_insecure: 
DEBUG: value for config item proxy_host: 
DEBUG: value for config item proxy_port: 
/Users/amitseth/.chefdk/gem/ruby/2.3.0/gems/rbvmomi-1.9.5/lib/rbvmomi/vim.rb:32:in `connect': host option required (RuntimeError)
	from /Users/amitseth/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.25/lib/chef/knife/base_vsphere_command.rb:117:in `vim_connection'
	from /Users/amitseth/.chefdk/gem/ruby/2.3.0/gems/knife-vsphere-1.2.25/lib/chef/knife/vsphere_vm_execute.rb:44:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:57:in `load'
	from /opt/chefdk/bin/knife:57:in `<main>'

### Expected Result:

I am trying to execute a command on the guest machine, using vsphere. Unable to do so . Can somebody point out a sample command.

**Comment by swalberg** [comment]
Hi, this command is somewhat limited. The output isn't passed back, personally I really only use it to run chef on a node that I can't reach or to turn off the firewall when I've really messed things up.

```knife vsphere vm execute SERVERNAME  --exec-user root --exec-passwd rootpassword -- /bin/foo -bar``` is how I use it.

**Comment by amitseth7** [comment]
that is weird, It doesnot understand arguments to any binary . A simple echo failed for me

amitseth@~/xx: knife vsphere vm execute hostname  -f "Development/Miscellaneous" --exec-user root --exec-passwd "rootpass" -- "/bin/echo 'help'"
ERROR: RbVmomi::Fault: FileNotFound: File /bin/echo 'help' was not found

**Comment by swalberg** [comment]
Try it without the quotes -- we have to pass args separately to the API. `"foo 'bar'"` literally tries to run a file called `foo 'bar'`. You want `foo 'bar'` if that makes sense.

**Comment by amitseth7** [comment]
Thank you for this. It does make sense. However when i am writing to a file on the guest vm , thats when I get bumped. 

I am trying to set the interfaces for my cloned VM.  Trying to write to /etc/network/interfaces using this , 
knife vsphere vm execute SERVERNAME --exec-user root --exec-passwd rootpassword  /bin/echo 'blah >' /etc/network/interfaces

That doesnot do anything. Any suggestions.

**Comment by swalberg** [comment]
Hm, that might be difficult. Redirections aren't really arguments to a command, they're things the shell does. I wonder if running `/bin/bash -c "/bin/echo 'blah' > /etc/network/interfaces"` might work? You'd be passing two arguments to bash... first is `-c` the second is the command you want bash to run.

Just curious if you need to do it this way? Typically this plugin will set the proper IPs when customizing the VM during the clone (`--cips`), or you're using something like Chef to manage the file.

**Comment by amitseth7** [comment]
the problem with cips is it only sets the /etc/hosts file , not the interfaces, if I want to set a static eth0, netmask, gateway, etc .

I am trying to set network config on clone. Do you have a better way to do this

**Comment by swalberg** [comment]
You mean it's not setting the interface IP? Or is there a different setting it's missing? The `--cips` command should set the right IP on the interface, and once the node has booted for the first time, should be reachable. If not there's usually a problem with the template or the way people are calling the clone command.

Can you give me the command you're running to clone, please? And what distro of Linux are you running?

Couple of things to check, too:
* Is the template configured to start vmware tools on boot?
* Is the template set with the right distribution name?
* There are a few files to wipe out if they exist (this is for Ubuntu: http://everythingshouldbevirtual.com/ubuntu-vmware-template-cleanup-script)

Thanks.

**Comment by amitseth7** [comment]
I see your point , I was using CentOS_6.7_v1.0.1 template with ethernet configurations in /etc/sysconfig/network-scripts . 

i verified cips and cgw works. 

knife vsphere vm clone servername --folder 'Templates' --dest-folder 'Development/Miscellaneous' --template 'CentOS_6.7_v1.0.1' --datastore VP2_Windows_Production_01 --chostname servername --cips 17.179.176.2/24 --cgw 17.179.176.1

**Comment by nkichukov** [comment]
> Hm, that might be difficult. Redirections aren't really arguments to a command, they're things the shell does. I wonder if running `/bin/bash -c "/bin/echo 'blah' > /etc/network/interfaces"` might work? You'd be passing two arguments to bash... first is `-c` the second is the command you want bash to run.
>...

For completeness, there is how this redirect worked for me:

`knife vsphere vm execute VM1 --exec-user root --exec-passwd ROOTPWD -f 'Location' /bin/bash -- "-c 'echo \"it works\" > /tmp/tesme'"`
