### ISSUE TITLE
Using knife-vsphere can you create multiple VMs simultaneously from a single template? 

### ISSUE THREAD

**Issue by kleidhyseni** [chef-partners/knife-vsphere#391]
### Versions:
Chef Development Kit Version: 2.0.26
chef-client version: 13.2.20
knife-vsphere version: 2.0.1

### Platform Details
Version of vSphere: 6.0
Version of ESXi: 6.0

### Scenario:
I am able to clone and configure a new VM from a single template using specifications from a --cplugin file. Using knife-vsphere can I create multiple VMs simultaneously from a single template?

**Comment by swalberg** [comment]
Hi, no, not from a single command line at least. You can use some kind of shell loop to run a bunch in the background if you want. There's also the [`chef-provisioning-vsphere`](https://github.com/chef-partners/chef-provisioning-vsphere) gem that's made to generate multiple VMs if that would be helpful.

**Comment by jjasghar** [comment]
Took the words right out of my mouth @swalberg. Please reopen this if you have anymore questions relevant to this :)
