### ISSUE TITLE
knife vsphere vm config is undocumented

### ISSUE THREAD

**Issue by petericebear** [chef-partners/knife-vsphere#394]
Hi,

How can you update the VM RAM or CPU on a existing VM?
Am I overlooking something?

Greetings,
Peter

**Comment by swalberg** [comment]
Yea, it's in the undocumented [knife vsphere vm config](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_config.rb) command. Going to hijack your issue to get that in the plan.
