### ISSUE TITLE
Vm clone dest-folder no such folder

### ISSUE THREAD

**Issue by diegobill** [chef-partners/knife-vsphere#395]
### Versions:

* Version of knife-vsphere: knife-vsphere-2.0.1
* Version of chef: gem install -V chef -v 12.4.3
$ chef --version
Chef Development Kit Version: 0.8.0
chef-client version: ERROR
berks version: 3.3.0
kitchen version: 1.4.2

### Platform Details

* Version of vSphere: vmware vcenter server version 6.0.0 build 2776510
* Version of ESXi: 

### Scenario:

I am trying to clone a vm to a dest-folder because I do not have permission to clone to root but I receive "no such folder"

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:

```
knife vsphere vm clone citex_prod_pacificadorTreinamento \
                       -VV \
                       --cips IP \
                       --cgw GW \
                       --cdnsips DNS \
                       --cvlan DMZ  \
                       --template template \
                       --datastorecluster CLUSTERDATA \
                       --resource-pool CLUSTER \
                       --bootstrap true \
                       --chostname ABC \
                       --distro chef-full \
                       --run-list 'role[role]' \
                       --ccpu 8 \
                       --cram 8 \
                       --node-name NODENAME
                       --dest-folder 'vm/AAA/BBB/CCC'
```

When I list folders:
```
$ knife vsphere folder list
 Folder: vm
   Folder: AAA
     Folder: BBB
       Folder: CCC
```

### Expected Result:

clone vm correctly

### Actual Result:

I receive message no such folder "vm/AAA/BBB/CCC"

**Comment by swalberg** [comment]
Hmmm... Is that the complete error message? It should say something like "while looking for XXX" indicating which level the search failed at.

**Comment by diegobill** [comment]
It failed in the First level : "while looking for VM".

What is the correct way to pass dest folder considering my "knife vsphere folder list"?

**Comment by swalberg** [comment]
I don't use folders myself, but what I see when I run it is the top level `vm`, too, and we're basically using the same methods to enumerate folders as to find them. So try `AAA/BBB/CCC` instead of starting with `vm` and let's see how that goes...

**Comment by swalberg** [comment]
Did this ever get fixed? Looking now I don't know that it's supposed to start with `vm/` as that's an internal folder name we try and hide. I've also made a bunch of updates to the way folders work in the latest version, so please try that.
