### ISSUE TITLE
VM_Clone --tag does not apply tags

### ISSUE THREAD

**Issue by benpoliquin** [chef-partners/knife-vsphere#398]
### Versions:
* Version of knife-vsphere: v2.0.1

### Platform Details
* Version of vSphere: v6.0

### Scenario:

When using the --tag option when cloning a VM, no tag is assigned. The tags being used are preexisting and can be assigned manually. 

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:
'... --tags='Prod_Backup' ...'

### Expected Result:
Assign tags to the cloned VM

### Actual Result:
No tags are assigned

**Comment by swalberg** [comment]
Hi Ben, can you try it with `--tags` (plural), and let me know, please?

**Comment by benpoliquin** [comment]
whoops, in the report I used tag. I have tried both tags and tag and it does not seem to do anything for me. When I test other options such as --annotate, that works.

**Comment by swalberg** [comment]
Can you double check you're not accidentally calling a version that predates support for `--tags`?

```
$ knife vsphere vm clone | grep tags
FATAL: You must specify a virtual machine name OR use --random-vmname
        --tags TAGS                  Comma separated list of tags to apply to the node
```

**Comment by benpoliquin** [comment]
Double checked. I am using the current version and received the same output as you

**Comment by swalberg** [comment]
hm, I will have to try it out here. I created a bunch of VMs earlier this week with tags and it worked fine, though I see I'm using 2.0.0.

**Comment by swalberg** [comment]
Oh... When you say "no tags are assigned" to the VM, are you talking about tags in vsphere or in Chef? The `--tags` option tags the node within Chef during the bootstrapping. This gem currently can't tag a node within vsphere, since that's not accessible through the SOAP API.

I thought we have an issue open for this but I can't find it.

**Comment by benpoliquin** [comment]
I am talking about tags in vsphere. Thank you for clarifying this! That makes much more sense it is for Chef.

**Comment by swalberg** [comment]
Yea, sorry about the confusion. I'd happily add the functionality to the gem but so far it looks like a large task.
