### ISSUE TITLE
--bootstrap-msi-

### ISSUE THREAD

**Issue by dheeraj86mathur** [chef-partners/knife-vsphere#401]
### Versions:

* Version of knife-vsphere: knife-vsphere (2.0.0)
* Version of chef: 
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

### Platform Details

* Version of vSphere: 5.5
* Version of ESXi:

### Scenario:

I have chef client and other chef rpm located on a nfs mount. I am trying to use knife vsphere to build and then bootstrap new VMs. Is there any option to provide nfs paths with --bootstrap. Since my organization isolates linux/window machines from external network, I need to keep rpm locally on a nfs server or in pulp repo.

**Comment by swalberg** [comment]
Hi, no, file paths won't work, but we do support `--bootstrap-msi-url` to pass a URI which you could point to your repo.

**Comment by dheeraj86mathur** [comment]
Hi, 
Do I need to both --bootstrap and --bootstrap-msi-url together or only --bootstrap-msi-url. 
As I understand --bootstrap downloads and execute install.sh , that will inture download the rpm and will install it. After that the actual "knife bootstrap" step will be executed. When bootstrap gets executed, and it uses user given in --ssh-user, how can I specify sudo ? Normally when we do bootstrap, we use --sudo, to specify that user will be using sudo.

**Comment by dheeraj86mathur** [comment]
I think --bootstrap-msi-url  doesnt works for Linux VM builds. Is there any other option for Linux machines ?

**Comment by swalberg** [comment]
Hi, the `msi` options are only for Windows, and yes, you'll need `--bootstrap` in any case.

Sudo will be automagically enabled if your `ssh_user` is not `root`.

Linux bootstrapping without an Internet connection is a bit different. Have a look at [custom templates](https://docs.chef.io/knife_bootstrap.html) and the `--distro` option. I've never used this option myself but might be able to help out if you get stuck. This feels like something we should be doing a better job on.

If it is a possibility, there's also `--bootstrap-proxy` that will point your node at a proxy server to get to the Internet.
