### ISSUE TITLE
Kickstart support?

### ISSUE THREAD

**Issue by Routhinator** [chef-partners/knife-vsphere#402]
Hi,

Is there anyway to use this in concert with a Kickstart server? I'd like to move away from templates. 

Thought was that this could work with kickstart like this:

- knife-vsphere creates new vm and retrieves the MAC address of the primary adapter
- knife-vsphere feeds base OS, mac address, ip, hostname, and initial package requirements into Kickstart
- knife-vsphere boots VM
- kickstart installs the OS and starts the VM
- knife-vsphere waits for the VM to be started as it does with the clone procedure, and then continues on to the chef bootstrap and runlist.

Is this currently possible or has anyone looked at it? Based on some testing I've done, the kickstart installation process takes about 1/3rd of the time as the clone process in VMWare, which would speed this up considerably.

**Comment by swalberg** [comment]
Hi there, no, not that I know of. This plugin assumes you're cloning a template and communicates with the vsphere agent on the booted server to find the IP. 

Really surprised to hear of your measurements. I clone 16GB images over NFS (e.g. no SAN offloading) and they maybe take a minute or two.

**Comment by jjasghar** [comment]
Hi! There's a chance here that PowerCLI might be a better tool for this job. I'm gonna forward this off to Jack Robinson for his advice here. I would /cc him, but i actually don't know his github handle.

**Comment by swalberg** [comment]
Closing this issue as it seems it's being taken care of outside this channel.
