### ISSUE TITLE
Unable to extend the disk using knife vsphere extend vm disk command

### ISSUE THREAD

**Issue by jithendrakumarak** [chef-partners/knife-vsphere#409]
### Versions:

* Version of knife-vsphere:2.0.1
* Version of chef:2.4.17

### Platform Details

* Version of vSphere:6.0.0
* Version of ESXi:

### Scenario:

I have created an extended disk for a vm using command "knife vsphere vm vmdk add -f /Infrastructure oraclenode 50", but i am not able to extend the same disk using the command "knife vsphere vm disk extend -f /Infrastructure oraclenode --diskname "Hard disk 1" 62914560

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:

It Gives me the following error when i tried to extend the disk

knife vsphere vm disk extend -f /Infrastructure oraclenode --diskname "Hard disk 1" 62914560

ERROR: RbVmomi::Fault: InvalidRequest: 
Single property sharing provided multiple times

while parsing property "sharing" of static type string

while parsing serialized DataObject of type vim.vm.device.VirtualDisk.FlatVer2BackingInfo
at line 1, column 525

while parsing property "backing" of static type VirtualDeviceBackingInfo

while parsing serialized DataObject of type vim.vm.device.VirtualDisk
at line 1, column 373

while parsing property "device" of static type VirtualDevice

while parsing serialized DataObject of type vim.vm.device.VirtualDeviceSpec
at line 1, column 297

while parsing property "deviceChange" of static type ArrayOfVirtualDeviceConfigSpec

while parsing serialized DataObject of type vim.vm.ConfigSpec
at line 1, column 255

while parsing call information for method ReconfigVM_Task
at line 1, column 177

while parsing SOAP body
at line 1, column 167

while parsing SOAP envelope
at line 1, column 0

while parsing HTTP request for method reconfigure
on object of type vim.VirtualMachine
at line 1, column 0

### Expected Result:

I need to extend the extended disk

**Comment by swalberg** [comment]
Hm. Is that the entirety of the output? Can you run it with `-VV`, strip out passwords, and paste it here?

**Comment by swalberg** [comment]
Closing some stale issues. If you still need help please feel free to re-open this, or start a new issue! Thanks.
