### ISSUE TITLE
How to use knife vSphere in jenkins

### ISSUE THREAD

**Issue by jithendrakumarak** [chef-partners/knife-vsphere#410]
I can use the knife commands in the execute shell build jobs in jenkins(by installing chef integration plugin). My question here is, in a similar way, how to integrate knife vSphere in jenkins for use by chef plugin?

**Comment by swalberg** [comment]
Typically you'll install the `knife-vsphere` plugin on Jenkins and run the commands from within a shell build job. I'm not familiar with the chef plugin, but if it's running a `knife` command, it'll work with this gem as long as the gem is installed.

**Comment by swalberg** [comment]
Going to close this, but please do re-open if you're still having problems.
