### ISSUE TITLE
knife vsphere vm clone --bootstrap supplies wrong IP to bootstrap!

### ISSUE THREAD

**Issue by bby-bishopclark** [chef-partners/knife-vsphere#412]
### Versions:
* Version of knife-vsphere: 2.0.1
* Version of chef: 13.6.4

### Platform Details
* Version of vSphere: 6.5.0.13000
* Version of ESXi: 6.5.0

### Scenario:
knife vsphere vm clone --bootstrap

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:
cd ~/chef-repo/knife/prod/; \
VM=prdjumpbox05; \
knife vsphere vm delete -P $VM; \
knife vsphere vm clone $VM -N $VM --chostname $VM \
--start --bootstrap -x provision -P provision \
--template centos7-01-prd -f Templates \
--cips 10.0.8.48/24 --cvlan 'Lab4' --cgw 10.0.8.1 --node-ssl-verify-mode none
Deleted virtual machine prdjumpbox05
Deleted node prdjumpbox05
Deleted client prdjumpbox05
Cloning template centos7-01-prd to new VM prdjumpbox05
Finished creating virtual machine prdjumpbox05
Powered on virtual machine prdjumpbox05
Waiting for network interfaces to become available...

Waiting for sshd access to become available on 10.3.18.47:22done
Creating new client for prdjumpbox05
Creating new node for prdjumpbox05
Connecting to 10.3.18.47
10.3.18.47
10.3.18.47 Starting the first Chef Client run...
10.3.18.47 Starting Chef Client, version 13.6.4
10.3.18.47 resolving cookbooks for run list: []
:
:

### Expected Result:
I'm expecting the bootstrap to use the supplied IP to register the client profile AND bootstrap.

### Actual Result:
You see how it's using a completely different IP?  That's the weeeird part.  

The VM itself *gets the new IP* as it should.  Suddenly, though, the bootstrap is using an IP (which may be on the pre-customization template), but AFTER fixing it to the new IP.  

The host at 10.3.18.47 is kinda pissed now, as it was a temporary box to test something else.  No fun!  ;-)

**Comment by swalberg** [comment]
Hey there, we're using the IP that's reported by the agent. Does this box have two nics by chance?

**Comment by swalberg** [comment]
Other thing you can try is the `--fqdn` option which will let you hit it on an fqdn that resolves to the address you want. But I think passing an IP address will cause problems with customization.

**Comment by swalberg** [comment]
Last comment, the template itself shouldn't have any IPs on it. I usually delete any kind of NIC config and let VMWare sort it out during customization.

**Comment by bby-bishopclark** [comment]
Nope.  One NIC only

In the --fqdn, I'm supplying the --chostname info glued to --cdomain info?  I forgot to mention - bad me! - that --cdomain and --cdnsips are pulled in with cores/cores-per-cpu, memory, datastore, dest-folder, resource_pool (and vsphere host and auth creds, etc) .  

When I rip out the /etc/sysconfig/network-scripts/ifcfg-eth0, it haaates it.  Are you saying I should vape the IPADDR/NETMASK/GATEWAY lines in there and try more?

**Comment by swalberg** [comment]
https://github.com/chef-partners/knife-vsphere/wiki/Making-a-template-for-cloning has a few things to check on the template. What do you mean by “it hates it”? Deleting that file is one of the things I do on my templates.  Is Perl installed and vmtools set to start on boot?

Sean

**Comment by bby-bishopclark** [comment]
I must be really losing it, then.  When I delete the file (under centos7 or centos6+open-vm-tools), the customization always fails.

Let's look at that a little later.

I have an update.  Maybe, MAYBE, the sudden failures are due to one  ESXi host coming online after the patch run, and as the newest it ends up being the quietest, which makes it very tasty to the placement algorithm in DRM.  It's still got standard switches, and _it may be missing the vLAN we need_ .  (yes, that's why we hate standard switches, and I know we need them, but it's not in my portfolio to hasten that fix) 

1. What happens in such a case where we vm-clone and the dest ESXi host doesn't have the vLAN or DS we need?  Could it not care, and clone to that host anyway?  Is this possible that rbvmomi doesn't check and bail with an error when the DS or vLAN is missing at the destination?

1. If it DOES clone onto a host without the vLAN it needs, can the customization where it edits the ifcfg template actually fail too?  (not just the connecting to the missing vLAN, but also modding that config file)

1. and then, if it does both - clone to a host without the vLAN it needs, fail to mod the ifcfg so it's got the old values, is it reporting that back to the chef node creation step, so that when it hammers the victim's sshd waiting for the port to open, could that be how it's getting the old/wrong IP?

I'll try to re-create the situation where cloning a template with no ifcfg file gets me that haaating situation tomorrow;  my notes just say "this doesn't work; leave something there" .

**Comment by swalberg** [comment]
Hm. I don't know the inner workings of vsphere to that level. When we're building the customization spec, though, we filter out hosts that don't have the vlan.

Let's try working through your no-ifcfg file thing. Things are a lot easier if the template is set up correctly.

**Comment by bby-bishopclark** [comment]
(stared at this all day, putting out other fires. Now OoO to 1/23; will peel the ifcfg off, test, and edit this comment then)

**Comment by bby-bishopclark** [comment]
Yeah.  Freakin' perl was missing.  Who knew?  

Filed a ticket with RHBZ to handle the packaging glitch, so it's not a time-bomb for anyone else.  It ended up being a dupe of RHBZ 1358108 , so at least it's in the queue.

I'm fixed.   Kronos grant me the time to get packer packing my templates and I'll be perfect.

Thanks for your time.  Sorry it wasn't better spent!  :-/

**Comment by swalberg** [comment]
Nah, it's all good. It'll help people with the same problem that otherwise wouldn't have opened an issue. Thanks for the follow up.
