### ISSUE TITLE
--cspec is applying custom specification values that are not defined in vCenter's customization specification manager

### ISSUE THREAD

**Issue by Zorrom** [chef-partners/knife-vsphere#419]
### Versions:

* Version of knife-vsphere: 2.0.1
* Version of chef: 12.19.36

### Platform Details

* Version of vSphere: 6.5.0
* Version of ESXi: 6.5.0

### Scenario:

I am trying to spin a VM using the following command

`knife vsphere vm clone testVM4 --dest-folder Chef_Test --template TEST_TMPT --start --datastore my_datastore --cips 10.10.10.1 --cspec winspec `

The scenario is that the VM has to take the IP address value from --cips and the rest of the values such as subnet mask , default gateway, DNS settings has to be taken from the --cspec which is holding the customization specification manager. 
But the VM is getting built with the Ip address passed in --cips but thedefault gateway and the subnet mask values are a random values that are never a part of the customization specification manager.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:
```
[root@chefworkstation .chef]# knife vsphere vm clone testVM4 --dest-folder Chef_Test --template TEST_TMPT --start --datastore my_datastore --cips 10.10.10.1 --cspec winspec -VV
Cloning template TEST_TMPT to new VM testVM4
VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec( deviceChange: [] ),
  customization: CustomizationSpec(
    encryptionKey: [48,
     *
     * # Too many number were here, removing them to make the thread smaller
     *
     *
     30],
    globalIPSettings: CustomizationGlobalIPSettings(
      dnsServerList: [],
      dnsSuffixList: []
    ),
    identity: CustomizationSysprep(
      guiRunOnce: CustomizationGuiRunOnce(
        commandList: ["net stop myservice",
         "reg delete my_reg_key"]
      ),
      guiUnattended: CustomizationGuiUnattended(
        autoLogon: true,
        autoLogonCount: 1,
        password: CustomizationPassword(
          plainText: false,
          value: " xxx"
        ),
        timeZone: 33
      ),
      identification: CustomizationIdentification( joinWorkgroup: "WORKGROUP"
      ),
      userData: CustomizationUserData(
        computerName: CustomizationVirtualMachineName(  ),
        fullName: "IT Department",
        orgName: "My Organization",
        productId: ""
      )
    ),
    nicSettingMap: [CustomizationAdapterMapping(
       adapter: CustomizationIPSettings(
         gateway: ["10.*.*.*.1"],               # This was having the gateway value that is not specified in the vCenter's customization specification manager 
         ip: CustomizationFixedIp( ipAddress: "10.10.10.1" ),
         subnetMask: "255.*.*.*"		# This was having the subnet mask value that is not specified in the vcenter's customization specification manager
       )
     )],
    options: CustomizationWinOptions( changeSID: true, deleteAccounts: false )
  ),
  location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-151"),
    pool: ResourcePool("resgroup-8")
  ),
  powerOn: false,
  template: false
)
Finished creating virtual machine testVM4
Powered on virtual machine testVM4
```

### Expected Result:

Vm to build with the IP address passed in --cips and other values as default gateway,netmask and dns should be taken from the --cspec which is the customization specification manager 

### Actual Result:

VM is built with the IP address passed --cips but the gateway,netmask are generated randomly by ignoring the values specified in the customization specification manager

**Comment by swalberg** [comment]
Hi, we expect the netmask to be passed in CIDR notation. Try `--cips 10.10.10.1/24` instead, and don't try to override in the cspec. The IP and gateway go on the same object we send to vsphere, so merging a CLI IP and a cspec netmask ends up being difficult.

**Comment by Zorrom** [comment]
The IP and gateway go on the same object we send to vsphere, so merging a CLI IP and a cspec netmask ends up being difficult.
Sorry I couldnt understand the above statement. Kindly add few more information to this.

So do you meant to say that I have to build a VM with my --cips as 10.10.10.1/subnetmask_range. So what about my DNS and gateway settings, as they are part of the cspec and I would need them to be exactly assigning the same value as specified in the customization specification manager for successful VM build

**Comment by swalberg** [comment]
Hi, sorry, my comment may have been more technical detail than necessary. Cloning a VM involves building a big data structure based on what's passed on the command line, then it's merged with what's stored on the server cspec if it was used. The IP and subnet "go together", so we'd need to override them in the cspec as a unit. It would be difficult to get the IP from the command line and the netmask from the cspec, plus it would end up being confusing for all.

The DNS and gateway are separate objects so it's no problem to pass those in the cspec. You can also use `--cdnsips` and `--cgw` on the CLI if you'd prefer. If your gateway is the `.1` of the subnet then you can omit it, FWIW.

**Comment by swalberg** [comment]
Meant to add that what we do at work is put as much stuff as possible on the command line rather than the cspec. So for Linux clones it's all on the command line (no cspec), and for Windows, the cspec just has the DNS and AD info so sysprep can join the box to the domain.

**Comment by Zorrom** [comment]
Hi Swalberg,
    Yes, I tried to pass the IP and the subnet mask like 10.0.0.1/mysubnet_range and it successfully assigned the ip,netmask and default gateway. But it didnt take my DNS settings value from the cspec and the DNS settings are blank on the VM which is built.
    I tried passing the DNS values using --cdnsips and then they took it, but I want them to take it from the cspec. Any suggestion on this

**Comment by swalberg** [comment]
Hm, can you run it with the proper `--cips` and no dns/gw CLI opts, and show me the output when using `-VV` please? This _should_ work; we do something similar here for Windows nodes.

**Comment by Zorrom** [comment]
Hi Sean, 
     Please find the logs below

[root@chefworkstaion .chef]# knife vsphere vm clone testVM3 --dest-folder Chef_Test --template NewTemplate -f Chef_Test --datastore my_datastore --cips 10.0.0.1/23 --cspec win12 --start -VV
Cloning template NewTemplate to new VM testVM3
VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec( deviceChange: [] ),
  customization: CustomizationSpec(
    encryptionKey: [48,
     -126,
     4,
     26,
     48,
     -126,
     3,
     *
     *
      # Too many numbers, removing them to make the thread look smaller
     -114,
     120,
     94,
     -68,
     -13,
     16,
     30],
    globalIPSettings: CustomizationGlobalIPSettings(
      dnsServerList: [],
      dnsSuffixList: []
    ),
    identity: CustomizationSysprep(
      guiRunOnce: CustomizationGuiRunOnce(
        commandList: ["net stop myservice",
         "reg delete myregkey"]
      ),
      guiUnattended: CustomizationGuiUnattended(
        autoLogon: true,
        autoLogonCount: 1,
        password: CustomizationPassword(
          plainText: false,
          value: "FwIuXmNRTmtXpgNlruE3UNi3MAO1Fz2yVKqEmSQwd/3buP6VbQZp3nAJZoxaFo9AoPgrB8LY                     4XEtAkUHQcQMkq6pdKRXtBX+WzMSrnnbWqFSL+54gd+gM3gAkYkqBEpD3/p99pB6pnaAvvGlEqRkZAR2T3PvWev5BK                     BFw2jfnMWAjuabi+ferV0t4BKxSD8/Ec5K8kncCjnBcOFMGD6OL7MRUDMeqkHhaD3wRlPtVd3MLPndX+jueqHkx5Qx                     3ICXOOJ50beGHhSJRkz6NVrnMCX5wO0HpM9izBrnjHpqMCEa2o30+9PA7XjY/G682uRyCpCne5YxROSqCvD6us8opA                     =="
        ),
        timeZone: 33
      ),
      identification: CustomizationIdentification( joinWorkgroup: "WORKGROUP"
      ),
      userData: CustomizationUserData(
        computerName: CustomizationVirtualMachineName(  ),
        fullName: "IT Department",
        orgName: "My Organization",
        productId: ""
      )
    ),
    nicSettingMap: [CustomizationAdapterMapping(
       adapter: CustomizationIPSettings(
         gateway: ["10.*.*.1"],
         ip: CustomizationFixedIp( ipAddress: "10.0.0.1" ),
         subnetMask: "255.*.*.0"
       )
     )],
    options: CustomizationWinOptions( changeSID: true, deleteAccounts: false )
  ),
  location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-151"),
    pool: ResourcePool("resgroup-8")
  ),
  powerOn: false,
  template: false
)
Finished creating virtual machine testVM3
Powered on virtual machine testVM3

On the same command if I pass the dns settings using --cdnsips, I can see in the logs showing my dns values
dnsServerList: [10.0.0.2,10.0.0.3]

The same command if I run without --cips and --cdnsips and only use --cspec, I am getting a dnsserverlist right after the line  nicSettingMap: , which is coming from the customization specification manager.

**Comment by swalberg** [comment]
Hm, this one is puzzling. It does look like it's set along with the NIC in the customization so we're going to override it when we set the IP.

Not sure if this helps, but can you pass it on the command line and later enforce it with group policy/chef/whatever? Many of the customization options are just there to get the box running and we expect that once the server is built that something else will take over managing it.

One option would be to create a [plugin](https://github.com/chef-partners/knife-vsphere/wiki/Sample-plugin-to-do-unattended-Windows-installations) that pulls down the cspec and "fixes up" the spec prior to it getting sent to vsphere.

**Comment by Zorrom** [comment]
Hi Sean,
    Yeah I'll look at the custom plugins options , but for now my --cdnsips are working fine. So I am good with that as of now, and hence closing this issue. Thanks for all your assistance on this. Much appreciated :+1:
