### ISSUE TITLE
CPU and Memory Hot plug Enablement

### ISSUE THREAD

**Issue by BhargaviAllada** [chef-partners/knife-vsphere#434]
### Versions:

* Version of knife-vsphere: 2.0.1
* Version of chef: 13.6.4

### Platform Details

* Version of vSphere: Version 6.5.0.10000 Build 7119157
* Version of ESXi: 6.5.0

### Scenario:
We are trying to Enable the CPU and Memory Hot plug post cloning the VM.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or 
Command:
knife vsphere vm find --pool 'Pool_Name' --match-name VM_Name --cpu-hot-add-enabled

This command is giving us the output with the status true or false (Enabled or Disabled).
Is there any command to enable it if it is disabled?

### Expected Result:
We need to enable the CPU and Memory Hot Plug if it is disabled.

### Actual Result:
The command is giving the status if it is enabled or disabled.

**Comment by swalberg** [comment]
Hi, the `knife vsphere vm find` command will not make any changes to the VM. It's just for reporting on status.

`knife vsphere vm config VM_Name cpuHotAddEnabled true` might work though (It's a boolean, where we normally expect a string, so I'm kinda curious...)

**Comment by BhargaviAllada** [comment]
Hi Swalberg, 
Great! the command [knife vsphere vm config VM_Name cpuHotAddEnabled true] worked. 
Thanks! :)

**Comment by swalberg** [comment]
Awesome, memory should work the same way too.

If you want this to happen during clone rather than after, look at the section on plugins in the README. A plugin can modify the clone settings we send to vsphere.

Going to close this issue but if anything pops up please reopen it or make a new one as you need.

Sean
