### ISSUE TITLE
Error message shows VM instead of template name

### ISSUE THREAD

**Issue by aaronkjones** [chef-partners/knife-vsphere#435]
### Versions:

* Version of knife-vsphere: 2.1.1

### Scenario:
When creating a VM from a template, the error message is misleading. I had a typo in the template name, so it could not find the template. However, the error message said could not find the VM, which does not make sense because it is being created and should not already exist.

### Expected Result:
FATAL: Could not find template <templatename>

### Actual Result:
knife vsphere clone <vmname> --template <templatename> ...
FATAL: Could not find template <vmname>

**Comment by aaronkjones** [comment]
The line in question is [here](https://github.com/chef-partners/knife-vsphere/blob/7f0c3e30c035225c106d1d88b10d69d314b67660/lib/chef/knife/vsphere_vm_clone.rb#L361):
```
src_vm = get_vm_by_name(get_config(:source_vm), get_config(:folder)) || fatal_exit("Could not find template #{vmname}")
```

Maybe it needs to be:
```
src_vm = get_vm_by_name(get_config(:source_vm), get_config(:folder)) || fatal_exit("Could not find template #{source_vm}")
```

**Comment by swalberg** [comment]
Good find (both the bug and the solution), thank you!
