### ISSUE TITLE
Knife Vsphere Clone Error with fixed ip

### ISSUE THREAD

**Issue by Sagardas72** [chef-partners/knife-vsphere#447]
### Versions:

* Version of knife-vsphere: 2.1.1
* Version of chef: 14.2.0

### Platform Details

* Version of vSphere: 6.0
* Version of ESXi: 6.0

### Scenario:

I am trying to clone a Windows Server 2016 VM using a Template and Customization Spec, and bootstrap it to the Chef Server

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:

knife vsphere vm clone TestVMVSphereKnife -N TestVMVSphereKnife --template XXXXXX -f Templates --bootstrap --cspec XXXXXX -r 'XXX' --bootstrap-ipv4 --bootstrap-nic 1 -VVV
INFO: Using configuration from XXXXX/.chef/knife.rb
DEBUG: value for config item datastore:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item chef_node_name: TestVMVSphereKnife
DEBUG: value for config item vsphere_host: XXXXX
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: administrator@vsphere.local
DEBUG: value for config item vsphere_pass: XXXX
DEBUG: value for config item vsphere_pass: XXXX
DEBUG: value for config item vsphere_pass: XXXX
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: XXX
DEBUG: value for config item source_vm: XXXXXX
DEBUG: value for config item folder: Templates
DEBUG: value for co
nfig item vsphere_dc: XXX

DEBUG: value for config item linked_clone:
DEBUG: value for config item host:
DEBUG: value for config item resource_pool:
DEBUG: value for config item vsphere_dc: XXX

DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount:
DEBUG: value for config item customization_corespersocket:
DEBUG: value for config item customization_memory:
DEBUG: value for config item customization_memory_reservation:
DEBUG: value for config item customization_macs: auto
DEBUG: value for config item customization_ips:
DEBUG: value for config item customization_sw_uuid:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item customization_spec: XXXXX
DEBUG: value for config item customization_spec: XXXXX
DEBUG: value for config ite
m disable_customization: false
DEBUG: value for config item customization_dns_ips:
DEBUG: value for config item customization_dns_suffixes:
DEBUG: value for config item customization_domain:
DEBUG: value for config item customization_plugin:
DEBUG: value for config item folder: Templates
DEBUG: value for config item vsphere_dc: HOU

DEBUG: value for config item source_vm: XXXXX
Cloning template XXXXXXXX to new VM TestVMVSphereKnife

Finished creating virtual machine TestVMVSphereKnife
DEBUG: value for config item customization_plugin:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item power:
DEBUG: value for config item bootstrap: true
DEBUG: value for config item vsphere_dc: XXX

Powered on virtual machine TestVMVSphereKnife
DEBUG: value for config item bootstrap: true
DEBUG: value for config item ssh_port: 22
DEBUG: value for config item bootstrap_protocol:
DEBUG: Identified os as windows.
Waiting for customization to complete...
DEBUG: value for config item sysprep_timeout: 600
Waiting for sysprep....
.
.
.
Customization of VM TestVMVSphereKnife succeeded. Customization log located at C:/Windows/TEMP/vmware-imc/guestcust.log in the guest OS.
Customization Complete
Waiting for network interfaces to become available...

Found address 10.100.0.50
Waiting for a valid IPv4 address...
DEBUG: value for config item bootstrap_nic: 1
ERROR: knife encountered an unexpected error
This may be a bug in the 'vsphere vm clone' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NoMethodError: undefined method `ipConfig' for nil:NilClass

### Expected Result:

The Cloned VM should bootstrap successfully to the Chef Server

### Actual Result:

The VM gets created after which the undefined method 'ipConfig' is thrown and the execution halts.

**Comment by swalberg** [comment]
Hi was there a stack trace after the exception giving a line number? I _think_ I know where this is but want to make sure.

**Comment by Sagardas72** [comment]
No, unfortunately there was no stack trace which gave out a line number.

**Comment by Sagardas72** [comment]
That solved the problem. Thank you for your help!
