### ISSUE TITLE
Empty list error when there's no snapshots taken from a VM

### ISSUE THREAD

**Issue by aririikonen** [chef-partners/knife-vsphere#89]
Hi,
This is not really an issue of failure, but the error message made me think that this is a code issue. I had to spend some time to actually get any sense out of the error produced and what was actually causing it.

Case:
Trying to --revert to a snapshot with 'knife vsphere vm snapshot -f FOLDER/NAME --revert base_with_disks VM_NAME -VV', but the snapshot list is empty.

Output:
DEBUG: value for config item vsphere_host: SERVER_NAME
DEBUG: value for config item vshere_path: 
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl: 
DEBUG: value for config item vsphere_user: USER
DEBUG: value for config item vsphere_pass: PASSWORD<password>
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host: 
DEBUG: value for config item proxy_port: 
DEBUG: value for config item folder: FOLDER/NAME
DEBUG: value for config item vsphere_dc: DC_NAME
/path/to/lib/chef/knife/vsphere_vm_snapshot.rb:106:in `find_node': undefined method `each' for nil:NilClass (NoMethodError)
	from /path/to/gems/ruby-1.9.3-p448/gems/knife-vsphere-0.9.7/lib/chef/knife/vsphere_vm_snapshot.rb:95:in `run'
	from /path/to/gems/ruby-1.9.3-p448/gems/chef-11.8.2/lib/chef/knife.rb:485:in `run_with_pretty_exceptions'
	from /path/to/gems/ruby-1.9.3-p448/gems/chef-11.8.2/lib/chef/knife.rb:174:in `run'
	from /path/to/gems/ruby-1.9.3-p448/gems/chef-11.8.2/lib/chef/application/knife.rb:133:in `run'
	from /path/to/gems/ruby-1.9.3-p448/gems/chef-11.8.2/bin/knife:25:in `<top (required)>'
	from /path/to/gems/ruby-1.9.3-p448/bin/knife:23:in `load'
	from /path/to/gems/ruby-1.9.3-p448/bin/knife:23:in `<main>'

Cause:
The snapshot list for the VM is empty.

Maybe just add error handling for this case and output the cause.

Br, Ari

**Comment by swalberg** [comment]
Closing to clean up the backlog. But I do get the need for better error reporting, and will be working towards some of that.
