### ISSUE TITLE
Computer name with only integers fails to clone

### ISSUE THREAD

**Issue by jdelaney731** [chef-partners/knife-vsphere#91]
example (not all params provided): knife vsphere vm clone 201402281
errors out:
ERROR: RbVmomi::Fault: InvalidArgument: A specified parameter was not correct.
spec.identity.userData.computerName

failure is in vsphere_vm_clone.rb link 228:
task = src_vm.CloneVM_Task(:folder => dest_folder, :name => vmname, :spec => clone_spec)

**Comment by jjasghar** [comment]
Please reopen if this is still relevant, and post the new error :metal.
