### ISSUE TITLE
Vapp Support

### ISSUE THREAD

**Issue by bniemeyer** [chef-partners/knife-vsphere#96]
```
$ knife vsphere pool list
Folder:
ClusterComputeResource: # New ESXi Hosts unConfigure
ClusterComputeResource: UCS1
VirtualApp: UCS1/Resources/TEST
Unknown type VirtualApp, not enumerating
```

---  Each folder below contains Vapps - Each Vapp contains 1-30 vm's -- they do not get enumerated.

```
$ knife vsphere vm list
Folder Name: Discovered virtual machine
Folder Name: Apps
Folder Name: Infrastructure
Folder Name: Enterprise Apps
```

**Comment by swalberg** [comment]
So when we [enumerate a collection](https://github.com/ezrapagel/knife-vsphere/blob/master/lib/chef/knife/base_vsphere_command.rb#L283-L295) the contents seem to be located at different parts of the API depending on the collection type.

We'd need to figure out how to look at the contents of a vApp collection, and could implement it then.

**Comment by omar2345** [comment]
Hello, just curious is there a plan to update this?  I've got about 50 vApps that I cannot list.  If not, I'll need to migrate to resource pools instead.  Thanks everyone.

**Comment by swalberg** [comment]
Initially we didn't use vapps at $dayjob but I noticed we have one now. We
should support this and I'll give it a shot.

Are you able to run development versions of this gem if I was able to throw
a branch your way for testing?

On Tuesday, August 11, 2015, omar2345 <notifications@github.com> wrote:

> Hello, just curious is there a plan to update this? I've got about 50
> vApps that I cannot list. If not, I'll need to migrate to resource pools
> instead. Thanks everyone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ezrapagel/knife-vsphere/issues/96#issuecomment-130101064>
> .
>


-- 
Sean Walberg <sean@ertw.com>    http://ertw.com/

**Comment by omar2345** [comment]
Definitely.  Thanks again!

**Comment by swalberg** [comment]
Can you try a branch from my repo? https://github.com/swalberg/knife-vsphere/tree/descend_into_vapp_folders

It's not working in my environment but I'm pretty sure there's something unique about the way we're doing things here.

If not, can you get me some output to look at? The messages changed somewhat since the issue was created.

**Comment by omar2345** [comment]
pool list will now display my vApps!   

>knife vsphere pool list | grep vapp
Pool: my_cluster/my_vapp

However, vm list will not display vApps or VMs within vApps.  

Within 'my_vapp' I have a VM called 'my_vapp_vm1'.  It does not get displayed.  

>knife vsphere vm list -r | grep vapp
>

**Comment by swalberg** [comment]
Thanks. I had a bit of time to look this morning and it seems that the `vm list` starts from a different spot in the tree and the `pool list`. I need to look into why and what that means.

**Comment by omar2345** [comment]
If you need me to test anything or find a solution please let me know.  Thanks for your help with this.

**Comment by djmbm** [comment]
Any further word on this?

**Comment by swalberg** [comment]
I wasn't able to get much further. Does my branch help at all?

**Comment by djmbm** [comment]
Unfortunately no, as we also need the VM listing within the vApp. I actually have a call later today with some Chef Engineers about adding OVA and vApp deployment capabilities to knife vsphere, so we can only hope that it gets some action.

**Comment by swalberg** [comment]
Let me know what happens. We don't use OVA or vApp here so it's hard for me to duplicate these problems.

**Comment by swalberg** [comment]
Going through some older issues and will close this. While I'd accept a PR for a feature like this, demand has been low enough that it's not something I'd be tracking for the backlog.
